Issue #9929: Ensure Suns Java Style Checkstyle Coverage
checkstyle/checkstyle pull request #10008
Opened 2021-05-15 21:12 UTC by Ritik2604

fixes Issue #9929  Ensure sun java checkstyle coverage

Mapped CommentsIndentationCheck to Sun style Block Comment

2021-07-20 21:05 UTC, Ritik2604 commented
@romani  review needed

2021-08-25 02:52 UTC, rnveach commented
GitHub, rebase

2022-03-13 03:45 UTC, rnveach commented
@Ritik2604 Are you still willing to get this merged? If so, please start by rebasing this on the latest master.

2022-03-19 17:36 UTC, pbludov commented
GitHub, generate site

2022-03-30 05:11 UTC, romani requested changes
Items

2022-03-30 05:11 UTC, romani commented on src/xdocs/sun_style.xml
> +                    CommentsIndentation
We need to put comment here that we do not cover
>```
block comment should be preceded by a blank line to set it apart from the rest of the code.

/*
 * Here is a block comment.
 */
```
It should be done by some other Chek

2022-03-30 05:11 UTC, romani commented on src/it/resources/com/sun/checkstyle/test/chapter5comments/rule511blockcomments/InputCommentsIndentationSurroundingCode.java
> +            int k = 0; // trailing comment
I do not see a reason to copy all that inputs better to use few and focus on that matter for sun style description.

2022-03-30 05:15 UTC, romani commented on src/xdocs/sun_style.xml
> +                    CommentsIndentation
We do not have check that demand empty line in block comment :)

2022-04-09 20:35 UTC, rnveach commented
@Ritik2604 ping

2022-05-06 02:54 UTC, nick-mancuso commented
We have lost contact with author, anyone is welcome to reuse code to solve related issue.

2022-05-06 02:54 UTC, closed without merging