Issue #9391: update example of AST for TokenTypes.ANNOTATION_DEF
checkstyle/checkstyle pull request #10036
Opened 2021-05-24 13:18 UTC by Rahulkhinchi03

fixes #9391 
![picture](https://user-images.githubusercontent.com/71710042/119345507-9a13f100-bcb6-11eb-9ad7-5e4fa6c72519.png)

Java Code used here:
<pre>
<code>
public class MyClass {
   public @interface MyAnnotation {
       int value() default 1;
    }
}
</code>
</pre>

AST Format of the Java Doc:
<pre>
<code>
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> MyClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:21]
    |--LCURLY -> { [1:21]
    |--ANNOTATION_DEF -> ANNOTATION_DEF [2:3]
    |   |--MODIFIERS -> MODIFIERS [2:3]
    |   |   `--LITERAL_PUBLIC -> public [2:3]
    |   |--AT -> @ [2:10]
    |   |--LITERAL_INTERFACE -> interface [2:11]
    |   |--IDENT -> MyAnnotation [2:21]
    |   `--OBJBLOCK -> OBJBLOCK [2:34]
    |       |--LCURLY -> { [2:34]
    |       |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [3:7]
    |       |   |--MODIFIERS -> MODIFIERS [3:7]
    |       |   |--TYPE -> TYPE [3:7]
    |       |   |   `--LITERAL_INT -> int [3:7]
    |       |   |--IDENT -> value [3:11]
    |       |   |--LPAREN -> ( [3:16]
    |       |   |--RPAREN -> ) [3:17]
    |       |   |--LITERAL_DEFAULT -> default [3:19]
    |       |   |   `--EXPR -> EXPR [3:27]
    |       |   |       `--NUM_INT -> 1 [3:27]
    |       |   `--SEMI -> ; [3:28]
    |       `--RCURLY -> } [4:4]
    `--RCURLY -> } [5:0]
</code>
</pre>

Expected Java Doc to changes:
<pre>
<code>
         |   |--MODIFIERS -&gt MODIFIERS
         |   |--TYPE -&gt TYPE 
         |   |   `--LITERAL_INT -&gt int 
         |   |--IDENT -&gt value 
         |   |--LPAREN -&gt ( 
         |   |--RPAREN -&gt ) 
         |   |--LITERAL_DEFAULT -&gt default 
         |   |   `--EXPR -&gt EXPR 
         |   |       `--NUM_INT -&gt 1 
         |   `--SEMI -&gt ; 
         `--RCURLY -&gt } 
   
</code>
</pre>

2021-05-24 14:22 UTC, Rahulkhinchi03 commented
@romani can you please help me how can I resolve this failing issue?

2021-05-24 16:27 UTC, Rahulkhinchi03 commented
@pbludov or @romani  please review my changes and approve for the same!

2021-05-25 06:26 UTC, AkMo3 approved these changes

2021-05-25 06:58 UTC, timurt requested changes

2021-05-25 06:58 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *      |   |--IDENT -&gt; value
someValue

2021-05-25 06:58 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *      |   |       `--NUM_INT -&gt; 1
there is `default` in example
```
     * public @interface MyAnnotation     
     * {     
     *     int someValue();    
     * }
```

please use old example and update AST

2021-05-25 07:45 UTC, closed without merging