Issue #9460: update example of AST for TokenTypes.LCURLY
checkstyle/checkstyle pull request #10108
Opened 2021-06-13 15:16 UTC by Hreshi

Resolves : Issue #9460: update example of AST for TokenTypes.LCURLY

![site](https://user-images.githubusercontent.com/59061299/121813136-4c245480-cc88-11eb-8910-27e2a50875d7.png)

2021-06-13 18:42 UTC, romani commented
Please share details of ast print

2021-06-14 03:27 UTC, Hreshi commented
AST print result
![ast](https://user-images.githubusercontent.com/59061299/121835224-537e4900-ccee-11eb-83af-00fee34ebb02.png)

Javadoc site according to latest commit

![site](https://user-images.githubusercontent.com/59061299/121835276-73ae0800-ccee-11eb-8084-0e5ceeb0744f.png)

2021-07-17 21:57 UTC, romani requested changes
minor before merge:

2021-07-17 21:57 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * int num
please add space before "{" and indent "int num" by 2 spaces.
This code is still for humans to read, formatting matters.

2021-07-18 05:49 UTC, romani commented
Please squash all commits in one. In PR should be single commit

2021-07-18 05:51 UTC, Hreshi commented
Yes i am working on it

2021-07-18 09:03 UTC, closed without merging