update example of AST for TokenTypes.LAMBDA #9458
checkstyle/checkstyle pull request #10324
Opened 2021-07-13 14:43 UTC by Hrushi20

Closes #9458

![Screenshot (6)](https://user-images.githubusercontent.com/65367566/125469547-3e49c9ff-93f0-4c9b-aa05-55860041c0d8.png)

Expected update example of AST for TokenTypes.LAMBDA

![Screenshot (4)](https://user-images.githubusercontent.com/65367566/125469948-67efed55-706a-45ee-a8ab-0a290920aea3.png)

Terminal view of AST

![Screenshot (5)](https://user-images.githubusercontent.com/65367566/125470111-3683efd2-4e56-427a-abdd-71fa211e11be.png)

```
public class Test{
    public static void main(String[] args) {
        int [] a = {1,2,3};

        Arrays.stream(a).map(el -> el);
    }
}

$ java -jar target/checkstyle-8.45-SNAPSHOT-all.jar -t ./src/main/java/Test.java

IMPORT -> import [1:0]
|--DOT -> . [1:16]
|   |--DOT -> . [1:11]
|   |   |--IDENT -> java [1:7]
|   |   `--IDENT -> util [1:12]
|   `--IDENT -> Arrays [1:17]
`--SEMI -> ; [1:23]
CLASS_DEF -> CLASS_DEF [3:0]
|--MODIFIERS -> MODIFIERS [3:0]
|   `--LITERAL_PUBLIC -> public [3:0]
|--LITERAL_CLASS -> class [3:7]
|--IDENT -> Test [3:13]
`--OBJBLOCK -> OBJBLOCK [3:17]
    |--LCURLY -> { [3:17]
    |--METHOD_DEF -> METHOD_DEF [4:4]
    |   |--MODIFIERS -> MODIFIERS [4:4]
    |   |   |--LITERAL_PUBLIC -> public [4:4]
    |   |   `--LITERAL_STATIC -> static [4:11]
    |   |--TYPE -> TYPE [4:18]
    |   |   `--LITERAL_VOID -> void [4:18]
    |   |--IDENT -> main [4:23]
    |   |--LPAREN -> ( [4:27]
    |   |--PARAMETERS -> PARAMETERS [4:28]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [4:28]
    |   |       |--MODIFIERS -> MODIFIERS [4:28]
    |   |       |--TYPE -> TYPE [4:28]
    |   |       |   |--IDENT -> String [4:28]
    |   |       |   `--ARRAY_DECLARATOR -> [ [4:34]
    |   |       |       `--RBRACK -> ] [4:35]
    |   |       `--IDENT -> args [4:37]
    |   |--RPAREN -> ) [4:41]
    |   `--SLIST -> { [4:43]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [5:7]
    |       |   |--MODIFIERS -> MODIFIERS [5:7]
    |       |   |--TYPE -> TYPE [5:7]
    |       |   |   |--LITERAL_INT -> int [5:7]
    |       |   |   `--ARRAY_DECLARATOR -> [ [5:10]
    |       |   |       `--RBRACK -> ] [5:11]
    |       |   |--IDENT -> a [5:13]
    |       |   `--ASSIGN -> = [5:15]
    |       |       `--ARRAY_INIT -> { [5:17]
    |       |           |--EXPR -> EXPR [5:18]
    |       |           |   `--NUM_INT -> 1 [5:18]
    |       |           |--COMMA -> , [5:19]
    |       |           |--EXPR -> EXPR [5:20]
    |       |           |   `--NUM_INT -> 2 [5:20]
    |       |           |--COMMA -> , [5:21]
    |       |           |--EXPR -> EXPR [5:22]
    |       |           |   `--NUM_INT -> 3 [5:22]
    |       |           |--COMMA -> , [5:23]
    |       |           |--EXPR -> EXPR [5:24]
    |       |           |   `--NUM_INT -> 4 [5:24]
    |       |           |--COMMA -> , [5:25]
    |       |           |--EXPR -> EXPR [5:26]
    |       |           |   `--NUM_INT -> 5 [5:26]
    |       |           `--RCURLY -> } [5:27]
    |       |--SEMI -> ; [5:28]
    |       |--EXPR -> EXPR [7:28]
    |       |   `--METHOD_CALL -> ( [7:28]
    |       |       |--DOT -> . [7:24]
    |       |       |   |--METHOD_CALL -> ( [7:21]
    |       |       |   |   |--DOT -> . [7:14]
    |       |       |   |   |   |--IDENT -> Arrays [7:8]
    |       |       |   |   |   `--IDENT -> stream [7:15]
    |       |       |   |   |--ELIST -> ELIST [7:22]
    |       |       |   |   |   `--EXPR -> EXPR [7:22]
    |       |       |   |   |       `--IDENT -> a [7:22]
    |       |       |   |   `--RPAREN -> ) [7:23]
    |       |       |   `--IDENT -> map [7:25]
    |       |       |--ELIST -> ELIST [7:32]
    |       |       |   `--LAMBDA -> -> [7:32]
    |       |       |       |--IDENT -> el [7:29]
    |       |       |       `--EXPR -> EXPR [7:35]
    |       |       |           `--IDENT -> el [7:35]
    |       |       `--RPAREN -> ) [7:37]
    |       |--SEMI -> ; [7:38]
    |       `--RCURLY -> } [9:4]
    `--RCURLY -> } [10:0]

```

2021-07-14 20:48 UTC, pbludov requested changes

2021-07-14 20:48 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *  Arrays.stream(a).map(el -&gt; el);
The code snippet should be compilable. For example, something like
`IntStream.of(1).forEach(n -> {});`

2021-07-14 20:48 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +import java.util.Arrays;
What the reason for this change? This import is not used.

2021-07-17 21:46 UTC, romani requested changes
item:

2021-07-17 21:46 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *               +`--METHOD_CALL -&gt; (
content here should exactly as from CLI, please use it.

2021-11-14 03:56 UTC, romani commented
Fixed in another PR

2021-11-14 03:56 UTC, closed without merging