Issue #10817: Fix IllegalTypeCheck on Record with configured member modifiers
checkstyle/checkstyle pull request #10820
Opened 2021-09-23 18:39 UTC by fprochazka

2021-09-27 10:28 UTC, strkkk requested changes
@fprochazka please also fix ci failures

2021-09-27 10:28 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
> +            if (methodOrVariableDef.getType() != TokenTypes.RECORD_COMPONENT_DEF) {
`methodOrVariableDef.getType() != TokenTypes.RECORD_COMPONENT_DEF`
now variable name `methodOrVariableDef` looks weird, please rename it to something abstract like `token` or `ast`

Please also correct javadoc

2021-09-27 10:28 UTC, strkkk commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndMemberModifiersSpecified.java
> +} // ok
no need to place ok comment on every line, it should only present on lines where violation can occur (but it is not)

Please remove all ok comments and add one more field to record ctor with some illegal type (listed in config in header)

2021-11-09 10:42 UTC, Rahulkhinchi03 commented
Hello, I want to work on this issue

2021-11-09 12:35 UTC, fprochazka commented
@Rahulkhinchi03 I was not able to find the time to fight with the CI so far. If you want to, I'd be happy to let you take over and fix it. Just create a new branch and a new MR and I'll close this one if you manage to solve it.

2021-11-09 14:42 UTC, Rahulkhinchi03 commented
Though I am also trying to understand the bug first 😅

2021-11-13 00:46 UTC, romani commented
@Rahulkhinchi03 
as soon as you create your PR we can close this PR. take ownership of this PR code and continue.

2021-11-18 17:18 UTC, Rahulkhinchi03 commented
@romani sir, you can close this PR now. I created a new pr #10958

2021-11-18 22:36 UTC, closed without merging