Issue #10835: Fixing default access modifier for CheckUtil
checkstyle/checkstyle pull request #10840
Opened 2021-10-02 11:47 UTC by Vyom-Yadav

Resolves #10835: JavadocMethod accessModifiers incorrectly interpreted for interface class

2021-10-02 13:49 UTC, Vyom-Yadav commented
@strkkk Can you review?

2021-10-02 14:46 UTC, rnveach commented
We will need regression from every check that uses this util method.

2021-10-03 01:17 UTC, romani commented
Please share list of depending Checks

2021-10-03 03:36 UTC, Vyom-Yadav commented
Github, generate report

2021-10-03 04:07 UTC, Vyom-Yadav commented
@romani Report is clean

2021-10-05 10:16 UTC, Vyom-Yadav commented
Strange `pitest-ant` is completing successfully on my local setup. I even replaced them with given mutations (ignoreList), they were the same only.

2021-10-06 06:12 UTC, pbludov requested changes
Please make suggested changes. Also, there should be some test inputs for enum constructor and enum constant.

2021-10-06 06:12 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
> +        final String scope = ScopeUtil.getScopeFromMods(modifiersToken).toString();
Please never convert an enum to another via string representation.
This is slow and will be broken after any kind of refactoring.

Secondly: this code is extremely inefficient. `ScopeUtil.getScopeFromMods` returns the declared scope if present. No need for the loop below.

Then, please note that `Scope` is deprecated. See #3511 for the details.

I think that the right way is to make `getAccessModifierFromModifiersTokenDirectly` return `null` if none modifiers present. Then fix `CheckUtil#getAccessModifierFromModifiersToken` to 
```java
    public static AccessModifierOption getAccessModifierFromModifiersToken(DetailAST ast) {
        final DetailAST modsToken = ast.findFirstToken(TokenTypes.MODIFIERS);
        AccessModifierOption accessModifier = getAccessModifierFromModifiersTokenDirectly(modsToken);

        if (accessModifier == null) {
            if (ScopeUtil.isInEnumBlock(ast)) {
                if (ast.getType() == TokenTypes.ENUM_CONSTANT_DEF) {
                    accessModifier = AccessModifierOption.PUBLIC;
                }
                else if (ast.getType() == TokenTypes.CTOR_DEF) {
                    accessModifier = AccessModifierOption.PRIVATE;
                }
                else {
                    accessModifier = AccessModifierOption.PACKAGE;
                }
            }
            else if (ScopeUtil.isInInterfaceOrAnnotationBlock(ast)) {
                accessModifier = AccessModifierOption.PUBLIC;
            }
            else {
                accessModifier = AccessModifierOption.PACKAGE;
            }
        }
        
        return accessModifier;
    }
```
```

2021-10-12 10:05 UTC, Vyom-Yadav commented
@pbludov Um these are not the final changes, I am still working on it, a couple of issues are there which I will solve as soon as I get some time.

2021-10-16 04:46 UTC, Vyom-Yadav commented
@pbludov wercker is failing on which project

2021-11-07 11:21 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
You could put these tests in their respective check test classes.

2021-11-07 11:52 UTC, Vyom-Yadav commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
I initially did but code coverage is a problem as I have made modifications to CheckUtil

2021-11-07 12:20 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
If this is for mutation coverage, you can add the corresponding check test classes to `targetTests` for `com.puppycrawl.tools.checkstyle.utils` package in `pom.xml`.

2021-11-07 12:35 UTC, nmancus1 commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
> +        final DetailAST modsToken = ast.findFirstToken(TokenTypes.MODIFIERS);
>  already provided the list of checks

It is better to share list of checks and method of generating list:

```
➜  checkstyle git:(master) grep -R -I "getAccessModifierFromModifiersToken" | grep -v "Test"     
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java:                        CheckUtil.getAccessModifierFromModifiersToken(parent.getParent()))) {
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java:            CheckUtil.getAccessModifierFromModifiersToken(ast);
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java:                .getAccessModifierFromModifiersToken(ast);
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:    public static AccessModifierOption getAccessModifierFromModifiersToken(DetailAST ast) {
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:            accessModifier = getAccessModifierFromModifiersTokenDirectly(modsToken);
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:    private static AccessModifierOption getAccessModifierFromModifiersTokenDirectly(
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java:                returnValue = getAccessModifierFromModifiersTokenDirectly(mods);


```

2021-11-07 13:26 UTC, Vyom-Yadav commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
Code coverage violations are given by jacoco, anything for that other than reducing coverage?

2021-11-07 13:54 UTC, nmancus1 commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
In my experience, Jacoco does not care about the location of the test, only that code is hit. If you move these tests to the corresponding check test classes and push your changes, I would be happy to take a look at the failure and offer some suggestions.

2021-11-07 16:03 UTC, Vyom-Yadav commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
> +public class CheckUtilTest extends AbstractModuleTestSupport {
Sorry, my bad, when I ran the code coverage test from IntelliJ, I didn't configure the module properly, thanks for clarifying, I have fixed it now.

2021-11-07 16:47 UTC, rnveach approved these changes

2021-11-11 21:39 UTC, romani approved these changes
@Vyom-Yadav , thanks a lot.
final version is way more clean !!!! good job.

2021-11-11 21:39 UTC, merged