Issue #11185: Run regression testing in CI over openjdk17
checkstyle/checkstyle pull request #11186
Opened 2022-01-12 06:07 UTC by nmancus1

Closes #11185.

Not much has changed, some non compilable files have been removed from the repo, as have a few compilable files. All compilable files related to new syntax are parsed with no issue.

Reviewers, please ignore commits before d413bd05ab23cb1e39136de0e1d2a207596e0ffa

2022-01-17 08:32 UTC, pbludov approved these changes

2022-01-17 14:32 UTC, rnveach requested changes
ok to merge once other commits are removed

2022-01-18 13:44 UTC, nmancus1 commented
GitHub, rebase

2022-01-22 22:26 UTC, romani approved these changes
ok to merge for last two commits.

2022-01-23 23:23 UTC, rnveach approved these changes

2022-01-23 23:24 UTC, merged