Update doc for FinalParameters #7588
checkstyle/checkstyle pull request #11202
Opened 2022-01-16 11:43 UTC by Taniya003

Fixes #7588

\> type config.xml
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalParameters">
        </module>
    </module>
</module>

```
\> type Point.java
```
class Point {
    private int m,n;
    private String s;
    public Point(){
        s = "ABC";
    }
    public Point(final int m) { //OK
        this();
        this.m = m;
    }
    public Point(final int m,int n){ //Violation - n should be final
        this();
        this.m = m;
        this.n = n;
    }
    public void methodOne(final int x){ //ok
        //
    }
    public void methodTwo(int x){ //Violation - x should be final
        //
    }

    public static void main(String[] args) { // violation-args should be final
        //
    }
}
```
```
C:\Users\DELL\Desktop\tests>java -jar checkstyle-9.2.1-all.jar -c config.xml Point.java
Starting audit...
[ERROR] C:\Users\DELL\Desktop\tests\Point.java:11:30: Parameter n should be final. [FinalParameters]
[ERROR] C:\Users\DELL\Desktop\tests\Point.java:19:27: Parameter x should be final. [FinalParameters]
[ERROR] C:\Users\DELL\Desktop\tests\Point.java:23:29: Parameter args should be final. [FinalParameters]
Audit done.
Checkstyle ends with 3 errors.
```
\> type config.xml
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalParameters">
        <property name="tokens" value="CTOR_DEF"/>
        </module>
    </module>
</module>
```
\> type Point.java
```
class Point {
    private int m,n;
    private String s;
    public Point(){
        s = "ABC";
    }
    public Point(final int m) { //OK
        this();
        this.m = m;
    }
    public Point(final int m,int n){ //Violation - n should be final
        this();
        this.m = m;
        this.n = n;
    }
    public void methodOne(final int x){ //ok
        //
    }
    public void methodTwo(int x){ //ok
        //
    }

    public static void main(String[] args) { //ok
        //
    }
}
```
```
C:\Users\DELL\Desktop\tests>java -jar checkstyle-9.2.1-all.jar -c config.xml Point.java
Starting audit...
[ERROR] C:\Users\DELL\Desktop\tests\Point.java:11:30: Parameter n should be final. [FinalParameters]
Audit done.
Checkstyle ends with 1 errors.
```
\> type config.xml
```
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalParameters">
        <property name="ignorePrimitiveTypes" value="true"/>
        </module>
    </module>
</module>
```
\> type Point.java
```
class Point {
    private int m,n;
    private String s;
    public Point(){
        s = "ABC";
    }
    public Point(final int m) { //OK
        this();
        this.m = m;
    }
    public Point(final int m,int n){ //OK
        this();
        this.m = m;
        this.n = n;
    }
    public void methodOne(final int x){ //ok
        //
    }
    public void methodTwo(int x){ //OK
        //
    }

    public static void main(String[] args) { //Violation, args should be final
        //
    }
}
```
```
C:\Users\DELL\Desktop\tests>java -jar checkstyle-9.2.1-all.jar -c config.xml Point.java
Starting audit...
[ERROR] C:\Users\DELL\Desktop\tests\Point.java:23:29: Parameter args should be final. [FinalParameters]
Audit done.
Checkstyle ends with 1 errors.
```

2022-01-16 14:15 UTC, romani requested changes
review CIs and fix violations from them
make sure that `mvn verify` pass on your local in terminal before push.

items:

2022-01-16 14:15 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
> + *       public Point(final int m,int n){ //Violation - n should be final
make space after `//` and lovercacse first word. Please apply this for all lines.

`// violation - n should be final`

2022-01-16 14:15 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
> + *       private int m,n;
please make indentation base +2 to keep code shorter at width.

2022-01-16 14:15 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
> + *       s = "ABC";
+2 in indentation.

2022-01-16 14:15 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
> + *           this();
This Check do not care about body content. so please make all metods single line
`public Point(final int m) { }`

2022-01-17 14:11 UTC, Taniya003 commented
**@romani** I got all your points and followed the same. Thanks alot ;)

2022-01-17 14:39 UTC, romani requested changes

2022-01-17 14:39 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
> + *   private String s;
Remove fields
From all examples

2022-02-07 03:47 UTC, romani commented
GitHub, rebase

2022-02-07 03:47 UTC, romani commented
GitHub, generate web site

2022-02-07 03:54 UTC, romani commented
@Taniya003, please rebase to most latest our master code. 
Your  update is awesome, let's do rebase, pass CI and merge.

2022-02-20 08:06 UTC, romani commented
GitHub, generate web site

2022-02-20 08:07 UTC, romani approved these changes
ok to merge

2022-02-20 16:48 UTC, strkkk approved these changes

2022-02-20 16:49 UTC, merged