minor: Updated Inputs for EmptyBlockCheck
checkstyle/checkstyle pull request #11366
Opened 2022-03-06 10:13 UTC by MUzairS15

Based on discussion at https://github.com/checkstyle/checkstyle/pull/11095#pullrequestreview-900959252

2022-03-06 10:33 UTC, romani approved these changes
ok to merge if CI pass

2022-03-06 10:38 UTC, romani commented
@MUzairS15 , do you plan to create all other PRs for all your existing PRs on similar update ?
or do you want me to review all of them and ask the same question ? :) 
please pin me in PR where you think codepoint update is required to your mind.

2022-03-06 17:58 UTC, nick-mancuso commented
Build is failing from false negatives, `EmptyBlockCheck` requires update.

2022-03-06 17:58 UTC, nick-mancuso requested changes
Build is failing from false negatives, `EmptyBlockCheck` requires update.

2022-03-06 18:38 UTC, MUzairS15 commented
> @MUzairS15 , do you plan to create all other PRs for all your existing PRs on similar update ?
> or do you want me to review all of them and ask the same question ? :)
> please pin me in PR where you think codepoint update is required to your mind.

I will add the output of CLI on existing PRs showing need of codepoints and if you want will create separate PRs (just input and test like in this) for those check which are not affected.

2022-03-06 18:45 UTC, nick-mancuso commented
If check requires update -> send PR with check update and new input/UT
If check does not require input -> send PR with only new input/UT

I think this PR was premature, since we found false negative at #11095

2022-03-09 14:16 UTC, romani commented
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=7932&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=771

```
[ERROR]   EmptyBlockCheckTest.testEmptyBlockWithEmoji:215->AbstractModuleTestSupport.verifyWithInlineConfigParser:270->AbstractModuleTestSupport.verifyViolations:427 Violation lines for /home/vsts/work/1/s/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockWithEmoji.java differ.
missing (3): 25, 33, 45
---
expected   : [15, 25, 28, 30, 31, 33, 40, 45]
but was    : [15, 28, 30, 31, 40]

```

2022-03-09 14:19 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockWithEmoji.java
> +        if (a == "🤩12🧐🧐") { } // violation 'Empty if block'
weird side effect, symbols are not even inside next to curly braces, but close enough to confuse Check

2022-03-09 14:21 UTC, MUzairS15 commented
@romani closing this PR since proof that EmptyBlock check  requires update is added in https://github.com/checkstyle/checkstyle/pull/11095

2022-03-09 14:21 UTC, closed without merging