Issue #7624: Updated doc for NoWhitespaceAfter
checkstyle/checkstyle pull request #11577
Opened 2022-04-24 19:41 UTC by IzumiKanata

Issue #7624 Updated
![image](https://user-images.githubusercontent.com/84538746/164992705-60a6095d-c895-4046-83af-0399c20ebcde.png)
````
$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

    <module name = "Checker">
        <property name="charset" value="UTF-8"/>
        <module name="TreeWalker">
          <module name="NoWhitespaceAfter">
            <property name="tokens" value="TYPECAST" />
          </module>
        </module>
    </module>
    
$ cat TYPECASTTest.java
class TYPECASTTest {
  int test6;
  long test8 = (long) test6;// violation,whitespace after '(long)' is not allowed
  long test9 = (long)test6;//OK
}

$ java -jar checkstyle-10.1-all.jar -c config.xml TYPECASTTest.java
Starting audit...
[ERROR] /home/izumi-kanata/checkstyle/TYPECASTTest.java:5:16: ')' is followed by whitespace. [NoWhitespaceAfter]
Audit done.
Checkstyle ends with 1 errors.
````

2022-04-24 20:06 UTC, pbludov commented
Both xdoc and Java source file should be changed. Please run `mvn clean verify` locally.

2022-04-29 05:05 UTC, romani requested changes
Items

2022-04-29 05:05 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
> + * <p>To Configure the check to restrict the use of whitespace after TYPECAST:
Please add same java code example to two config above to show user how behavior changing on same code but different config.

2022-05-28 21:17 UTC, romani commented
Please resolve conflict

2022-05-28 21:20 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
> + * <p>To Configure the check to restrict the use of whitespace after TYPECAST:
Please add java code for each xml config

2022-06-28 03:57 UTC, nick-mancuso commented
@IzumiKanata we will be closing PR if there is no activity, please let us know if you would like to continue or not.

2022-06-28 06:49 UTC, romani commented
We can probably merge this PR but keep issue open.

2022-08-25 04:19 UTC, nick-mancuso commented
> We can probably merge this PR but keep issue open.

I would rather not, there is conflicts now and CI is failing, plus we have added to test input that is over 300 lines long.

2022-10-16 02:23 UTC, rnveach commented
This PR is completely disconnected. User deleted their CS fork.

Patched code can still be downloaded from https://patch-diff.githubusercontent.com/raw/checkstyle/checkstyle/pull/11577.patch .

2022-10-16 22:32 UTC, closed without merging