Issue #11637: Used Shellcheck to resolve SC2236 in Shell Script
checkstyle/checkstyle pull request #11664
Opened 2022-05-22 14:21 UTC by Rahulkhinchi03

Resolves: `SC2236` https://github.com/checkstyle/checkstyle/issues/11637
`SC2236: Use -n instead of ! -z` (https://github.com/koalaman/shellcheck/wiki/SC2236)

2022-05-22 15:16 UTC, nick-mancuso requested changes
@Rahulkhinchi03 please send separate minor commit to fix same violation in .github/workflows/no_old_refs.yml:

```
➜  checkstyle git:(master) ✗ grep -R "! -z"              
.ci/no_old_refs.sh:if [ ! -z "$PR_HEAD_REPO_NAME" ]; then
.ci/no_old_refs.sh:  if [ ! -z "$LINKED_ISSUES" ]; then
.ci/checkchmod.sh:if [[ ! -z $CHMOD ]]; then
.ci/checkchmod.sh:if [[ ! -z $CHMOD ]]; then
.github/workflows/no_old_refs.yml:          if [ ! -z "$LINKED_ISSUES" ]; then

```

2022-05-22 16:41 UTC, nick-mancuso requested changes
@Rahulkhinchi03 please make commit descriptive for anyone to be able understand, such as `minor: Use -n instead of ! -z`

2022-05-23 03:56 UTC, nick-mancuso approved these changes

2022-05-23 03:59 UTC, romani approved these changes

2022-05-25 06:12 UTC, strkkk approved these changes

2022-05-25 06:12 UTC, merged