Issue #11641 Solved SuppressWarningsHolder should allow usage of simple name of Checks in aliasList
checkstyle/checkstyle pull request #11675
Opened 2022-05-28 08:33 UTC by 524130120

Added a method `getDefaultName` which is similar with `getDefaultAlias` except the last line.
I think we can just modify the last line of `getDefaultAlias` since it seems that it's just use for `nameMatches` at: 
https://github.com/checkstyle/checkstyle/blob/51408f83b03311e2c4a86cb28410d4bd7b3388be/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L238
However, it needs to change the Javadoc of `getDefaultName`, so I want to ask for your advice. 
Thank you.

2022-05-30 03:55 UTC, romani requested changes
Items

2022-05-30 03:55 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
> +            .that(SuppressWarningsHolder.getDefaultName("SomeName"))
Please avoid usage of pure Unit testing. Please try to cover code by Inputs.

2022-05-30 04:51 UTC, romani requested changes
Items

2022-05-30 04:51 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
> +        int endIndex = sourceName.length();
This code is very similar to getDefaultAlias
Let's reuse code as much as possible

2022-06-09 14:51 UTC, nick-mancuso commented
@524130120 ping

2022-07-04 05:55 UTC, romani commented
@Kevin222004 , can you help to continue this PR ?

2022-07-04 06:06 UTC, Kevin222004 commented
> @Kevin222004 , can you help to continue this PR ?
> 
> You can reuse any code from this PR, we can close this PR to let you create new PR.

yes I will work on this

2022-07-04 07:49 UTC, closed without merging