Issue #11140: solve S508C_SET_COMP_COLOR
checkstyle/checkstyle pull request #11682
Opened 2022-05-30 17:10 UTC by pbludov

Part of #11140

All colors should be obtained from `UIManager.getColor`

2022-05-31 01:55 UTC, nick-mancuso requested changes
One minor item:

2022-05-31 01:55 UTC, nick-mancuso commented on src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableCellRenderer.java
> +    private static final String COLOR_KEY_TABLE_BACKGROUND = "Table.background";
Please separate fields by empty line.

2022-05-31 23:22 UTC, nick-mancuso approved these changes

2022-06-02 05:52 UTC, strkkk approved these changes

2022-06-02 05:52 UTC, merged