minor: remove multiple return points
checkstyle/checkstyle pull request #11701
Opened 2022-06-06 12:57 UTC by nick-mancuso

Noticed during work on https://github.com/checkstyle/checkstyle/pull/11691, it is better to fix a simple violation like this, than to put a comment on it and let it live in the code base.

2022-06-08 13:27 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
@rnveach , @strkkk , @pbludov .

2022-06-09 06:10 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
may be just move this check to the place where this method is invoked? As I see, there is only one place. It seems that there is no point in invocation if value is null and such logic belongs to other place.

2022-06-11 20:15 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
Good point. It is private method, we are free to refactor code in wide scope

2022-06-12 02:02 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
Assume the question is the prior version or this version better.

I personally prefer simple if guards.
https://deviq.com/design-patterns/guard-clause/

2022-06-13 03:39 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
Guava has implementation of such guards.
In case single null check we can move it out of method - it will make more clear.

2022-06-19 14:04 UTC, nick-mancuso commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
Done

2022-06-19 15:46 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
> +            result = null;
@nick-mancuso please update Javadoc for the method `replaceProperties`.

2022-06-19 18:03 UTC, romani requested changes
items:

2022-06-26 20:33 UTC, romani approved these changes
Ok to merge after fix required by pbludov

2022-06-28 06:39 UTC, romani commented
Pitest common:
```
+ConfigurationLoader.java.html:<td class='covered'><pre><span  class='survived'>                if (value.charAt(pos + 1) == DOLLAR_SIGN) {</span></pre></td></tr>
+ConfigurationLoader.java.html:<td class='uncovered'><pre><span  class='survived'>                    fragments.add(value.substring(pos, pos + 2));</span></pre></td></tr>
 DefaultLogger.java.html:<td class='covered'><pre><span  class='survived'>        closeError = errorStreamOptions == OutputStreamOptions.CLOSE;</span></pre></td></tr>
```

2022-06-28 09:21 UTC, pbludov approved these changes

2022-06-28 18:21 UTC, pbludov commented
> Pitest common:
> 
> ```
> +ConfigurationLoader.java.html:<td class='covered'><pre><span  class='survived'>                if (value.charAt(pos + 1) == DOLLAR_SIGN) {</span></pre></td></tr>
> +ConfigurationLoader.java.html:<td class='uncovered'><pre><span  class='survived'>                    fragments.add(value.substring(pos, pos + 2));</span></pre></td></tr>
> ```

These lines are from method [parsePropertyString](
https://github.com/checkstyle/checkstyle/blob/ed73c8d23a7b76b0d5ed20aa57e190786b75e5e3/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L433-L435), which has not changed in this PR.

This may be related to removed test `testReplacePropertiesNoReplace`. One of these values
```java
final String[] testValues = {null, "", "a", "$a", "{a",
                                         "{a}", "a}", "$a}", "$", "a$b", };
```
is required to kill the mutation.

2022-06-29 18:42 UTC, pbludov approved these changes

2022-07-02 15:36 UTC, rnveach approved these changes

2022-07-02 15:37 UTC, merged