Issue #11584: Adding changes to WriteTag check to solve null javadoc issue
checkstyle/checkstyle pull request #11700
Opened 2022-06-06 08:40 UTC by theWolf1198

Issue #11584

If WriteTag is configured with default settings and there is no Javadoc to check, there used to be a violation with an incorrect error message, hence attempting to solve.

1. Added check to proceed to writeTag verification only when Javadoc comment is not null.
2. Added two unit tests to check on the aforementioned cases and complete code coverage to 100%

2022-06-06 08:41 UTC, theWolf1198 commented
@strkkk, please review this updated PR. Thanks!

2022-06-06 10:48 UTC, strkkk requested changes
Please revert all formatting things (indentation, spaces, etc) and leave only relevant changes.
Also please fix CI issues

2022-06-26 03:55 UTC, romani commented
@theWolf1198 , ping.

2022-08-02 03:30 UTC, nick-mancuso commented
We have lost contact with author, anyone is welcome to reuse code and continue work on this issue.

2022-08-02 03:30 UTC, closed without merging