Issue #11734: Add codenarc to CI for groovy files
checkstyle/checkstyle pull request #11739
Opened 2022-06-14 13:03 UTC by Vyom-Yadav

Resolves #11734

2022-06-16 05:23 UTC, romani commented
I would move this check to Travis or other not high demand CI. It it most likely that such script will never be updated after summer, so better to have it run in some less critical CI.

But we can do this move at end of summer

2022-06-16 14:19 UTC, nick-mancuso requested changes
Items:

2022-06-16 14:19 UTC, nick-mancuso commented on .ci/StarterRuleSet-AllRulesByCategory.groovy.txt
> +
Please remove empty lines

2022-06-18 18:08 UTC, Vyom-Yadav commented on .ci/StarterRuleSet-AllRulesByCategory.groovy.txt
> +
Done.

2022-06-18 18:09 UTC, Vyom-Yadav commented on .ci/jsoref-spellchecker/whitelist.words
> +weired
Came from the starter file I copied, updated it with https://codenarc.org/StarterRuleSet-AllRulesByCategory.groovy.txt, done.

2022-06-22 15:53 UTC, nick-mancuso commented on .ci/jsoref-spellchecker/whitelist.words
> +weired
I was OK with all rule suppressions, just not misspellings that came with them :)

2022-06-23 13:45 UTC, Vyom-Yadav commented on .ci/jsoref-spellchecker/whitelist.words
> +weired
Resolved?

2022-06-24 01:26 UTC, nick-mancuso commented
@Vyom-Yadav see CI failure at https://cloud.drone.io/checkstyle/checkstyle/10876/5/2

2022-06-24 05:57 UTC, Vyom-Yadav commented
> @Vyom-Yadav see CI failure at https://cloud.drone.io/checkstyle/checkstyle/10876/5/2

Done.

2022-06-24 10:46 UTC, nick-mancuso approved these changes

2022-06-24 10:46 UTC, merged