Issue #11720: Kill surviving mutation in RequireThisCheck related to static blocks
checkstyle/checkstyle pull request #11792
Opened 2022-06-29 06:46 UTC by Vyom-Yadav

#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11776

### Reports with hardcoded mutation (clean):

- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2c344d5_2022110827/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2c344d5_2022041934/reports/diff/index.html

`validateOnlyOverlapping = false` report was not generated with OpenJDK (Out of memory in GitHub actions), though it is very unlikely that it will show any difference, still, if it is required, ping me, and I will generate it locally.

### This mutation falls in the category:

- Safely (no regressions) remove code to be covered

### Rationale:

The condition `definitionToken.getType() == TokenTypes.STATIC_INIT` is same as the condition 
`codeBlockDefinition.getType() == TokenTypes.STATIC_INIT`. A variable declared in static block scope, will always have an enclosing `CLASS_FRAME`.

In the current logic, we skip all frames of type `BLOCK_FRAME`, and `FOR_FRAME` to reach the `CLASS_FRAME`, if we can't reach `CLASS_FRAME` (maybe `METHOD_FRAME` is in between), then we can be assured that there is no static block present.

So if there is a static block, we will surely go into the branch
`if (variableDeclarationFrame.getType() == FrameType.CLASS_FRAME)` in which we check for the condition-
```java
staticContext = codeBlockDefinition.getType() == TokenTypes.STATIC_INIT
    || modifiers.findFirstToken(TokenTypes.LITERAL_STATIC) != null;
```
Hence the line can be safely removed, in theory, we would take a hit in TC, as we would make another traversal in `getCodeBlockDefinitionToken(..)` but in reality, there will be no difference, in real case use scenario, 2-3 more iterations.

2022-06-29 18:49 UTC, pbludov approved these changes

2022-06-30 12:36 UTC, nick-mancuso requested changes
Please generate check regression reports for this PR.

2022-07-01 04:34 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 06:54 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 10:58 UTC, nick-mancuso approved these changes

2022-07-01 10:59 UTC, merged