Issue #11720: Kill surviving mutation in RequireThisCheck related to getting block-definition for the code
checkstyle/checkstyle pull request #11798
Opened 2022-06-30 02:14 UTC by Vyom-Yadav

#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11787

### Reports with hardcoded mutation (clean):

- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dd535b3_2022201547/reports/diff/index.html

### This mutation falls in the category:

- Safely (no regressions) remove code to be covered

### Rationale:

This method is only used at: https://github.com/checkstyle/checkstyle/blob/c8c2d8c7edaa05ce457b5babd6be27daff299528/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L870-L876

Where we check `codeBlockDefinition` for having a `static` modifier that can't be used with constructors. The rationale for adding this at that time could be to save a few iterations. In a real case scenario, it shouldn't be a problem.

2022-06-30 12:43 UTC, nick-mancuso commented
@Vyom-Yadav please find some subset of projects to generate validateOnlyOverlappingFalse report on

2022-07-01 04:35 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 06:56 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 11:26 UTC, nick-mancuso requested changes
Differences in report were not false positives, [this one](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022072739/reports/diff/spoon/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/spoon/src/test/java/spoon/test/targeted/testclasses/Tapas.java.html#L45) will reassign value to method parameter without `this`, and [this one](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022072739/reports/diff/spoon/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/spoon/src/test/java/spoon/test/targeted/testclasses/Tapas.java.html#L56) will not compile without `this`.

2022-07-01 12:35 UTC, Vyom-Yadav commented
> Differences in report were not false positives, [this one](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022072739/reports/diff/spoon/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/spoon/src/test/java/spoon/test/targeted/testclasses/Tapas.java.html#L45) will reassign value to method parameter without `this`, and [this one](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022072739/reports/diff/spoon/xref/home/runner/work/checkstyle/checkstyle/contribution/checkstyle-tester/repositories/spoon/src/test/java/spoon/test/targeted/testclasses/Tapas.java.html#L56) will not compile without `this`. 
> 
> Looks like we have found some test cases :) Please update PR.

Yes, that is correct, but in both the cases, `this` keyword is already there, so isn't that violation a false positive? 🤔

2022-07-01 12:45 UTC, nick-mancuso commented
> Yes, that is correct, but in both the cases, `this` keyword is already there, so isn't that violation a false positive? 🤔

Yes, got confused for a moment, thanks for explanation :)

2022-07-02 14:52 UTC, nick-mancuso requested changes
@Vyom-Yadav please add test cases from report.

2022-07-03 12:12 UTC, nick-mancuso approved these changes

2022-07-03 13:38 UTC, baratali approved these changes
looks good.
@Vyom-Yadav , please rebase on master branch.

2022-07-03 18:58 UTC, merged