Issue #11720: Kill surviving mutation in RequireThisCheck in isInsideConstructorFrame
checkstyle/checkstyle pull request #11800
Opened 2022-06-30 08:16 UTC by Vyom-Yadav

#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11780

### Reports with hardcoded mutation (clean):

- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4d8bbaa_2022114649/reports/diff/index.html
- validateOnlyOverlappingFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4d8bbaa_2022152354/reports/diff/index.html

### This mutation falls in the category:

- Safely (no regressions) remove code to be covered

### Rationale:

The condition is redundant, the only case in which the result might not be what is expected is when the frame is `FrameType.CTOR_FRAME` in which the earlier method returned `false` but the current method will result `true`. Shouldn't be a problem, fields with `FrameType.CTOR_FRAME` are ctor parameters and variable declarations are not checked, only usages are checked-
https://github.com/checkstyle/checkstyle/blob/c8c2d8c7edaa05ce457b5babd6be27daff299528/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L503-L506

2022-06-30 12:48 UTC, nick-mancuso requested changes
Please generate check regression reports for this PR.

2022-07-01 04:37 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 06:47 UTC, strkkk approved these changes

2022-07-01 07:05 UTC, Vyom-Yadav commented
Github, generate report

2022-07-01 11:02 UTC, nick-mancuso commented
@Vyom-Yadav please resolve conflicts

2022-07-02 14:59 UTC, nick-mancuso commented
Github, generate report

2022-07-02 16:09 UTC, nick-mancuso commented
Github, generate report

2022-07-03 12:14 UTC, nick-mancuso commented
Github, generate report

2022-07-03 12:15 UTC, nick-mancuso commented
@Vyom-Yadav please resolve conflicts

2022-07-03 14:14 UTC, nick-mancuso approved these changes

2022-07-03 14:14 UTC, merged