infra: allows for maven cache to not be restored, but continue execution
checkstyle/checkstyle pull request #11877
Opened 2022-07-10 01:26 UTC by nick-mancuso

"Fixes" (really allows us to bypass) failure noted at: https://cloud.drone.io/checkstyle/checkstyle/11222/4/2

I am guessing that this is the same issue mentioned by @romani regarding dropbox last week in discord:

```
Dropbox.
Hi Roman,
This email is an automated notification from Dropbox letting you know that your Public links have been temporarily suspended for generating excessive traffic.

```
The file we are actually downloading now:

```
➜  checkstyle git:(fix-infra-2) ✗ curl -o .ci-temp/cache.tar -SsL \
    https://www.dropbox.com/s/"sh1g8o4h16p4n""x6"/cache.tar\?dl\=0

➜  checkstyle git:(fix-infra-2) cat .ci-temp/cache.tar 
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dropbox - 404</title>
<link href="https://cfl.dropboxstatic.com/static/css/error.css" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" href="https://cfl.dropboxstatic.com/static/images/favicon.ico"/>
</head>
<body>
<div class="figure">
<img src="https://assets.dropbox.com/www/en-us/illustrations/spot/look-magnifying-glass.svg" alt="Error: 404"/>
</div>
<div id="errorbox">
<div class="not-found">
                <h1>Error (404)</h1>
                We can't find the page you're looking for.
                <div class="not-found--links">
                    Here are a few links that may be helpful:
                    <ul>
                        <li><a href="https://www.dropbox.com/home?_tk=fof">Home</a></li>
                        <li><a href="https://www.dropbox.com/help?_tk=fof">Help center</a></li>
                        <li><a href="https://www.dropbox.com/login?_tk=fof">Sign in</a></li>
                        <li><a href="https://www.dropbox.com/register?_tk=fof">Get a free account</a></li>
                        <li><a href="https://www.dropbox.com/plus?_tk=fof">Dropbox Plus</a></li>
                        <li><a href="https://www.dropbox.com/business?_tk=fof">Dropbox Business</a></li>
                    </ul>
                </div>
            </div>
</div>

</body>
</html>

```

2022-07-10 02:39 UTC, romani commented
This is not required to merge, as side effect that we have in drone it not blocking execution.

But it shows very strange situation that I can not understand, there is no m2 cache installation but there is no download of artifacts.

If we get understanding of this paradox, I would be ok to remove restoration of cache at all.

2022-07-10 18:35 UTC, nick-mancuso commented
Link to build: https://cloud.drone.io/checkstyle/checkstyle/11289/1

2022-07-12 04:09 UTC, nick-mancuso commented
@romani see https://cloud.drone.io/checkstyle/checkstyle/11289/1/2, we do not have cache, but download of all dependencies is very fast.

2022-07-13 03:24 UTC, romani requested changes
Items

2022-07-13 03:24 UTC, romani commented on .ci/validation.sh
> +  mvn -e --no-transfer-progress clean verify -DskipTests -DskipITs \
Keep it, it is good option

2022-07-13 03:25 UTC, nick-mancuso commented on .ci/validation.sh
> +  mvn -e --no-transfer-progress clean verify -DskipTests -DskipITs \
It is a duplicate

2022-07-13 04:09 UTC, nick-mancuso commented
Link to drone execution in this PR (no cache):

![image](https://user-images.githubusercontent.com/31252532/178648778-5fe096c2-ed79-47d5-8589-373ee15afe2f.png)

Link to drone execution from another PR:

2022-07-13 04:20 UTC, romani commented
Please put in commit reference to this PR and merge PR immediately

2022-07-13 04:20 UTC, romani approved these changes
Ok to merge

2022-07-13 04:23 UTC, merged

2022-07-13 04:24 UTC, nick-mancuso commented
> Please put in commit reference to this PR and merge PR immediately

@romani done