Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck related to usage distance
checkstyle/checkstyle pull request #11962
Opened 2022-07-22 15:29 UTC by Vyom-Yadav

#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11937

Check documentation: https://checkstyle.sourceforge.io/config_coding.html#VariableDeclarationUsageDistance

### Diff Reports:

- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/690b2d8_2022145912/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/690b2d8_2022100320/reports/diff/index.html

### Rationale
If variable wasn't used after its declaration then `variableUsageAst` will be null, this method returns 
`Entry<DetailAST, Integer>` , `new SimpleEntry<>(variableUsageAst, dist)` this method
(`calculateDistanceInSingleScope`) is only called at-
https://github.com/checkstyle/checkstyle/blob/32cfeee3a3b85eb26015dc515211c6db97a470f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L407-L425

Whatever the value of distance was, no violation will be logged because of the condition 
https://github.com/checkstyle/checkstyle/blob/32cfeee3a3b85eb26015dc515211c6db97a470f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L417-L418

When `variableUsageAst` is `null`, the method `isInitializationSequence` returns `true` hence making this condition `false` https://github.com/checkstyle/checkstyle/blob/32cfeee3a3b85eb26015dc515211c6db97a470f6/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L459-L468
No violation will be logged, so it is safe to remove this method.

---

### Generating reports again:

Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/a06fa3c8f525c4466a67c1ee057d4ed843db2301/my_checks.xml
Report label: validateBetweenScopesTrue

2022-07-22 15:30 UTC, Vyom-Yadav commented
Github, generate report

2022-07-23 17:13 UTC, Vyom-Yadav commented
Github, generate report

2022-07-26 10:54 UTC, baratali requested changes
It might be confusing why `calculateDistanceInSingleScope()` returns non-zero distance when varaible usage is not found. Can you pease add more info to javadoc? Something like this:
```
     * @return entry which contains expression with variable usage and distance.
     *         If variable usage is not found then the expression node is null,
     *         although the distance can be greater than zero.
```

2022-07-26 12:14 UTC, Vyom-Yadav commented
> 

Done.

2022-07-27 08:31 UTC, baratali approved these changes

2022-07-27 08:49 UTC, baratali commented
@Vyom-Yadav, the same method was changed in https://github.com/checkstyle/checkstyle/pull/11963
Can you please rebase on master and build a report again for `validateBetweenScopes=false` to make sure nothing changes?

2022-07-27 08:59 UTC, Vyom-Yadav commented
Github, generate report

2022-07-27 12:26 UTC, nick-mancuso commented
@Vyom-Yadav please resolve conflicts

2022-07-27 12:44 UTC, Vyom-Yadav commented
> @Vyom-Yadav please resolve conflicts

Done.

2022-07-28 15:29 UTC, nick-mancuso approved these changes

2022-07-28 15:29 UTC, merged