Issue #11575: fix false negative about the rule RightCurly
checkstyle/checkstyle pull request #12054
Opened 2022-08-12 14:09 UTC by ZuevKirill95

2022-08-25 04:06 UTC, nick-mancuso requested changes
Items:

2022-08-25 04:06 UTC, nick-mancuso commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
> +            TokenTypes.OBJBLOCK,
It would be better to not extend list of tokens in the scope of this issue.

2022-08-25 04:06 UTC, nick-mancuso commented on src/main/resources/google_checks.xml
> +    <module name="RightCurly">
Please do not extend google config in the scope of this issue.

2022-08-25 04:06 UTC, nick-mancuso commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestObjectBlockLineBreakAfter.java
> +    Object o3 = new Object() {}; // ok
Please add test case with empty statement following anonymous class.

2022-09-22 13:07 UTC, nrmancuso commented
@ZuevKirill95 ping

2022-11-23 05:46 UTC, nrmancuso commented
We have lost contact with author, anyone is welcome to reuse code to finish issue.

2022-11-23 05:46 UTC, closed without merging