Issue #12079: Github action Release perform
checkstyle/checkstyle pull request #12089
Opened 2022-08-22 18:42 UTC by Rahulkhinchi03

Fixes #12079

2022-08-25 19:28 UTC, Rahulkhinchi03 commented
Need some time to test it. Facing some errors, resolving them and will get back to the generation soon

2022-08-27 18:38 UTC, romani requested changes
show me your maven project that you use to test this action.

items:

2022-08-27 18:38 UTC, romani commented on .ci/maven-perform.sh
> +git fetch --all --tags
why clone in action is not enough ?

2022-08-27 18:38 UTC, romani commented on .ci/maven-perform.sh
> +  echo "latest version is not set"
remove latest

2022-08-27 18:41 UTC, Rahulkhinchi03 commented
This is my project: https://github.com/Rahulkhinchi03/checkstyle-test

2022-08-27 18:54 UTC, romani commented
Remove this file https://github.com/Rahulkhinchi03/checkstyle-test/blob/main/release.properties it should not be in git

2022-08-31 15:18 UTC, Rahulkhinchi03 commented on .ci/maven-perform.sh
> +  echo "latest version is not set"
Changes Done

2022-08-31 15:18 UTC, Rahulkhinchi03 commented on .ci/maven-perform.sh
> +git fetch --all --tags
Changes Done

2022-09-04 03:47 UTC, romani requested changes
Items

2022-09-04 03:47 UTC, romani commented on .github/workflows/maven_perform.yml
> +        with:
Checkout is not enough, no tags

2022-09-04 03:47 UTC, romani commented on .ci/maven-perform.sh
> +mvn -e --no-transfer-progress release:perform -Darguments="$SKIP_CHECKSTYLE"
Please prove by testing that this command can run successfully without release:prepare on same host/filesystem.

2022-09-04 09:14 UTC, closed without merging