minor: add helper method hasModifiers and hasNotModifiers
checkstyle/checkstyle pull request #12088
Opened 2022-08-22 15:58 UTC by ZuevKirill95

added utility methods - hasModifiers and hasNotModifiers

2022-08-22 18:56 UTC, rnveach reviewed
Where is this change coming from? What prompted this to be started?

2022-08-22 18:56 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> +    public static boolean hasModifiers(DetailAST ast, int... modifiersTypes) {
Pointing to https://github.com/checkstyle/checkstyle/issues/11527 over past concerns with performance with these type of methods.

2022-08-22 18:56 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> +    public static boolean hasNotModifiers(DetailAST ast, int... modifiersTypes) {
Same.

2022-08-24 15:48 UTC, ZuevKirill95 commented
> Where is this change coming from? What prompted this to be started?

In one of the tasks I needed such a method, but I didn't find it in the util classes

And I decided to suggest such a method in the main code. If it is approved, I am ready to continue working on this PR.

2022-08-29 02:19 UTC, nick-mancuso requested changes
@ZuevKirill95 this change affects 30 checks, this is not a `minor` commit. To move forward with this change, you will need to create an issue for discussion. If issue is approved, we would need to run check regression reports for all affected checks, and ensure that there is no regressions/ changes in check behavior. 

Please create an issue, it would probably be better to close this PR and create a new PR if issue gets approved.

2022-08-29 02:19 UTC, nick-mancuso commented on src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
> +        final DetailAstImpl astFinal = new DetailAstImpl();
We cover new code by real test input only, we are not extending our tech debt by allowing coverage by synthetic tests.

2022-08-30 16:16 UTC, ZuevKirill95 commented
> Please create an issue, it would probably be better to close this PR and create a new PR if issue gets approved.

Okay, I'll do it. Thanks

2022-08-30 16:17 UTC, closed without merging