Issue #3955: corrected tokens so all are required
checkstyle/checkstyle pull request #12108
Opened 2022-08-27 04:49 UTC by rnveach

Issue #3955

2022-08-27 19:22 UTC, romani commented
it is breaking compatibility .... will nee review from all.

2022-08-28 17:28 UTC, pbludov approved these changes

2022-08-29 02:01 UTC, nick-mancuso commented
Github, generate site

2022-08-30 03:31 UTC, nick-mancuso approved these changes
This is a big improvement to this check; documentation and usage is clear now.

2022-09-02 07:42 UTC, strkkk approved these changes

2022-09-20 22:25 UTC, rnveach commented
@romani ping

2022-09-22 12:57 UTC, romani commented
Github, generate web site

2022-09-22 13:04 UTC, romani requested changes
Do we have test that shows that user can define FQN of inner class to be validated ? 

items:

2022-09-22 13:28 UTC, rnveach commented
> Do we have test that shows that user can define FQN of inner class to be validated ?

InputIllegalInstantiationSemantic2 has:
````
classes = java.lang.Boolean,com.puppycrawl.tools.checkstyle.checks.coding.illegalinstantiation.\
          InputModifier,java.io.File,java.awt.Color
````

Please note `InputModifier`.

2022-09-22 14:48 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
> + * and {@code java.lang.Integer}:
Done.

2022-09-22 15:06 UTC, romani commented
Github, generate web site

2022-09-22 15:19 UTC, romani approved these changes
Ok to merge

2022-09-22 15:21 UTC, merged