Issue #8016: Add allowMissingBuilderJavadoc
checkstyle/checkstyle pull request #12148
Opened 2022-09-01 00:51 UTC by nerdydrew

Issue: #8016

That issue does not have the "approved" label yet, but I wanted to propose a solution in a backwards-compatible way. This adds an `allowMissingBuilderJavadoc` boolean to `MissingJavadocMethod`. If set to `true`, methods using the builder pattern are allowed to not have Javadoc, parallel to `allowMissingPropertyJavadoc`. Three different formats are below:

```java
public class Builder {
    private String field;

    public Builder setField(String field) {
        this.field = field;
        return this;
    }
    public Builder withField(String field) {
        this.field = field;
        return this;
    }
    public Builder field(String field) {
        this.field = field;
        return this;
    }
}
```

Diff Regression config: {{URI to my_checks.xml}}

Diff Regression patch config: {{URI to patch_config.xml}}

2022-09-01 00:52 UTC, nerdydrew commented
GitHub, generate report

2022-09-01 02:50 UTC, nerdydrew commented
GitHub, generate report

2022-09-01 11:34 UTC, nerdydrew commented
GitHub, generate report

2022-09-01 22:17 UTC, nerdydrew commented
GitHub, generate report

2022-09-01 23:29 UTC, nerdydrew commented
Okay, I've addressed all the issues from the automatic workflows. This is now in a reviewable state.

2022-09-02 11:14 UTC, nrmancuso requested changes
Not only does #8016  not have approved label, but the issue description is lacking. Please create a new issue for discussion of your idea and we will close the old one. I advise you to not continue work on this PR until new issue is approved.

2022-09-22 13:12 UTC, nrmancuso commented
@nerdydrew can we close this PR now that we have moved discussion to https://github.com/checkstyle/checkstyle/issues/12157 and have a possible solution?

2022-09-22 23:03 UTC, nerdydrew commented
Sure. I haven’t found time to explore xpath too deeply yet, but I’ll close this off.

2022-09-22 23:03 UTC, closed without merging