Pull #12223: Correct the hashCode method in checker-framework.groovy
checkstyle/checkstyle pull request #12223
Opened 2022-09-22 07:05 UTC by Vyom-Yadav

Contents of this PR:

- The `hashCode()` method was not implemented correctly, for two objects `equals()` could return true but the objects had different hashes.
- Now for every error, the hash code is generated from `messageWithoutNumber` and `messageWithoutNumber`.

2022-09-22 12:24 UTC, nrmancuso requested changes
Item:

2022-09-22 12:24 UTC, nrmancuso commented on .ci/checker-framework.groovy
> +    final List<String> details
Why did we do list instead of multiline string?

2022-09-22 12:34 UTC, romani commented
I recommend to not mess with hashcode/equals and make special method `compareTo` or somthing like this and use it instead.
We do not need high speed in this script, we need ease of maintenance/change.

2022-09-22 12:38 UTC, nrmancuso commented
>I recommend to not mess with hashcode/equals (human is always error prone on this contract) and make special method compareTo or somthing like this and use it instead.

As we use Sets/ TreeSets/ Lists, we must make sure that equals and hashcode are overridden to account for changing messages.

2022-09-22 23:00 UTC, romani commented
>As we use Sets/ TreeSets/ Lists, we must make sure that equals and hashcode are overridden

Nobody has to override such methods if objects are immutable or you do not mutate such objects while there in collection.

We just need single place in our code that instead of relying on collection to do search by collection API, do it by our search function that use very specific way of comparison.

2022-09-22 23:43 UTC, rnveach commented
> As we use Sets/ TreeSets/ Lists, we must make sure that equals and hashcode are overridden
Nobody has to override such methods if objects are immutable or you do not mutate such objects while there in collection.

Immutability has no play here. Immutable just means the object will not change after creation. I can pass the same values to a constructor twice and have 2 different instances of the "same" inner values. The issue here is determining if 2 different instances are the same. We have to compare the before and after lists, and each one is given their own unique instances. Our class' are not singleton and that is the only way we could get around not overriding equals, is if they amounted to the same instance.

Pitest suppression does the same thing discussed here. The only difference is it doesn't override the hashCode method.
https://github.com/checkstyle/checkstyle/blob/master/.ci/pitest-survival-check-xml.groovy#L316-L317
https://github.com/checkstyle/checkstyle/blob/master/.ci/pitest-survival-check-xml.groovy#L360


> We just need single place in our code that instead of relying on collection to do search by collection API, do it by our search function that use very specific way of comparison.

So you are saying we need to create our version of `contains`/`compareTo`/`equals` which in the end amounts to the same type of code as a  `contains`/`compareTo`/`equals` ? This is a POH tato PAH tato thing, doing our own search is the same as implementing our own `compareTo`/`equals` and using Java's already built utilities. Regardless we have to define when 2 instances are equal to know if they are the same or not.

2022-09-23 00:06 UTC, romani commented
Instances of two violations are not same, but we can consider them as same if that is unstable and we want it. But they are not same and equals should give false.

We can merge this PR and in next PR, make it conseptually more robust.

2022-09-23 03:12 UTC, nrmancuso commented
I think we should rethink on idea proposed in discord: treat all messages and details the same, i.e. replacement of problematic text by some obvious generic name. Example: `temp-var-123` becomes `'temp-var'`, `capture#123` becomes `'capture'`, etc. This way we only have custom string manipulation method, and once we create suppression object, they are all treated the same.

2022-09-23 03:36 UTC, romani commented
I am ok with this

2022-09-24 18:47 UTC, Vyom-Yadav commented
> I think we should rethink on idea proposed in discord: treat all messages and details the same, i.e. replacement of problematic text by some obvious generic name. Example: `temp-var-123` becomes `'temp-var'`, `capture#123` becomes `'capture'`, etc. This way we only have custom string manipulation method, and once we create suppression object, they are all treated the same.

That would mean replacing all numbers in details and messages with an empty string. Also, it would be `capture#` and `temp-var-` as creating a regex to remove `#` and `-` is not very reliable as we can have more cases.

2022-09-24 19:01 UTC, nrmancuso commented
>we can have more cases.

I think it is better to allow failure for new cases to make us aware of all possible variations and enumerate them in groovy file.

2022-09-24 19:22 UTC, romani commented
>That would mean replacing all numbers in details and messages with an empty string.

No just numbers are that has very distinct prefix. Both such numbers are not from our code, and some internal representation of Checker tool.
We can ignore them for now. 
In future as we come to state that we find way to resolve most violations and will plan to resolve all other, we can reconsider our decision update of messages.
We need some stable time to consume this tool and experience it.

2022-10-02 03:21 UTC, rnveach commented
@romani @Vyom-Yadav @nrmancuso My recommendation is to drop this PR and proceed with recommendation at https://github.com/checkstyle/checkstyle/issues/12243 .

We should also need to worry less about hash code, and just implement a compare to that will control ordering of violations.

2022-10-02 05:50 UTC, Vyom-Yadav commented
> > That would mean replacing all numbers in details and messages with an empty string.
> 
> No just numbers are that has very distinct prefix. Both such numbers are not from our code, and some internal representation of Checker tool. We can ignore them for now. In future as we come to state that we find way to resolve most violations and will plan to resolve all other, we can reconsider our decision update of messages. We need some stable time to consume this tool and experience it.

Agreed, closed in favour of #12244

2022-10-02 05:50 UTC, closed without merging