Issue #12267: Resolve Pitest suppression for SeperatorWrapCheck
checkstyle/checkstyle pull request #12272
Opened 2022-10-07 17:07 UTC by Kevin222004

Issue #12267: Resolve Pitest suppression for SeperatorWrapCheck

2022-10-07 17:07 UTC, Kevin222004 commented
Killed Mutation report
https://kevin222004.github.io/SeperatorWrap/com.puppycrawl.tools.checkstyle.checks.whitespace/SeparatorWrapCheck.java.html

2022-10-07 17:32 UTC, rnveach approved these changes
Ok to merge when CI passes and no conflicts.

2022-10-08 11:47 UTC, romani requested changes
Items

2022-10-08 11:47 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapSetOptionTrim.java
> +        /* violation */ Arrays.sort(stringArray, String::
As you create new file.
Please make it with indentation of +2, not a +4.
Remove this leading comment.
Move trailing comment to same line where violation

2022-10-08 11:54 UTC, rnveach approved these changes

2022-10-08 19:21 UTC, romani approved these changes
Ok to merge

2022-10-08 19:21 UTC, merged