Issue #12443: Fix null pointer exception on config value with trailin…
checkstyle/checkstyle pull request #12444
Opened 2022-11-23 04:52 UTC by nrmancuso

closes #12443

2022-11-23 14:01 UTC, romani approved these changes
Ok to merge

2022-11-23 14:05 UTC, romani commented
Should be merged before Sunday, to release this fix sooner

2022-11-23 14:26 UTC, rnveach requested changes
https://github.com/checkstyle/checkstyle/issues/12443#issuecomment-1324375539
I am seeing 3 trims removed, but only 2 fixes here.

2022-11-23 14:35 UTC, nrmancuso commented
Third trim does not need to be replaced, trim is called on argument in method.

https://github.com/checkstyle/checkstyle/blob/276263b6493b2b47709407f2315524586619c0a1/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java#L65-L67

2022-11-23 14:36 UTC, rnveach commented
> Third trim does not need to be replaced, trim is called on argument in method.

Do we have a similar test to show it is not needed?

2022-11-23 14:48 UTC, nrmancuso commented
This is where the other trim was located: https://github.com/checkstyle/checkstyle/commit/308001394030b0ba52921dd8f1b0bef22c90ea83#r90853229

Which calls https://github.com/checkstyle/checkstyle/blob/276263b6493b2b47709407f2315524586619c0a1/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java#L65-L67

I can add another tab in config like this: `public\t,\t`

2022-11-24 00:06 UTC, nrmancuso commented
@rnveach test case is added

2022-11-24 09:16 UTC, Vyom-Yadav approved these changes
One minor, rest LGTM :)

2022-11-24 09:16 UTC, Vyom-Yadav commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeWhitespaceInConfig.java
> +ignoredMethodNames = foo1
Lets keep this is default too:
```
ignoredMethodNames = (default)getEnvironment, getInitialContext
```

2022-11-24 14:11 UTC, rnveach commented
> I can add another tab in config like this: `public\t,\t`, this will cause an unnecessary suppression since this is the test case at https://github.com/checkstyle/checkstyle/pull/12340

There is no test case like this in the other PR.

2022-11-24 14:29 UTC, nrmancuso commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeWhitespaceInConfig.java
> +ignoredMethodNames = foo1
Done

2022-11-24 14:52 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeWhitespaceInConfig.java
> +ignoredMethodNames = foo1
confirmed.

2022-11-24 15:01 UTC, nrmancuso commented
Linking discussion here: https://github.com/checkstyle/checkstyle/pull/12340#discussion_r1031557625

2022-11-24 15:22 UTC, Vyom-Yadav commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeWhitespaceInConfig.java
> +ignoredMethodNames = foo1
Resolved

2022-11-26 02:42 UTC, merged