Issue #12641: adds tests for design profile
checkstyle/checkstyle pull request #12642
Opened 2023-01-15 01:10 UTC by rnveach

Issue #12641

No regression needed.

2023-01-15 06:18 UTC, nrmancuso requested changes
Item:

2023-01-15 06:18 UTC, nrmancuso commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount4.java
> +    void method1() throws Exception // violation
Please add violation messages

2023-01-15 14:26 UTC, romani approved these changes
ok to merge as above is addressed

2023-01-15 20:33 UTC, rnveach commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount4.java
> +    void method1() throws Exception // violation
Done.

2023-01-17 04:32 UTC, nrmancuso approved these changes

2023-01-17 04:33 UTC, nrmancuso commented
Failure to download dependency in semaphore is not related to this PR. https://checkstyle.semaphoreci.com/jobs/accbe8ca-f87f-41dc-a35c-091b59472f0d

2023-01-17 04:33 UTC, merged