minor: test 009cffaa
checkstyle/checkstyle pull request #12670
Opened 2023-01-21 03:36 UTC by rnveach

# PLEASE READ before removing

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

2023-01-24 13:59 UTC, romani requested changes
items:

2023-01-24 13:59 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
>       * until #11589
should be removed.

2023-01-24 13:59 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
> +     * @noinspectionreason ResultOfMethodCallIgnored - Setup for mockito for which method to mock.
can we be specific , something like `toByteArray only mocked to throw exception`

2023-01-24 15:37 UTC, rnveach commented on src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
>       * until #11589
Done.

2023-01-25 02:17 UTC, romani approved these changes

2023-01-25 02:17 UTC, merged