Issue #7604: Update doc NonEmptyAtclauseDescriptionCheck
checkstyle/checkstyle pull request #12708
Opened 2023-02-02 18:34 UTC by MauryanKansara

Issue #7604 

![Screenshot (12)](https://user-images.githubusercontent.com/86093112/216411060-33978dab-3fd9-49f1-879d-61d8feb5a5fe.png)

`$ cat config1.xml`
```cmd
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="NonEmptyAtclauseDescription"></module>
  </module>
</module>

```
`$ cat Test1.java`
```java
class Test1
{
  /**
  * @param a Multiplying a with 10.
  * @param ans
  * @deprecated
  * @throws Exception
  */
  public int method(int a, int ans) throws Exception
  {
    ans = a * 10;
    return ans;
  }
}
```

`$ java -jar checkstyle-10.6.0-all.jar -c config1.xml Test1.java`
```cmd
Starting audit...
[ERROR] C:\CheckStyle\issues\Test1.java:5: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
[ERROR] C:\CheckStyle\issues\Test1.java:6: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
[ERROR] C:\CheckStyle\issues\Test1.java:7: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
Audit done.
Checkstyle ends with 3 errors.
```
![Screenshot (13)](https://user-images.githubusercontent.com/86093112/216418162-f74910b4-ed0c-48df-a345-13bb2cb2331d.png)

`$ cat config2.xml`
```cmd
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="NonEmptyAtclauseDescription">
        <property name="javadocTokens" value="PARAM_LITERAL,RETURN_LITERAL"/>
    </module>
  </module>
</module>
```
`$ cat Test2.java`
```java
class Test
{
  // OK for parameter "a" because it's description is provided.
  // Violation for parameter "ans" because it's description is not provided.
  // "deprecated" and "throws" tags are ignored.
  /**
  * @param a Multiplying a with 10.
  * @param ans
  * @deprecated
  * @throws Exception
  */
  public int method(int a, int ans) throws Exception
  {
    ans = a * 10;
    return ans;
  }
}
```
`$ java -jar checkstyle-10.6.0-all.jar -c config2.xml Test2.java`
```cmd
Starting audit...
[ERROR] C:\CheckStyle\issues\Test2.java:8: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
Audit done.
Checkstyle ends with 1 errors.
```

![Screenshot (14)](https://user-images.githubusercontent.com/86093112/216417689-f80540cb-c0e9-4804-bff2-eeb5b6c3e7b7.png)

2023-02-02 18:41 UTC, MauryanKansara commented
@romani can you please review my PR?

2023-02-10 04:46 UTC, nrmancuso commented
Github, generate site

2023-02-11 14:31 UTC, romani requested changes
items:

2023-02-11 14:37 UTC, romani commented on config/archunit-store/slices_should_be_free_of_cycles_suppressions
> -    - Method <com.puppycrawl.tools.checkstyle.checks.javadoc.NonEmptyAtclauseDescriptionCheck.visitJavadocToken(com.puppycrawl.tools.checkstyle.api.DetailNode)> calls method <com.puppycrawl.tools.che
if diff is in line number update, due to extra javadoc, it is ok to keep

2023-02-11 14:44 UTC, romani commented
please make example like:
```
<module name="NonEmptyAtclauseDescription"/>

class Test
{
  // '@param a' - OK
  // '@param ans' - OK
  // '@return' - OK
  // '@deprecated' - OK
  // '@throws Exception' - OK
  /**
  * @param a Multiplying a with 10.
  * @param ans our accumulation parameter
  * @deprecated As of release 1.3
  * @return multiplied value
  * @throws Exception if something is bad
  */
  public int method(int a, int ans) throws Exception
  {
    ans = a * 10;
    return ans;
  }
}

<module name="NonEmptyAtclauseDescription"/>

class Test
{
  // '@param a' - OK for parameter "a" because it's description is provided.
  // '@param ans' - violation
  // '@return' - violation
  // '@deprecated' - violation
  // '@throws Exception' - violation
  /**
  * @param a Multiplying a with 10.
  * @param ans
  * @deprecated
  * @return
  * @throws Exception
  */
  public int method(int a, int ans) throws Exception
  {
    ans = a * 10;
    return ans;
  }
}

<module name="NonEmptyAtclauseDescription">
  <property name="javadocTokens" value="PARAM_LITERAL,RETURN_LITERAL"/>
</module>
        
class Test
{
  // '@param a' - OK because it's description is provided.
  // '@param ans' - violation
  // '@return' - violation
  // '@deprecated' - ok because not a target of validation
  // '@throws Exception' - ok because not a target of validation
  /**
  * @param a Multiplying a with 10.
  * @param ans
  * @deprecated
  * @return
  * @throws Exception
  */
  public int method(int a, int ans) throws Exception
  {
    ans = a * 10;
    return ans;
  }
}
```

2023-02-28 14:15 UTC, romani commented
@MauryanKansara , please finish this PR.
if you have no time now, we can let others to finish it.

2023-02-28 18:08 UTC, MauryanKansara commented
> @MauryanKansara , please finish this PR. if you have no time now, we can let others to finish it.

I will finish the pending work within a day. Really sorry for the delay.

2023-03-12 22:33 UTC, romani commented
we lost contact with author.

2023-03-12 22:33 UTC, closed without merging