Issue #11637: Resolve shellcheck SC2026
checkstyle/checkstyle pull request #12724
Opened 2023-02-05 13:51 UTC by shubh220922

Related to #11637 

Checking CI.

2023-02-05 23:48 UTC, shubh220922 commented
Problem CI showed:

https://github.com/checkstyle/checkstyle/actions/runs/4096900031/jobs/7064875554#step:4:6

2023-02-06 05:40 UTC, rnveach commented
Are you familiar with bash to read the code and try to understand what it is doing?
Do you know what the following lines mean? https://github.com/checkstyle/checkstyle/blob/master/.ci/validation.sh#L20-L22

2023-02-10 04:41 UTC, nrmancuso requested changes
Item:

2023-02-10 04:41 UTC, nrmancuso commented on .ci/validation.sh
> +    -t -v '//pom:profile[./pom:id[contains(text(),'"'pitest'"')]]//pom:targetClasses/pom:param'))
```suggestion
    -t -v "//pom:profile[./pom:id[contains(text(),'pitest')]]//pom:targetClasses/pom:param"))
```

Please send temporary commit to show that it works by removing some pitest target class.

2023-02-14 06:37 UTC, shubh220922 commented
> Are you familiar with bash to read the code and try to understand what it is doing? Do you know what the following lines mean? https://github.com/checkstyle/checkstyle/blob/master/.ci/validation.sh#L20-L22

(I am writing this reply after doing a complete course on bash (link: https://www.youtube.com/watch?v=e7BufAVwDiM))

I totally didn't realize it was switch case statement there. I am working on it now.

2023-02-16 14:24 UTC, nrmancuso commented on .ci/validation.sh
> +    -t -v '//pom:profile[./pom:id[contains(text(),'"'pitest'"')]]//pom:targetClasses/pom:param'))
@shubh220922 ping

2023-02-18 10:41 UTC, closed without merging

2023-02-18 10:41 UTC, shubh220922 commented
Progress of this PR is continued in .