Issue #7593: Fix typos in docs of TranslationCheck
checkstyle/checkstyle pull request #12918
Opened 2023-03-27 00:32 UTC by Mariam-maghraby

# PLEASE READ before removing

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove the whole message and type what you need.

2023-03-27 06:55 UTC, rnveach requested changes
Rename your commit to exactly `doc: fixed typos in docs of TranslationCheck`

2023-03-27 06:55 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
> +
Remove this empty line.

2023-03-27 06:55 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
> + * TranslationCheck will rise a violation that the language code is incorrect.
`rise` => `raise`

2023-03-27 06:55 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
> + * The missing {@code ok} key in the default resource file and the missing
This is not the start of the statement. We detailing a list with the comma and it is one long sentence. This should be reverted to what it was before.

2023-03-27 14:42 UTC, Mariam-maghraby commented
`Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project checkstyle: There are test failures.` This error pops when I use ` mvn clean verify`

2023-03-28 08:10 UTC, Mariam-maghraby commented
@rnveach I rebase it into 1 commit, can you review it now?

2023-03-28 12:29 UTC, nrmancuso commented
@Mariam-maghraby review all CI failures and fix issues, example: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13815&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2

Content in xdocs and javadoc of check must be synced

2023-03-28 12:37 UTC, Mariam-maghraby commented
@nrmancuso on it, thanks!

2023-03-28 20:50 UTC, Mariam-maghraby commented
This is the error with maven log but I can't resolve it
![image](https://user-images.githubusercontent.com/61349498/228363356-ab7fa51a-a8fd-46c7-96ae-6e360ed19ef2.png)

2023-03-29 01:53 UTC, nrmancuso commented
@Mariam-maghraby actual error is above where you took your screenshot. See https://github.com/checkstyle/checkstyle/pull/12918#issuecomment-1486799626 , xdocs and Javadoc must match. You can rerun the failing test in your IDE to see the actual difference.

2023-04-08 17:27 UTC, Mariam-maghraby commented
@nrmancuso I don't know how to sync the content in xdocs and javadoc. Can you give me a hint?
Also the build in [Link]((https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=13815&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2))  now is no longer found

2023-04-08 18:31 UTC, romani commented
update them manually together

2023-04-08 18:50 UTC, Mariam-maghraby commented
> update them manually together

@rnveach Ok got it, thanks!

2023-04-08 19:46 UTC, Mariam-maghraby commented
The test run smoothly but how can I resolve these errors?
![image](https://user-images.githubusercontent.com/61349498/230739930-1fe8fbca-06cd-4f34-964b-b4d8745480b2.png)

2023-04-11 12:36 UTC, rnveach commented
@Mariam-maghraby The number of commits in this PR should be 1, just yours.
https://github.com/Mariam-maghraby/checkstyle
> This branch is [11 commits ahead](https://github.com/Mariam-maghraby/checkstyle/compare/checkstyle:checkstyle:master...master) of checkstyle:master.

See https://github.com/checkstyle/checkstyle/wiki/PR-rules

2023-04-11 19:06 UTC, Mariam-maghraby commented
@rnveach I did rebase now

2023-04-11 19:17 UTC, Mariam-maghraby commented
what should I do to pass the 2 tests that failed?

2023-04-11 22:09 UTC, Mariam-maghraby commented
Is there a way instead of manually to figure out at which line or paragraph tag that the xdocs anen't synced with the javadocs?

2023-04-11 22:49 UTC, rnveach commented
> Is there a way instead of manually to figure out at which line or paragraph tag that the xdocs anen't synced with the javadocs?

There is not.

CI has checkstyle failures which give line numbers.
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/18172/workflows/ece7a0ce-036c-454c-b1f0-9f0bef295546/jobs/278269
````
[INFO] [checkstyle] Running Checkstyle  on 1499 files
[ERROR] [checkstyle] [ERROR] /root/project/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java:232: Javadoc tag '@since' should be preceded with an empty line. [RequireEmptyLineBeforeBlockTagGroup]
[ERROR] [checkstyle] [ERROR] /root/project/src/xdocs/config_misc.xml:1: File does not end with a newline. [NewlineAtEndOfFile]
[ERROR] [checkstyle] [ERROR] /root/project/src/xdocs/config_misc.xml:2240: Line should not be longer than 100 symbols [lineLengthXml]
[INFO]      [echo] Checkstyle finished (checkstyle-checks.xml) : 11/04/2023 07:06:40 PM
[INFO]      [echo] Checkstyle started (checkstyle-non-main-files-checks.xml): 11/04/2023 07:05:44 PM
[INFO] [checkstyle] Running Checkstyle  on 3559 files
[ERROR] [checkstyle] [ERROR] /root/project/src/xdocs/config_misc.xml:1: File does not end with a newline. [NewlineAtEndOfFile]
[ERROR] [checkstyle] [ERROR] /root/project/src/xdocs/config_misc.xml:2240: Line should not be longer than 100 symbols [lineLength]
````

Also, you need to rebase now as there are conflicts.

2023-04-11 23:08 UTC, Mariam-maghraby commented
![image](https://user-images.githubusercontent.com/61349498/231307521-f8d53b72-7bef-4a44-9417-d2d42bcbac82.png)

2023-04-12 00:43 UTC, rnveach commented
I am sorry, I have not seen that before. If you are using IntelliJ, maybe another member or google can help you. I only use Eclipse.

2023-04-14 05:03 UTC, romani commented
Please backup your changes, close Pr. Remove your fork. And do all from scratch.
https://checkstyle.org/beginning_development.html#Starting_Development

2023-04-14 13:45 UTC, Mariam-maghraby commented
@romani Ok, I will do so thanks!

2023-04-14 13:46 UTC, closed without merging