Issue #12671: Resolve pitest suppression for FinalLocalVariableCheck
checkstyle/checkstyle pull request #13008
Opened 2023-04-19 12:11 UTC by coderdeadpool

Related to #12671 #12341

2023-04-19 12:14 UTC, romani requested changes
items:

2023-04-19 12:14 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
> +        DetailAST parent = ast;
`DetailAST currentAst = ast;`

2023-04-19 12:23 UTC, romani commented
please share regression report

2023-04-19 12:27 UTC, coderdeadpool commented
Github, generate repot

2023-04-19 12:58 UTC, coderdeadpool commented
Github, generate report

2023-04-19 13:08 UTC, romani commented
use all tokens at `property name="tokens" value="VARIABLE_DEF"`

2023-04-19 13:10 UTC, coderdeadpool commented
Done

2023-04-19 13:46 UTC, nrmancuso commented
@coderdeadpool you must have only a single ` ` between `Diff Regression config:` and link, newlines are not supported

2023-04-19 13:47 UTC, nrmancuso commented
Github, generate report

2023-04-19 16:47 UTC, nrmancuso commented
@coderdeadpool report generation failure here is from out of memory error in CI, this is usually an indicator of a lot of diffs/violations. Please generate report locally with all projects and share via github.io

2023-04-19 22:34 UTC, romani commented
Or split config in two configs and execute report in two trigger comments, one after another.

2023-04-19 23:01 UTC, romani commented
Please do not share images of reports, do uploading  to GitHub, read on how to do this at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/README_MANUAL_EXECUTION.md#executing-diffgroovy

2023-04-20 11:41 UTC, coderdeadpool commented
Github, generate website

2023-04-20 12:59 UTC, nrmancuso commented
Github, generate report

2023-04-20 16:38 UTC, romani commented
@coderdeadpool, please remove conflict to let me merge

2023-04-20 16:47 UTC, coderdeadpool commented
Done.

2023-04-20 17:29 UTC, romani approved these changes
Ok to merge if CI pass

2023-04-20 17:33 UTC, coderdeadpool commented
@romani Do we have to generate report again ?

2023-04-20 18:32 UTC, merged

2023-04-20 18:32 UTC, romani commented
No, it was conflict in suppression file