Issue #11214: minor: Specified violation messages in CustomImportOrder
checkstyle/checkstyle pull request #13028
Opened 2023-04-25 12:41 UTC by aaryan-gautam

Fixes https://github.com/checkstyle/checkstyle/issues/11214

2023-04-25 13:38 UTC, romani commented
Please do fixes of violations of CI

2023-04-25 13:41 UTC, romani requested changes
Items

2023-04-25 13:41 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault.java
> +import java.awt.Button; // violation should be at the end
Please use real violation message.

2023-04-28 15:45 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault.java
> +import java.awt.Button; // violation should be at the end
Please review changes in similar Check https://github.com/checkstyle/checkstyle/pull/12772/files

2023-05-01 15:07 UTC, romani requested changes
Good, but please remove this Check from suppression list in java code, see issue description to a line where to do this.

2023-05-01 21:30 UTC, aaryan-gautam commented
> Good, but please remove this Check from suppression list in java code, see issue description to a line where to do this.

I have already removed the check from suppression list in the previous commit 04ed952584bbb6bc08ca11c73c6f848f32fd1075
https://github.com/checkstyle/checkstyle/blob/4838dbc82ced038cfb72fdcada612dcfdec8a93c/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java#L105

2023-05-02 01:25 UTC, romani commented
Please keep single commit in PR all the time.
Please strictly follow commit message template, please fix CI failures

2023-08-31 17:52 UTC, rnveach commented
CI needs to be green. Needs to be rebased.

2023-09-01 01:51 UTC, romani commented
Considering amount of conflicts, better to do it from scratch

2023-09-01 01:51 UTC, closed without merging