Issue #13026: Modify the instructions for checks related to record in WriteTagCheck
checkstyle/checkstyle pull request #13034
Opened 2023-04-27 10:40 UTC by Sloent

Issue: #13026 
Modify violation messages associated with 'record'.
Update doc:
![image](https://user-images.githubusercontent.com/116325914/234838806-893f250c-0a29-436b-a23f-304bf08df10d.png)

2023-04-27 13:31 UTC, romani requested changes
Root problem is not clear goal of this ancient Check.
and not clear documentation.

Confusion is that this Check demands:
- if no target javadoc tag give violation
- if tag is present, put violation on tag that match regexp.

I think we need to update description of this Check to describe this.


from doc:
>Requires user defined Javadoc tag to be present in Javadoc comment with defined format.

this is bad wording, as it is not exactly what happening.
proposal: `Requires user defined Javadoc tag to be present in Javadoc comment, tag that match format will be marked as violation.`

>  Property tagSeverity is used for severity of events when the tag exists. 

` Property tagSeverity is used for severity of violations when the tag exists. `


-----

And we need extend example to show it.

2023-04-27 13:31 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
> + * is the same.
this sounds strange ... as it is also applicable to interfaces and all other target tokens.

2023-04-27 14:25 UTC, Sloent commented
> - if no target javadoc tag give violation
> - if tag is present, put violation on tag that match regexp.

So I need to update the documentation for this check and add examples to describe the two requirements above?  Then do I need to keep the other modifications I have made so far?

2023-04-27 15:10 UTC, Sloent commented
I got it

2023-04-28 16:00 UTC, romani commented
Do not hesitate to close this PR and open new with changes I pointed at https://github.com/checkstyle/checkstyle/pull/13034#pullrequestreview-1404044934

Or simply change things PR.

2023-04-29 08:32 UTC, Sloent commented
Maybe I stayed up too hard this month and had a fever of 38.5 degrees last night.  In addition, I have to hand in some course work and a paper for the math school competition when I return from the holiday.  Maybe I can't deal with this issue these days.  After I solve other problems, I will open a new PR according to your requirement.

2023-08-31 17:55 UTC, rnveach commented
CI needs to be green. Needs to be rebased.

2023-09-02 14:59 UTC, romani commented
I lost reason of this update.
if we do extension of doc we kind should do same for all others modules, but take it for granted that user knows that  interface/class/enum/record are kind the same , they are types that can have javadoc.

2023-09-02 14:59 UTC, closed without merging