minor: remove extra word based on feedback
checkstyle/checkstyle pull request #13093
Opened 2023-05-27 14:27 UTC by romani

2023-05-27 14:42 UTC, rnveach requested changes
We should swap `Target` with `POM`.

2023-05-28 13:36 UTC, romani commented
done

2023-05-28 15:27 UTC, rnveach approved these changes

2023-05-29 12:24 UTC, nrmancuso approved these changes

2023-05-29 12:25 UTC, merged