Issue #13109: Kill mutation for EqualsAvoidNullCheck 3
checkstyle/checkstyle pull request #13126
Opened 2023-06-01 07:29 UTC by Kevin222004

Issue #13109: Kill mutation for EqualsAvoidNullCheck 3

-------------------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/c515fe44cd311783e6cbdf0f5788b4d3/raw/15647eeebde66f0c3a366f655442b02b4d55efef/equal.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/08abf0204adc3dbcbf8d6379cd57be4ad325b232/test-projects.properties

2023-06-01 07:29 UTC, Kevin222004 commented
GitHub, generate report

2023-06-01 10:33 UTC, nrmancuso commented
@Kevin222004 looks like GitHub runner ran out of space: https://github.com/checkstyle/checkstyle/actions/runs/5141568905/jobs/9254217315#step:9:5992

2023-06-02 04:17 UTC, Kevin222004 commented
https://kevin222004.github.io/reports/Ev3/2023-06-01-T-23-12-41/test-report/index.html

2023-06-03 14:16 UTC, romani requested changes
items:

2023-06-03 14:16 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
> +            return new HashSet<>(children);
I asked this question somewhere.

How ca we instruct pitest to not mutate  `Collections.unmodifiableSet` better to keep code restrictive on mutability, even nobody even tried to change this collection.

2023-06-13 06:57 UTC, Kevin222004 commented
closing this covered at https://github.com/checkstyle/checkstyle/pull/13127

2023-06-13 06:57 UTC, closed without merging