Issue #13140: Fix NullPointerException
checkstyle/checkstyle pull request #13141
Opened 2023-06-03 10:49 UTC by SebHeuze

# Fix Issue #13140 

NullChecking is missing to avoid an error when reading a ternary operator that contain unnecessary parenthesis, these can of course be removed but this is another checkstyle rule and should not throw any exception while reading this line

2023-06-03 13:33 UTC, romani commented
@SebHeuze , thanks a lot for fix, please address CI failures 
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=14552&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=824

looks like there some spaces at the of commit message, please follow commit format.

please recheck "mvn verify" passing before push.

2023-06-05 10:23 UTC, SebHeuze commented
Yes, didn't seen that space at the end, I fixed the commit message

2023-06-05 15:59 UTC, romani approved these changes
Ok to merge.

2023-06-05 20:12 UTC, rdiachenko approved these changes
lgtm

2023-06-05 20:30 UTC, nrmancuso requested changes
Please generate regression report by GitHub action: https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation

2023-06-05 20:52 UTC, SebHeuze commented
GitHub, generate report

2023-06-05 22:15 UTC, merged