Issue #13109: Kill mutation for OneStatementPerLineCheck
checkstyle/checkstyle pull request #13163
Opened 2023-06-05 14:46 UTC by Kevin222004

Issue #13109: Kill mutation for OneStatementPerLineCheck

-------------

# Check :- https://checkstyle.org/config_coding.html#OneStatementPerLine

-----------

# Mutation covered 
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L219-L244

2023-06-06 02:30 UTC, romani commented
You need to provide long explanation why not possible to cover by Inputs.

We do not accept testing by pure unit test.

2023-06-06 02:30 UTC, romani requested changes
See above

2023-06-21 10:51 UTC, Kevin222004 commented
@romani done input based test added

2023-06-23 10:57 UTC, Vyom-Yadav approved these changes
LGTM!

2023-06-25 03:09 UTC, romani commented
@Kevin222004 , please resolve conflict and look at CI failing

2023-06-27 13:12 UTC, romani requested changes
items:

2023-06-27 13:40 UTC, Kevin222004 commented on src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
> +    public void testStateIsClearedOnBeginTree1() throws Exception {
Done

2023-06-27 15:10 UTC, romani approved these changes
Ok to merge if CI is green

2023-06-28 20:31 UTC, rdiachenko commented
@Kevin222004 please resolve a conflict

2023-06-29 20:26 UTC, rdiachenko approved these changes
lgtm

2023-06-29 20:38 UTC, rdiachenko commented
rebased via Github

2023-06-29 22:47 UTC, merged