Issue #13501: Kill mutation for ImportOrderCheck-2
checkstyle/checkstyle pull request #13232
Opened 2023-06-15 13:24 UTC by Kevin222004

Issue #13501: Kill mutation for ImportOrderCheck-2

---------

Check : 
https://checkstyle.org/config_imports.html#ImportOrder
https://checkstyle.org/checks/imports/importorder.html#ImportOrder

----------

# Mutation covered 
https://github.com/checkstyle/checkstyle/blob/58fdccf566a46b2ad4eea3987be3157d323bb3a8/config/pitest-suppressions/pitest-imports-suppressions.xml#L57-L73

--------

# Explaination

https://pitest.org/quickstart/mutators/#non-void-method-call-mutator-non_void_method_calls

test was added.

---------

# Regression 

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/64068f25e12fc53287e29c691b44b0cd/raw/3f08e73e3946ef9ef59bd119028bb67eff99b15b/ImportOrder.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: R2

2023-06-15 13:25 UTC, Kevin222004 commented
Github, generate report

2023-06-16 02:16 UTC, prajwalah28 commented
<mutation unstable="false"> 
   <sourceFile>ImportOrderCheck.java</sourceFile> 
   <mutatedClass>com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck</mutatedClass> 
   <mutatedMethod>getGroupNumber</mutatedMethod> 
   <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator> 
   <description>removed call to java/util/regex/Matcher::end</description> 
   <lineContent></lineContent> 
 </mutation>

2023-06-16 02:17 UTC, prajwalah28 commented
``<mutation unstable="false"> 
   <sourceFile>ImportOrderCheck.java</sourceFile> 
   <mutatedClass>com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck</mutatedClass> 
   <mutatedMethod>getGroupNumber</mutatedMethod> 
   <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator> 
   <description>removed call to java/util/regex/Matcher::end</description> 
   <lineContent>bestEnd = matcher.end();</lineContent> 
 </mutation>

2023-06-16 17:32 UTC, Kevin222004 commented
Github, generate report

2023-08-02 16:01 UTC, Kevin222004 commented
Github, generate report

2023-08-02 17:39 UTC, Kevin222004 commented
Github, generate report

2023-08-08 18:09 UTC, romani requested changes
Items:

2023-08-14 03:54 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
> -                    bestEnd = matcher.end();
@Kevin222004 , ping.
Please play with almost same groups.

2023-08-18 13:07 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
> -                    bestEnd = matcher.end();
@Kevin222004 , here is how to quicky play with this methods coverage - https://github.com/checkstyle/checkstyle/commit/e0e1161b3c454e3b31f7009196c044ef590fa4f3

ones you kill it by pure unit test, you can convert it to Input based.

2023-08-24 17:22 UTC, Kevin222004 commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
> -                    bestEnd = matcher.end();
It is getting a long delay in this pr but I am trying to find test 

Just a update on this pr  I have found a pure ut which kill one mutation `if (matcher.start() < bestPos) {`
```
@Test
public void testPitest() throws Exception {
    Pattern[] patterns = new Pattern[5];
    patterns[0] = Pattern.compile("jarInputStream");
    patterns[1] = Pattern.compile(".util");
    patterns[2] = Pattern.compile(".jar.");
    patterns[3] = Pattern.compile(".util.");
    patterns[4] = Pattern.compile("jar");
    assertWithMessage("")
            .that(ImportOrderCheck.getGroupNumber(patterns, "java.util.jar.JarInputStream"))
            .isEqualTo(3);
}
```

I am trying to make this input base and also for other mutation trying to find test

2023-09-10 15:19 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
> -                    bestEnd = matcher.end();
we missed a fact that we treat provided packages as full name from the beginning, 
https://github.com/checkstyle/checkstyle/blob/8e8962a365fdafec1b3e5fade58784a7fe0e32c7/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L768-L771

so we can not use `.util` or `awt` , all patterns must have full name from the beginning. So it meant that getGroupNumber should be aware of this, so finding most early `bestPos` is nonsense at line `if (matcher.start() < bestPos) {`.

2023-09-10 15:42 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
> -                    bestEnd = matcher.end();
ok, we can use regexp, but we have to use `/` around values to make it treated as-is - https://checkstyle.org/checks/imports/importorder.html#Properties

2023-09-13 13:31 UTC, romani approved these changes
just test.

Ok to merge

2023-09-13 19:14 UTC, rdiachenko approved these changes
lgtm

2023-09-13 19:38 UTC, merged

2023-09-13 19:38 UTC, romani commented
Just test, we merge on single review.