Issue #13109: Kill mutation for PackageNamesLoader
checkstyle/checkstyle pull request #13286
Opened 2023-06-21 17:54 UTC by Kevin222004

Issue #13109: Kill mutation for PackageNamesLoader

# Mutation 
https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-packagenamesloader-suppressions.xml

2023-06-21 17:56 UTC, Kevin222004 commented on src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java
> +    public static Map<String, String> createIdToResourceNameMap() {
This case looks not possible to cover. But to cover the test it is required to make it public.

Please give your suggestion if it is not fine

2023-06-21 19:42 UTC, Kevin222004 commented
Failures are not related to changes

2023-06-23 01:15 UTC, nrmancuso requested changes
@Kevin222004 please try:

```
    private PackageNamesLoader()
            throws ParserConfigurationException, SAXException {
        super(Map.of(
            DTD_PUBLIC_ID, DTD_RESOURCE_NAME,
            DTD_PUBLIC_CS_ID, DTD_RESOURCE_NAME
        ));
    }
```

And remove method completely.

2023-06-23 04:44 UTC, Kevin222004 commented
> @Kevin222004 please try:
> 
> ```
>     private PackageNamesLoader()
>             throws ParserConfigurationException, SAXException {
>         super(Map.of(
>             DTD_PUBLIC_ID, DTD_RESOURCE_NAME,
>             DTD_PUBLIC_CS_ID, DTD_RESOURCE_NAME
>         ));
>     }
> ```
> 
> And remove the method completely.

Done, Thanks :), I don't get this idea in my mind while working on this pr

2023-06-23 04:51 UTC, Kevin222004 commented
@nrmancuso @romani @stoyanK7 I don't know you are aware of this or not but 
```
[INFO]      [echo] Checkstyle started (checkstyle-input-checks.xml): 23/06/2023 10:16:12 am
[INFO] [checkstyle] Running Checkstyle  on 2109 files
[INFO]      [echo] Checkstyle finished (checkstyle-input-checks.xml): 23/06/2023 10:17:22 am
[INFO]      [echo] Checkstyle started (checkstyle-examples-checks.xml): 23/06/2023 10:16:12 am
[INFO] [checkstyle] Running Checkstyle  on 54 files
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/check_style/checkstyle/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java:14: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/check_style/checkstyle/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java:15: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/check_style/checkstyle/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example2.java:25: Trailing whitespace is not allowed [noTrailingWhitespace]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:48 min
[INFO] Finished at: 2023-06-23T10:18:46+05:30

```

This error is from master branch might be from https://github.com/checkstyle/checkstyle/pull/13272

2023-06-23 10:07 UTC, stoyanK7 commented
@Kevin222004 Thanks for the tip. Kind of expected because we didn't have the checks when these examples got merged. I opened PR https://github.com/checkstyle/checkstyle/pull/13294. Please disregard these errors.

2023-06-23 12:28 UTC, nrmancuso approved these changes
PR is rebased, ok to merge.

2023-06-26 16:59 UTC, Kevin222004 commented
@rdiachenko ping

2023-06-26 19:19 UTC, rdiachenko approved these changes
lgtm

2023-06-27 13:00 UTC, romani requested changes
items:

2023-06-27 13:00 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java
> +            DTD_PUBLIC_CS_ID, DTD_RESOURCE_NAME
same as https://github.com/checkstyle/checkstyle/pull/13299#discussion_r1243693995

2023-07-01 09:16 UTC, Kevin222004 commented on src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java
> +            DTD_PUBLIC_CS_ID, DTD_RESOURCE_NAME
Done Please check Test added

2023-07-01 15:52 UTC, Kevin222004 commented
@romani only test added still linkcheck failing

2023-07-01 17:36 UTC, romani approved these changes
Ok to merge 

Just tests were added

2023-07-01 17:37 UTC, merged