Issue #13279: Support JDK 20 preview language features
checkstyle/checkstyle pull request #13291
Opened 2023-06-22 05:09 UTC by nrmancuso

Closes #13279 

-----------------------

## Check Regression Reports
https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/sevntu-check-regression_part_1-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part4-report/index.html - no dif

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part2-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part3-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part5-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part6-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/part1-report/index.html - no diff

https://nrmancuso.github.io/reports/issue-13279/2023-07-20-T-17-39-42/sevntu-check-regression_part_2-report/index.html - no diff

---------------------
## ANTLR regression reports

https://nrmancuso.github.io/reports/issue-13279/2023-07-21-T-06-50-01/antlr-report/index.html

2023-07-23 02:40 UTC, nrmancuso commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java20/ExpectedJava20RecordDecompositionEnhancedForLoopTricky.txt
> +        |       |       |   |       `--IDENT -> points1 [32:51]
Example of basic record component decomposition in enhanced for loop:
```
 for (Point(final var x, final var y) : points1) {
  }
```

2023-07-23 04:04 UTC, romani requested changes
good, only minors:

2023-07-23 14:17 UTC, nrmancuso commented
Moving this back to draft, I want to double check some things at https://docs.oracle.com/javase/specs/jls/se20/preview/specs/patterns-switch-record-patterns-jls.html

2023-07-23 14:18 UTC, nrmancuso commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java20/InputJava20RecordDecompositionEnhancedForLoopTricky.java
> +        // ticket is opened with openjdk.
I do not have a ticket number, it is still in review. I created an issue for us to track this at https://github.com/checkstyle/checkstyle/issues/13418#issuecomment-1646848517

2023-07-23 14:18 UTC, nrmancuso commented on config/jsoref-spellchecker/whitelist.words
> +Decomp
Done

2023-07-23 14:39 UTC, romani approved these changes
ok to merge.

2023-07-29 17:58 UTC, nrmancuso commented
@romani @rnveach ok, I have resolved my doubts, see conclusion of investigation at https://github.com/checkstyle/checkstyle/pull/13291#issuecomment-1646851409

2023-08-01 00:29 UTC, rnveach approved these changes

2023-08-01 04:19 UTC, merged