Issue #13109: Kill mutation for SummaryJavaDocCheck-5
checkstyle/checkstyle pull request #13315
Opened 2023-06-26 18:24 UTC by Kevin222004

Issue #13109: Kill mutation for SummaryJavaDocCheck-5

-----

# Check :- 
https://checkstyle.org/checks/javadoc/summaryjavadoc.html#SummaryJavadoc

-----

# Mutation 

-----

# Explaination

-----

# Regression :- 

-----

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/61eaa69fe98585b6ee1882ca082362bc/raw/c74195e574d09886a3406be17a9d46787da9545e/Summary.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Regression-1

2023-06-26 18:24 UTC, Kevin222004 commented
Github, generate report

2023-06-28 08:18 UTC, Kevin222004 commented
Github, generate report

2023-06-28 09:08 UTC, Kevin222004 commented
Github, generate report

2023-06-28 12:37 UTC, romani requested changes
Items

2023-06-28 12:37 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
>          while (previousSibling != null && isDefinedFirst) {
Please rename to ` currentAst`

2023-07-02 07:43 UTC, Vyom-Yadav approved these changes
LGTM!

2023-07-03 20:25 UTC, rdiachenko approved these changes
lgtm

2023-07-03 20:25 UTC, merged