Issue #13328: Kill mutation for UnusedLocalVariableCheck 10
checkstyle/checkstyle pull request #13331
Opened 2023-07-01 03:54 UTC by Kevin222004

Issue #13328: Kill mutation for UnusedLocalVariableCheck 10

------

# Check :- 
https://checkstyle.org/checks/coding/unusedlocalvariable.html#UnusedLocalVariable

--------

# Mutation
https://github.com/checkstyle/checkstyle/blob/554a87ea9b5ae27f9519e8dbca15a116bcc108a4/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L84-L95

-----------

# Explaination

The reason to make typeast null is as similar as https://github.com/checkstyle/checkstyle/pull/13145#issue-1739850025
that we don't throw violation on instance or class variable

----------

# Regression :- 

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0dbdfb487f8e9a050ed0e6356f1a35b4/raw/31f7927f400e11e4285e86fd086b373095227848/unusedLocal.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Final-Regression-1

2023-07-01 03:55 UTC, Kevin222004 commented
Github, generate report

2023-07-01 04:10 UTC, romani requested changes
Items

2023-07-01 04:10 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
> +                        null, updatedScope);
Please make two params ctor instead

2023-07-01 07:32 UTC, Kevin222004 commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
> +                        null, updatedScope);
Done

2023-07-01 07:49 UTC, Kevin222004 commented
Github, generate report

2023-07-01 07:50 UTC, Kevin222004 commented
@romani @rdiachenko @Vyom-Yadav Please merge this pr first before https://github.com/checkstyle/checkstyle/pull/13151 and https://github.com/checkstyle/checkstyle/pull/13152

2023-07-01 16:24 UTC, romani approved these changes
Ok to merge

2023-07-02 08:27 UTC, Vyom-Yadav commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
> +
Ok for killing the mutation. IMO the check design should be slightly modified not to ask for `type` if it is an instance variable.

2023-07-02 08:28 UTC, Vyom-Yadav approved these changes
LGTM!

2023-07-03 20:39 UTC, rdiachenko approved these changes
lgtm

2023-07-03 20:39 UTC, merged