minor: Added all the check test to pitest-utils profile
checkstyle/checkstyle pull request #13379
Opened 2023-07-08 11:01 UTC by Kevin222004

minor: Added all the check test to pitest-utils profile

2023-07-09 13:36 UTC, romani commented
Adding all in not good option, as it will make execution to be hours. Please keep adding checks tests one by one to keep execution time minimized.

2023-07-09 14:28 UTC, Kevin222004 commented
Yes this is just for testing purpose i am not going to add all

2023-07-21 01:22 UTC, romani requested changes
Items

2023-07-21 01:22 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil3.java
> +                if (true) { // violation
Please use message for each violation

2023-07-21 07:23 UTC, Kevin222004 commented on src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil3.java
> +                if (true) { // violation
Done

2023-07-21 07:25 UTC, Kevin222004 commented
Please re-run failed ci
semaphore is also not looking related to changes

2023-07-21 07:26 UTC, Kevin222004 commented
Failure of Semaphore 

```
[INFO] Across all seeds:18:04
[INFO] com.puppycrawl.tools.checkstyle.checks.whitespace.SingleSpaceSeparatorCheckTest#testNoStackoverflowError18:04
[INFO] Test results can be found at: 18:04
[INFO] file:///home/semaphore/checkstyle/.nondex/mqPUyJg3YLld6jAMyRVk7sXkJs4gRpxIwGKZagQ7HkI=/test_results.html18:04
[INFO] [NonDex] The id of this run is: mqPUyJg3YLld6jAMyRVk7sXkJs4gRpxIwGKZagQ7HkI=18:04
[INFO] ------------------------------------------------------------------------18:04
[INFO] BUILD FAILURE18:04
[INFO] ------------------------------------------------------------------------18:04
[INFO] Total time:  18:02 min18:04
[INFO] Finished at: 2023-07-21T07:11:03Z18:04
[INFO] ------------------------------------------------------------------------
```

I have faced `[INFO] com.puppycrawl.tools.checkstyle.checks.whitespace.SingleSpaceSeparatorCheckTest#testNoStackoverflowError18:04` in my local many time as well. while generating reports

2023-07-21 13:16 UTC, romani approved these changes
ok to merge.

2023-07-21 13:25 UTC, merged