Issue #13321: Kill mutation for DetailAstImpl-2
checkstyle/checkstyle pull request #13390
Opened 2023-07-12 08:38 UTC by Kevin222004

Issue #13321: Kill mutation for DetailAstImpl-2

https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java

-------

# Mutations 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L48-L64

--------

# Explaintion 
here the code in method to addPreviousSibiling is 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L116-L135
in which line no 121 and 133 is mutated and the reasonto removal is same for both

here as per the condition `if (previousSibilingNode != null` it shows that we already have previousSibilingNode

lets suppose an example we have 2 node connected y and x in which y is the previous sibiling of node x. 
some thing like
 ```y - x```
and know we want to add the new previous sibiling of x which is w.
in that case the sceanrio looks like
``` y - w - x ```

know to make changes like this we need to perfom operation where 
according to the code we have in our codebase previousSibiling variable would be y in this case 
know
 https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L121-L122

here as `previousSibilingNode` we are assinging `previousSibiling` it means know for my example 
`previousSibilingNode = y` and `astImpl = w`

so know to achieve `y - w - x`
1) we have to set w previous sibiling to y 
which is done by 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L125

where astImpl means `w.previousSibiling = y` is set 
so the know the sceanrio looks like
`y <-- w`  
2) know we have to add y's next sibiling to w
which is done by 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L126
this will set next sibiling of y as w 

know rest of the thing means we have set the condition right know as 
`y - w` but still we have to connect it with x which is done by https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L132-L133 
with way i mention above.

so know in this both the case we see that we are setting nodes next sibiling using method `setNextSibiling`.
which code is 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L468-L478
which is setting next sibiling for node 
so lets talk where we have to set y's next sibiling as w
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L126

here our previousSibilingNode is y and we have to set w as nextsibiling which is w
so 
here first directly https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L471
after this line execute we got what we want 
`y - w` 
but this code contains 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L475-L477
in which our nextSibiling never going to null so this statment is again assigning nextsibiling means in our case
the statment look like 
`w .previousSibiling = this`and it would be y

which we are setting in https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L125 
and
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L133

we can verify this using for particular 	`addPreviousSibiling` method
**Note:-** 
This is just for testing it will affect the tree structure if we made change like this.

change https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L126 as 
`previousSiblingNode.nextSibling = astImpl;` know if you remove the statment above statment then test will fail.

2023-07-16 11:47 UTC, nrmancuso commented
@Kevin222004 what is your plan for regression testing this change? We should treat changes to this class the same way we do for grammar changes, IMO. This means regression testing on all checks and ANTLR regression testing.

2023-07-16 11:53 UTC, Kevin222004 commented
yes, I am also thinking similar that this changes require regression on all the check

I think this will https://github.com/nrmancuso/nrmancuso.github.io/tree/master/configs make my work easy

2023-07-16 13:53 UTC, nrmancuso commented
@Kevin222004 you can just send a PR to my repo to generate reports of you want to

2023-07-29 14:49 UTC, romani requested changes
looks good.

last minor:

2023-07-29 14:49 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
> +        final DetailAstImpl pr = new DetailAstImpl();
pr -> `secondNewPreviousSibling`

2023-07-29 14:53 UTC, nrmancuso commented
@Kevin222004 please always provide an analysis of reports, if there is no diff you can save us a bunch of clicks :)

2023-07-29 14:58 UTC, Kevin222004 commented
@nrmancuso https://github.com/checkstyle/checkstyle/pull/13390#issuecomment-1656747380 ok will take care of this 
I updated the description

2023-07-29 15:23 UTC, Kevin222004 commented on src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
> +        final DetailAstImpl pr = new DetailAstImpl();
Done

2023-07-29 17:09 UTC, romani approved these changes
Ok to merge

2023-07-29 18:24 UTC, Kevin222004 commented
@romani @nrmancuso I have added some new reports and found diff
1) https://kevin222004.github.io/reports/com1/2023-07-29-T-17-58-13/part3-report/index.html
2) https://kevin222004.github.io/reports/com1/2023-07-29-T-17-58-13/checks-nonjavadoc-error-report/index.html
this 2 are accpeted in my opinion it will also fail if the code is not removed

3) https://kevin222004.github.io/reports/com1/2023-07-29-T-17-58-13/antlr-report/index.html
I am trying to understaing this one

2023-07-30 14:23 UTC, romani commented
> Violations: src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLongConcatenatedString.tree

diff just shows that exception become a bit different, but we do not support non java files, so format of exception does not matter for us.

I do not see config for this report. By what tool you generated it ?

2023-07-30 17:08 UTC, Kevin222004 commented
> I do not see config for this report. By what tool you generated it ?

I have generated using https://github.com/Kevin222004/Kevin222004.github.io
This tool is created by @nrmancuso https://github.com/nrmancuso/nrmancuso.github.io

2023-07-31 14:18 UTC, nrmancuso approved these changes
Difference in ANTLR diff report is exception from a different method call, but for the same reason; StackOverflowError. Report is good.

2023-08-01 08:18 UTC, Vyom-Yadav approved these changes
LGTM!

2023-08-01 21:11 UTC, rdiachenko approved these changes
lgtm

2023-08-01 21:12 UTC, rdiachenko commented
rebased

2023-08-02 16:40 UTC, romani commented
Rebased by GitHub one more time

2023-08-03 00:43 UTC, merged