Issue #13411: Fix NPE in UnnecessarySemicolonAfterTypeMemberDeclarationCheck
checkstyle/checkstyle pull request #13486
Opened 2023-07-30 21:01 UTC by relentless-pursuit

Resolve #13411

2023-07-30 21:05 UTC, relentless-pursuit commented
@romani and @nrmancuso 

Sorry for the hassle. This is a new PR. Kindly review whenever convenient for you. I have made changes as requested by @nrmancuso. 

Past PR's conversation as a reference:https://github.com/checkstyle/checkstyle/pull/13417

2023-07-31 00:39 UTC, romani commented
Please fix https://github.com/checkstyle/checkstyle/actions/runs/5708338178/job/15466147589?pr=13486#step:6:14

2023-07-31 05:23 UTC, relentless-pursuit commented
> Please fix https://github.com/checkstyle/checkstyle/actions/runs/5708338178/job/15466147589?pr=13486#step:6:14

done. can i be assigned reviewers as i have made requested changes?

2023-07-31 05:41 UTC, romani commented
Please do report generation https://github.com/checkstyle/checkstyle/pull/13417#pullrequestreview-1551157067

Examples: https://github.com/checkstyle/checkstyle/pull/13475

2023-07-31 05:58 UTC, relentless-pursuit commented
Github, generate report

2023-07-31 06:33 UTC, relentless-pursuit commented
> Please do report generation [#13417 (review)](https://github.com/checkstyle/checkstyle/pull/13417#pullrequestreview-1551157067)
> 
> Examples how others are doing it: #13475

Bit confusing. Reading the documentation. Will seek help on this.

2023-08-01 13:21 UTC, relentless-pursuit commented
GitHub, generate report

2023-08-01 13:22 UTC, relentless-pursuit commented
> Resolve #13411
> 
> Diff Regression config: https://gist.githubusercontent.com/relentless-pursuit/95180658ff45ac1bab444f2c35ac301d/raw/d53eda164c7ccd456cb6a1def8bb4e4f0de9c39c/gistfile1.txt Diff Regression projects: https://gist.githubusercontent.com/relentless-pursuit/b51c223730e8e119e34855226bef3865/raw/6989794a8eb9ad5fde3995f637617cc775173973/gistfile1.txt

@Romani, have i done it right?

2023-08-01 13:28 UTC, relentless-pursuit commented
GitHub, generate report

2023-08-01 13:54 UTC, nrmancuso commented
@relentless-pursuit click through link at https://github.com/checkstyle/checkstyle/pull/13486#issuecomment-1660361711 and read error messages. Also - you do not need to use a projects file, you can remove that from the PR description.

2023-08-01 14:25 UTC, relentless-pursuit commented
GitHub, generate report

2023-08-01 17:31 UTC, relentless-pursuit commented
> @relentless-pursuit please rebase on latest master and resolve conflicts to prepare for final review, report looks good

done.

2023-08-01 18:44 UTC, nrmancuso requested changes
Item:

2023-08-01 18:44 UTC, nrmancuso commented on config/projects-to-test/openjdk20-excluded.files
The only change in this file should be the removal of related suppression module, we should not add modules back.

2023-08-01 19:12 UTC, relentless-pursuit commented on config/projects-to-test/openjdk20-excluded.files
> The only change in this file should be the removal of related suppression module, we should not add modules back.

the recent push looks fine. please let me know your feedback.

2023-08-01 19:40 UTC, relentless-pursuit commented on config/projects-to-test/openjdk20-excluded.files
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':postgresql'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':postgresql:classpath'.
      > Could not resolve gradle.plugin.com.github.lburgazzoli:gradle-karaf-plugin:0.5.6.
        Required by:
            project :postgresql > com.github.lburgazzoli.karaf:com.github.lburgazzoli.karaf.gradle.plugin:0.5.6
         > Could not resolve gradle.plugin.com.github.lburgazzoli:gradle-karaf-plugin:0.5.6.
            > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/github/lburgazzoli/gradle-karaf-plugin/0.5.6/gradle-karaf-plugin-0.5.6.pom'.
               > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/com/github/lburgazzoli/gradle-karaf-plugin/0.5.6/gradle-karaf-plugin-0.5.6.pom'. Received status code 530 from server: 
```

Not sure why it is failing.

2023-08-01 19:42 UTC, relentless-pursuit commented
GitHub, generate report

2023-08-01 20:01 UTC, nrmancuso commented on config/projects-to-test/openjdk20-excluded.files
Latest push looks good.

2023-08-01 21:25 UTC, merged