Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck2
checkstyle/checkstyle pull request #13573
Opened 2023-08-20 19:50 UTC by Kevin222004

Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck2

----

# Check
https://checkstyle.org/checks/javadoc/javadoctagcontinuationindentation.html#JavadocTagContinuationIndentation

-------

# Mutation 
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L516-L541

-----

# Explaination

loop run 1 time more

---------

# Regression

Report-1 :- 

Report-2 :- 

--------

Diff Regression config: https://gist.githubusercontent.com/Kevin222004/ec7b8b74e9e64a8a9f9c0014860b2016/raw/e392cb5c586eacde87601e6ef62098f95b8eba8f/JavadocTagContinuationIndentationCheck.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test-projects-2.properties
Report label: Regression-1

2023-08-20 19:51 UTC, Kevin222004 commented
Github, generate report

2023-08-20 20:33 UTC, romani commented
@Kevin222004 , basic CI is red

2023-08-21 03:54 UTC, romani commented
Rebased to fix CI failure on ok comment

2023-08-21 13:06 UTC, romani approved these changes
ok to merge if reports are clean

2023-08-21 15:47 UTC, Kevin222004 commented
Github, generate report

2023-08-21 17:59 UTC, romani commented
@Kevin222004 , conflict

2023-08-21 18:37 UTC, rdiachenko approved these changes
lgtm

2023-08-22 09:06 UTC, Vyom-Yadav requested changes
Item:

2023-08-22 12:39 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
> +        DetailNode inlineTag = description;
@Kevin222004 , please do.

2023-08-22 17:27 UTC, Kevin222004 commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
> +        DetailNode inlineTag = description;
Done

2023-08-23 03:12 UTC, romani approved these changes

2023-08-23 03:12 UTC, merged