Issue #13213: Resolve the '//ok' comments from annotationlocation pac…
checkstyle/checkstyle pull request #13679
Opened 2023-09-01 13:39 UTC by Rohanraj123

part of #13213 

Link to check the documentation :  [clickHere](https://checkstyle.org/checks/annotation/annotationlocation.html#AnnotationLocation)

proof that all supressions for this check are removed 

```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep annotationlocation config/checkstyle-input-suppressions.xml
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCustomAnnotationsDeclared.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCustomAnnotationsDeclared.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationCustomAnnotationsDeclared.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationDeprecatedAndCustom.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationDeprecatedAndCustom.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationDeprecatedAndCustom.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationEmpty.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationIncorrect2.java"/>
      [...]

2023-09-01 13:43 UTC, nrmancuso approved these changes
Ok to merge as CI passes.

@Rohanraj123 please do not open and close PRs.

2023-09-01 13:44 UTC, nrmancuso commented
@romani we can use this PR as example in issue

2023-09-01 13:51 UTC, Rohanraj123 commented
> Ok to merge as CI passes.
> 
> @Rohanraj123 please do not open and close PRs.

Sir sorry but I am newbie at this open source contribution and am getting confused  why these tests fails again and again even after doing everything right. And i closed last PR by mistake. Sorry for the inconvenience. I will not close this PR now. Now suggest me the changes i can do in this PR please.

2023-09-01 14:02 UTC, nrmancuso commented
Please read: https://checkstyle.sourceforge.io/beginning_development.html

Make sure that `mvn clean verify` is passing before pushing changes. Take time to read and understand failure messages.

>tests fails again and again even after doing everything right

If tests are failing, everything is not right :)

It looks like you removed a suppression for a file that has not been updated.

2023-09-01 14:47 UTC, nrmancuso requested changes
You should have exactly one commit in this PR, please squash into 1.

2023-09-01 14:47 UTC, nrmancuso commented on config/checkstyle-input-suppressions.xml
> +            files="checks[\\/]annotation[\\/]annotationlocation[\\/]InputAnnotationLocationRecordsAndCompactCtors.java"/>
We need to update this input file, not add suppression back.

2023-09-01 14:48 UTC, Rohanraj123 commented
> You should have exactly one commit in this PR, please squash into 1.

sure am waiting for CI passes

2023-09-01 15:03 UTC, nrmancuso commented
> > You should have exactly one commit in this PR, please squash into 1.
> 
> sure am waiting for CI passes

CI will not pass, I see that you are still not running `mvn clean verify` before pushing changes. Please do this and squash commits into 1.

2023-09-01 15:56 UTC, Rohanraj123 commented
`mvn clean verify`  Successfull

Now I think squashing should solve the issue.

2023-09-02 01:03 UTC, Rohanraj123 commented
@nrmancuso Sir, all checks are cleared and also did successfull `mvn clean verify`  Can you please review it.

2023-09-02 13:27 UTC, romani approved these changes
ok to merge

2023-09-04 11:46 UTC, nrmancuso approved these changes

2023-09-04 11:46 UTC, merged