Issue #13213: Remove '//ok' comments from annotationonsameline
checkstyle/checkstyle pull request #13688
Opened 2023-09-02 17:39 UTC by Rohanraj123

part of #13213 

Link to check documentation : [click here](https://checkstyle.sourceforge.io/checks/annotation/annotationonsameline.html#AnnotationOnSameLine)

proof that all suppressions are removed : 

```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep annotationonsameline config/checkstyle-input-suppressions.xml
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck2.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck2.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck3.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck3.java"/>

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout issue-13213-annotationonsameline
Switched to branch 'issue-13213-annotationonsameline'

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-annotationonsameline)
$ grep annotationonsameline config/checkstyle-input-suppressions.xml
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-annotationonsameline)
$ echo $?
0

```

2023-09-02 19:15 UTC, romani approved these changes
Ok to merge

2023-09-04 11:57 UTC, nrmancuso requested changes
Please resolve conflicts.

Item:

2023-09-04 11:57 UTC, nrmancuso commented on config/checkstyle-input-suppressions.xml
> -            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck3.java"/>
>proof that all suppressions are removed :

Please explain why `grep` shows two results and has an exit code of zero if all suppressions are removed.

2023-09-04 14:52 UTC, Rohanraj123 commented
```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep annotationonsameline config/checkstyle-input-suppressions.xml
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck2.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck2.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck3.java"/>
            files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck3.java"/>

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout issue-13213-annotationonsameline
Switched to branch 'issue-13213-annotationonsameline'

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-annotationonsameline)
$ grep annotationonsameline config/checkstyle-input-suppressions.xml

rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-annotationonsameline)
$ echo $?
1
```

Required grep check..

2023-09-04 16:04 UTC, romani commented
@Rohanraj123, keep single commit always

2023-09-04 16:16 UTC, Rohanraj123 commented
> @Rohanraj123, keep single commit always

I read that in guidelines, I did this by mistake and now I am unable to remove it . Can you please suggest me something to do that. I made the same change in #13690 correctly but here I made some mistake and now I dont know how to remove this unwanted commit.

2023-09-04 16:44 UTC, nrmancuso commented
@Rohanraj123 `mvn clean verify` should always be passing on your local before pushing changes to Github

2023-09-05 11:54 UTC, Rohanraj123 commented
I am not able to remove the extra unwanted commit. How can i do that ? Can you please suggest me something @nrmancuso

2023-09-05 12:34 UTC, romani commented
Remove branch on your local and recreate it from scratch, push with force back to same branch name to GitHub

2023-09-06 02:48 UTC, romani commented
Resolve conflict please

2023-09-06 10:49 UTC, Rohanraj123 commented
> Resolve conflict please

Can you please suggest me how can I resolve this conflit. I research a lot and applied certain approaches but it didn't worked. @romani

2023-09-06 12:32 UTC, romani commented
do backup of your repo to some folder on your local drive
in git repo:
```
git checkout master
git pull upstream master
git branch -D issue-13213-annotationonsameline
git checkout -b issue-13213-annotationonsameline
```
copy all files except for ...supression.xml
apply update to suppression.xml manually
```
git add .
git commit -m ....
git push origin issue-13213-annotationonsameline
```

2023-09-06 14:47 UTC, closed without merging