Issue #13213: Remove '//ok' comments from missingdeprecated
checkstyle/checkstyle pull request #13715
Opened 2023-09-07 03:47 UTC by Rohanraj123

part of #13213 

Link to check documentation : [ClickHere](https://checkstyle.sourceforge.io/checks/annotation/missingdeprecated.html#MissingDeprecated)

```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep missingdeprecated config/checkstyle-input-suppressions.xml
            files="checks[\\/]annotation[\\/]missingdeprecated[\\/]InputMissingDeprecatedGood.java"/>
            files="checks[\\/]annotation[\\/]missingdeprecated[\\/]InputMissingDeprecatedSingleComment.java"/>
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout issue-13213-missingdeprecated
Switched to branch 'issue-13213-missingdeprecated'
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-missingdeprecated)
$ grep missingdeprecated config/checkstyle-input-suppressions.xml
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-missingdeprecated)
$ echo $?
1

```

2023-09-07 04:00 UTC, romani approved these changes
Ok to merge

2023-09-07 17:35 UTC, rnveach commented
@Rohanraj123 There is a conflict now.

2023-09-08 01:03 UTC, Rohanraj123 commented
@rnveach Actually Here the changes I made earlier i.e removed all suppressions and okay comments are not visible but changes have been made. I think due to force push it is overwritten. But suppressions and okay comments have been removed successfully from missingdeprecated package

2023-09-09 15:05 UTC, rnveach requested changes

2023-09-09 15:05 UTC, rnveach commented on config/checkstyle-input-suppressions.xml
> +  <suppress id="UnnecessaryOkComment"
This issue isn't about adding suppressions.

2023-09-10 01:30 UTC, rnveach approved these changes

2023-09-10 01:30 UTC, merged