Issue #13213: Remove '//ok' comments from blocks package
checkstyle/checkstyle pull request #13719
Opened 2023-09-08 07:26 UTC by relentless-pursuit

part of https://github.com/checkstyle/checkstyle/issues/13213

2023-09-08 15:21 UTC, romani requested changes
Items

2023-09-09 17:31 UTC, relentless-pursuit commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCommentBeforeLeftCurly.java
> +    /* I am comment */ {
done

2023-09-09 20:40 UTC, romani approved these changes
Ok to merge.

Thanks a lot for update

2023-09-12 13:08 UTC, nrmancuso approved these changes

2023-09-12 13:09 UTC, nrmancuso commented
Ok to merge as CI passes

Looks like GitHub actions did not run on the last push.

2023-09-12 16:05 UTC, merged