Issue #13668: upper case first letter description of all Module prope…
checkstyle/checkstyle pull request #13750
Opened 2023-09-17 17:28 UTC by romani

…rties except tokens property

related to Issue #13668, as we agreed to make this update as pre-step.

2023-09-17 17:46 UTC, rnveach approved these changes

2023-09-17 17:47 UTC, rnveach requested changes
> config.xml section 'Checker' should have a description for basedir that starts with uppercase character

2023-09-17 18:09 UTC, romani commented
It might be from https://checkstyle.org/config.html#Checker

https://github.com/checkstyle/checkstyle/blob/d94f78fffde2b3180b911c6d8f8c79250803cb9d/src/xdocs/config.xml#L308

2023-09-18 13:20 UTC, rnveach approved these changes

2023-09-19 02:55 UTC, nrmancuso approved these changes

2023-09-19 02:55 UTC, merged