Issue #4845: Removed checkstyle dependencies from illegalimport
checkstyle/checkstyle pull request #13795
Opened 2023-09-28 13:55 UTC by Guneetsinghtuli

Part of #4845

2023-09-28 15:31 UTC, romani requested changes
Items

2023-09-28 15:43 UTC, Guneetsinghtuli commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
> -import java.util.List;
Okay will do that, Just wanted to know the purpose of why we are having 2 import for `java.util.List`

2023-09-28 19:22 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
> -import java.util.List;
Tests are weird on purpose. Checkstyle should work all compile able code, even this code is nonsense.

2023-09-29 16:31 UTC, romani approved these changes
Ok to merge

2023-10-02 18:09 UTC, merged