Issue #13797: Create a Checkstyle module to enforce comment formatting for input files
checkstyle/checkstyle pull request #13803
Opened 2023-09-30 12:37 UTC by relentless-pursuit

Resolves #13797

2023-09-30 12:38 UTC, relentless-pursuit commented
I have just taken examples directory input files into consideration. Based on the review and feedback, we can expand the scope.

2023-09-30 13:19 UTC, romani commented
Please create one more commit to cause violation and show that it works.

2023-09-30 14:04 UTC, relentless-pursuit commented
> Please create one more commit to cause violation and show that it works.

There was logical error in the check. I have modified it and also deliberately modified one example file to be able to flag it. It worked in local. Will wait for the logs to fail.

2023-09-30 14:16 UTC, romani requested changes
Items

2023-09-30 14:16 UTC, romani commented on config/checkstyle-examples-checks.xml
> +    <property name="format" value="^//(ok|violation)"/>
Please squash this change to first commit.
Test commit should be only input changes

2023-09-30 19:18 UTC, romani commented
Here is example  second reviewer https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48164885/job/cb577eql5bf1eki5#L123

Please remove second commit

2023-10-01 15:26 UTC, relentless-pursuit commented
> Here is example second reviewer https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48164885/job/cb577eql5bf1eki5#L123
> 
> Please remove second commi

> Here is example second reviewer https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48164885/job/cb577eql5bf1eki5#L123
> 
> Please remove second commit

done

2023-10-01 15:30 UTC, romani approved these changes
Ok to merge

2023-10-02 22:26 UTC, nrmancuso approved these changes
Ok, it does not make sense to reuse module in `checkstyle-checks.xml`, since this limits us to only java files:

https://github.com/checkstyle/checkstyle/blob/58fdccf566a46b2ad4eea3987be3157d323bb3a8/config/checkstyle-checks.xml#L464-L471

We have other types of input that we might use this style of comment in, so let's keep this as a simple regexp match now and expand later as needed.

2023-10-02 22:27 UTC, merged