Issue #11163: Enforce Java file for FinalLocalVariable
checkstyle/checkstyle pull request #13827
Opened 2023-10-04 13:50 UTC by Rohanraj123

Part of #11163

2023-10-04 13:51 UTC, Rohanraj123 commented
Can we please put HacktoberFest accepted label over this PR. @romani

2023-10-05 04:27 UTC, romani approved these changes
Ok to merge

2023-10-05 16:01 UTC, rnveach requested changes
The commit of this PR is misleading.
> Enforce Java file for FinalLocalVariable

This sounds like the issues where we are converting TXT file in examples to Java files.

Please rename to `Issue #11163: Enforce file size for FinalLocalVariable`.

2023-10-05 16:01 UTC, rnveach commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFive.java
> +InputFinalLocalVariableFive table = new InputFinalLocalVariableFive(); // violation
Same.

2023-10-06 11:45 UTC, Rohanraj123 commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableTwo.java
> +final InputFinalLocalVariableTwo.InnerClass ic = new InputFinalLocalVariableTwo.InnerClass();
Done with the changes @rnveach Can you please review it once .

2023-10-07 16:44 UTC, rnveach approved these changes

2023-10-08 15:01 UTC, merged

2023-12-18 13:28 UTC, MauryanKansara commented
I'm working on NoEnumTrailingComma.

2023-12-18 16:23 UTC, romani commented
@MauryanKansara, please post this in issue, not a Pull Request.