Issue #13345: Enable example test for parameterassignment
checkstyle/checkstyle pull request #13824
Opened 2023-10-04 06:51 UTC by AayushSaini101

Related: https://github.com/checkstyle/checkstyle/issues/13345

2023-10-04 11:36 UTC, nrmancuso approved these changes

2023-10-04 14:36 UTC, rnveach requested changes

2023-10-04 14:36 UTC, rnveach commented on src/xdocs/checks/coding/parameterassignment.xml
> +
Remove extra blank lines that you added.

2023-10-04 14:36 UTC, rnveach commented on src/xdocs/checks/coding/parameterassignment.xml
> +    int b = a; // ok
same.

2023-10-04 16:49 UTC, rnveach commented
@AayushSaini101 Please also keep the number of commits in this PR as 1.

2023-10-05 05:45 UTC, AayushSaini101 commented
> @AayushSaini101 Please also keep the number of commits in this PR as 1.

Working on the fix

2023-10-08 05:42 UTC, AayushSaini101 commented
> @AayushSaini101 Please also keep the number of commits in this PR as 1.

Done

2023-10-08 15:46 UTC, romani commented
@AayushSaini101 , please fix CI

2023-10-08 16:26 UTC, AayushSaini101 commented
> @AayushSaini101 , please fix CI

Tried. Some failing reason due to the switching between the acccounts

2023-10-08 18:16 UTC, romani commented
Prage is failing, please pull latest master from us and rebase.

2023-10-08 18:16 UTC, rnveach requested changes
There is some issue with the PR with 133 changed files. We cannot merge until this is only showing your changes in GitHub.

In addition:
> The PR is based on a master that is 21 commit(s) old.
The max allowed is 10.

2023-10-08 18:23 UTC, AayushSaini101 commented
> There is some issue with the PR with 133 changed files. We cannot merge until this is only showing your changes in GitHub.
> 
> In addition:
> 
> > The PR is based on a master that is 21 commit(s) old.
> > The max allowed is 10.
> 
> https://github.com/checkstyle/checkstyle/wiki/PR-rules See 2 as that may help.

Can I open new PR I guess it would be better as I switched to single user

2023-10-08 18:39 UTC, rnveach commented
If you can't re-push to the original branch, then be welcome opening a new PR. Just ping us here on the new one.

2023-10-09 02:15 UTC, AayushSaini101 commented
> If you can't re-push to the original branch, then be welcome to open a new PR. Just ping us here on the new one.

Closing this PR Opening a new

2023-10-09 02:15 UTC, closed without merging