dependency: Updated Maven version in pom.xml
checkstyle/checkstyle pull request #13887
Opened 2023-10-14 17:15 UTC by suniti0804

Running maven with the current version 3.3.9 (as mentioned in pom.xml) results in the following error message - 

`[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.1.0:check-format (default) on project checkstyle: The plugin org.codehaus.mojo:xml-maven-plugin:1.1.0 requires Maven version 3.5.4 -> [Help 1]`

This PR updates the maven version from 3.3.9 to 3.5.4

2023-10-14 17:19 UTC, suniti0804 commented
@romani please add hacktoberfest-accepted tag

2023-10-14 17:32 UTC, rnveach requested changes
Missing documentation update.

> updates the maven version from 3.3.9 to 3.5.4

https://checkstyle.org/beginning_development.html
> Ensure that ... maven >= 3.3.9 are installed

What changed?

2023-10-14 17:40 UTC, rnveach commented
> What changed?

`xml-maven-plugin` upgraded their maven version as part of 1.1.0 .
https://github.com/mojohaus/xml-maven-plugin/commit/9ae4e72844780e18cc49bf2a63df5f8fea94f857

We upgraded this version 4 months ago.
https://github.com/checkstyle/checkstyle/commit/4a69ab7991ea831ac6f75a4219648dc3c3b34a44

We should add a CI item to check maven version compatibility.

2023-10-14 17:50 UTC, suniti0804 commented
<groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        
this plugin requires maven version of 3.5.4

2023-10-14 17:56 UTC, rnveach commented
Our version of `maven-enforcer-plugin` is 3.4.1, and it uses the same version of `enforcer` which specifies the maven version as `3.2.5`. So unless you are seeing this error, it may only be `xml-maven-plugin` that uses a newer version.

2023-10-15 13:05 UTC, suniti0804 commented
@rnveach can you please explain to me the cause of this error, this error led me to the conclusion that we might need an update of the above mentioned group and artifcact id, i think i am mistaken here - 
`[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.1.0:check-format (default) on project checkstyle: The plugin org.codehaus.mojo:xml-maven-plugin:1.1.0 requires Maven version 3.5.4 -> [Help 1]`

2023-10-15 14:38 UTC, rnveach commented
My explanation of the cause of this error is at https://github.com/checkstyle/checkstyle/pull/13887#issuecomment-1763060926 .

Your post at https://github.com/checkstyle/checkstyle/pull/13887#issuecomment-1763063348 just mentions the wrong group/artifact.

What is left to be done is:
https://github.com/checkstyle/checkstyle/pull/13887#pullrequestreview-1678247981
> Missing documentation update.

And possibly:
https://github.com/checkstyle/checkstyle/pull/13887#issuecomment-1763060926
> We should add a CI item to check maven version compatibility.

2023-10-15 14:56 UTC, romani commented
my local:
```
$ mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/maven/apache-maven-3.8.4
Java version: 11.0.14.1, vendor: Amazon.com Inc., runtime: /opt/jvm/amazon-corretto-11.0.14.10.1-linux-x64
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-210-generic", arch: "amd64", family: "unix"
```

looks like we definitely need to update minimal version of maven.
Sad that non of CI jobs user a version that we declare in pom to report problem to us automatically

2023-10-15 14:59 UTC, romani commented
@suniti0804 , please update this line also:
https://github.com/checkstyle/checkstyle/blob/b1b25109068ae4aec1d7042ceb9756bc02118c42/src/xdocs/beginning_development.xml#L20

2023-10-16 06:27 UTC, suniti0804 commented
@romani all the changes requested in https://github.com/checkstyle/checkstyle/pull/13887#issuecomment-1763415671 are implemented

2023-10-16 13:37 UTC, romani approved these changes

2023-10-16 13:41 UTC, romani commented
Something weird is going on
https://app.travis-ci.com/github/checkstyle/checkstyle/builds/266600699#L198

2023-10-16 15:17 UTC, rnveach commented
CI is failing.

> so lets update version to 3.8.6 not a 3.5.4.

I would stick to the lowest maven we can use. That is the point of this in the documentation.

Besides, CI is saying not all CIs have the latest maven installed.

2023-10-17 09:56 UTC, suniti0804 commented
@romani on it

2023-11-22 14:07 UTC, romani requested changes
in this PR we just can update mvn versions in CI and merged PR.
actual update of min version will be done in scope of https://github.com/checkstyle/checkstyle/issues/13970
and updates in this PR will simplify a lot such future update.
 

items:

2023-11-22 14:07 UTC, romani commented on pom.xml
> +                  <version>3.8.6</version>
to unblock this PR, please revert this line.
it is blocked by https://github.com/checkstyle/checkstyle/issues/13970 and it is heavy lifting operation as you can see in related PRs.

we can merge all other changes meanwhile.

2023-11-22 14:07 UTC, romani commented on src/xdocs/beginning_development.xml
> +        1. Ensure that Git, Java JDK >= 11 until JDK 17, maven >= 3.8.6 are installed.<br/>
revert this change for now.

2023-11-22 14:07 UTC, romani commented on .travis.yml
> +  - "mvn -e --no-transfer-progress -N io.takari:maven:wrapper -Dmaven=3.8.6"
move to `install:`

2023-11-22 14:07 UTC, romani commented on .travis.yml
> +  - sudo apt install -y xmlstarlet
remove this line we have it in "install:"

2023-11-22 17:32 UTC, romani commented
After you addressed review item please reply "done" to explicitly show that you addressed this item in best way you understand it. I will review them and resolve if I agree.

CI are waiting please investigate and try to fix them.

2023-11-29 21:55 UTC, romani requested changes
items:

2023-11-29 21:55 UTC, romani commented on azure-pipelines.yml
> +      tar xzvf apache-maven-3.8.6-bin.tar.gz
lets use https://stackoverflow.com/a/52343639

2023-11-29 22:54 UTC, romani commented on azure-pipelines.yml
> +      tar xzvf apache-maven-3.8.6-bin.tar.gz
No need to update azure, it has latest - 3.8.8
https://github.com/checkstyle/checkstyle/pull/14078#issuecomment-1832825993
We are ok to run mvnw that is above min required.

2023-11-30 02:59 UTC, nrmancuso commented
@suniti0804 please resolve conflicts

2023-12-02 14:13 UTC, closed without merging