Issue #13345: Enable Type Name Check Example Test
checkstyle/checkstyle pull request #13978
Opened 2023-11-01 13:38 UTC by piyush-1234

Issue: #13345

2023-11-01 15:05 UTC, romani approved these changes
Ok to merge

2023-11-02 03:24 UTC, nrmancuso requested changes
Item:

2023-11-02 03:24 UTC, nrmancuso commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/Example1.java
> +class Example1{
```suggestion
class Example1 {
```

Please do this for all examples.

2023-11-02 07:41 UTC, piyush-1234 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/Example1.java
> +class Example1{
done

2023-11-06 15:16 UTC, merged