Issue #13809: Kill mutation in Tree-Walker
checkstyle/checkstyle pull request #13975
Opened 2023-10-31 19:51 UTC by Kevin222004

Issue #13809: Kill mutation in Tree-Walker

Test added

2023-10-31 22:48 UTC, romani requested changes
Goal of test is not clear if pitest diff not visible.

Item:

2023-10-31 22:48 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
> +    public void testMultiCheckOrder2() throws Exception {
testMultiCheckOfSameTypeNoIdResultsInOrderingByHash

2023-11-01 16:56 UTC, Kevin222004 commented on src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
> +    public void testMultiCheckOrder2() throws Exception {
done

2023-11-01 17:25 UTC, romani approved these changes
Ok to merge

2023-11-01 17:25 UTC, merged