Issue #6207: Added Xpath IT regression test for MagicNumber
checkstyle/checkstyle pull request #14029
Opened 2023-11-14 09:35 UTC by Rohanraj123

Part of #6207

2023-11-14 12:23 UTC, nrmancuso commented
@Rohanraj123 Please read https://github.com/checkstyle/checkstyle/issues/6207#issue-379425252 and do all that it requires.

2023-11-15 04:49 UTC, Rohanraj123 commented
> @Rohanraj123 Please read [#6207 (comment)](https://github.com/checkstyle/checkstyle/issues/6207#issue-379425252) and do all that it requires.

So as per my understanding yet , I only need to add a link of the documentation . Right? Else I think I have dont correctly @nrmancuso  Sir.

2023-11-15 05:16 UTC, romani commented
>XPath test must have 3 tests

Please add one more test

2023-11-15 11:07 UTC, nrmancuso commented
Check has one message: https://checkstyle.org/checks/coding/magicnumber.html#Violation_Messages

We should have one test.

2023-11-15 12:43 UTC, Rohanraj123 commented
> > XPath test must have 3 tests
> 
> Please add one more test

@romani Sir, Although its not necessarily required. It while mvn clean verify it says that two or more testcases are required for unit testing in Xpath. And i feel two tests are enough to test for magic number. But still if I can add one more test case. Please let me know.

2023-11-15 14:07 UTC, romani commented
@Rohanraj123 , thanks a lot for raising this unclear point, please do 3. I updated issue description.

2023-11-16 09:05 UTC, Rohanraj123 commented
> @Rohanraj123 , thanks a lot for raising this unclear point, please do 3. I updated issue description.

Sure !

2023-11-16 13:58 UTC, romani requested changes
items:

2023-11-18 08:20 UTC, Rohanraj123 commented on src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberAnotherVariable.java
> +    int a = 20; // warn
Added a test file with the pointers given by you @romani Sir.

2023-11-18 13:29 UTC, romani requested changes
item:

2023-11-18 13:29 UTC, romani commented on src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberAnotherVariable.java
> +            handleException(e);
make it: 
```
} catch(Exception e) {
        int a = 0;
        boolean someCondition = false;
        if (someCondition) {
            a = 1; // ok
        } else {
            a = 20; // warn
        }
```
to let generated xpath be long and complicated

2023-11-18 13:29 UTC, romani commented on src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberAnotherVariable.java
> +    private int performCalculation() throws Exception {
remove this method it does not contribute to generated xpath

2023-11-18 18:36 UTC, romani approved these changes
Ok to merge if ci pass

2023-11-18 19:36 UTC, merged