Issue #14019: Resolve pitest suppressions for ScopeUtil 2
checkstyle/checkstyle pull request #14030
Opened 2023-11-14 10:59 UTC by suniti0804

Issue #14019 

https://github.com/checkstyle/checkstyle/blob/3a23ae03d5f7cd3e59693017b5c971bb3d886770/config/pitest-suppressions/pitest-utils-suppressions.xml#L12-L19

2023-11-14 11:10 UTC, suniti0804 commented
Github, generate report

2023-11-14 11:14 UTC, suniti0804 commented
Github, generate report

2023-11-14 11:20 UTC, suniti0804 commented
Github, generate report

2023-11-14 11:22 UTC, suniti0804 commented
Github, generate report

2023-11-14 12:20 UTC, nrmancuso requested changes
@suniti0804 we need to add modules for all checks that use `ScopeUtil#getDeclaredScopeFromMods` to your regression report, and investigation/explanation of why it is safe to remove this condition.

2023-11-14 13:35 UTC, romani commented
example of explanation and report generaton - https://github.com/checkstyle/checkstyle/pull/13424

2023-11-16 06:55 UTC, suniti0804 commented
> @suniti0804 we need to add modules for all checks that use `ScopeUtil#getDeclaredScopeFromMods` to your regression report config, and investigation/explanation of why it is safe to remove this condition in the PR description.

@nrmancuso I updated the PR description accordingly, please check.

2023-11-16 10:57 UTC, nrmancuso commented
@suniti0804 Please attentively read https://github.com/checkstyle/checkstyle/pull/14030#pullrequestreview-1729610276. It is clear from your PR description that we have some misunderstanding about the work to do here.

Please take some time and read through  https://github.com/checkstyle/checkstyle/wiki/How-to-Generate-and-Analyze-Pitest-Reports, https://github.com/checkstyle/checkstyle/issues/12341#issue-1419918015, and the pitest documentation itself.

As far as your explanation goes, what you have stated is obvious from CI being green. We need to know WHY we cannot kill this mutation. Is some preceding condition making it impossible? What exactly my is the check looking for here? Debug this are of the code while executing done tests to deeply understand what is going on here.


However; it looks like we missed the very first step in https://github.com/checkstyle/checkstyle/issues/12341#issue-1419918015. We need to hard code this mutation to make sure that we even understand it correctly, then generate reports with all modules that use this method.

2023-11-17 16:19 UTC, romani commented
>Modules
DeclarationOrderCheck
JavadocVariableCheck
MissingJavadocMethodCheck
MissingJavadocTypeCheck
DesignForExtensionCheck

Please add them to diff config.

2023-11-17 16:23 UTC, romani commented
I agree with code removal as inside loop we always do break from loop  for each case and default.

As regression diff report is regenerated with usage of affected modules, we will be good to merge.

2023-11-21 14:33 UTC, suniti0804 commented
Github, generate report

2023-11-22 13:45 UTC, romani commented
Github, generate report

2023-11-22 15:03 UTC, suniti0804 commented
@romani Can you please let me know what changes you made in the PR description which enabled the generate report actions. When I tried last, it was failing. I need this information for my future PRs.

2023-11-25 12:56 UTC, nrmancuso approved these changes

2023-11-27 16:25 UTC, rnveach approved these changes

2023-11-27 16:25 UTC, merged