Issue checkstyle#13345: Enable EmptyCatchBlockCheckExamplesTest
checkstyle/checkstyle pull request #14043
Opened 2023-11-19 00:57 UTC by Kai0011

Part of #13345

2023-11-19 01:52 UTC, romani requested changes
items (apply to all)

2023-11-19 01:52 UTC, romani commented on src/xdocs/checks/blocks/emptycatchblock.xml
> +        } // ok
please remove all ` // ok` comments 
it is good to jave comeents like `// ok, catch block has comment` that has some explanation, but if no explanation then no comment is required.

2023-11-29 16:27 UTC, romani approved these changes
Ok to merge.
Violations are placed at right location, example5 is created due violation on filelenght for 60 lines

2023-11-30 02:33 UTC, nrmancuso approved these changes

2023-11-30 02:33 UTC, merged