Issue #6207: Added Xpath IT regression test for SuperClone
checkstyle/checkstyle pull request #14062
Opened 2023-11-24 18:23 UTC by Rohanraj123

part of #6207 

Documentation : [SuperClone](https://checkstyle.sourceforge.io/checks/coding/superclone.html#SuperClone)

2023-11-24 20:23 UTC, romani requested changes
Items

2023-11-24 20:23 UTC, romani commented on src/it/resources/org/checkstyle/suppressionxpathfilter/superclone/SuppressionXpathRegressionSuperCloneInnerClone.java
> +    {
This is same as SuppressionXpathRegressionSuperClonePlainAndSubclasses
Make this method to non clone to get violation in inner class

2023-11-25 13:33 UTC, romani approved these changes
Ok to merge, thanks a lot for contribution

2023-11-25 13:34 UTC, romani commented
Please fix CI failure https://app.circleci.com/pipelines/github/checkstyle/checkstyle/21996/workflows/846277a2-affd-4d24-944c-e86adc2f457b/jobs/436325/artifacts

2023-11-25 19:58 UTC, Rohanraj123 commented
> Please fix CI failure https://app.circleci.com/pipelines/github/checkstyle/checkstyle/21996/workflows/846277a2-affd-4d24-944c-e86adc2f457b/jobs/436325/artifacts

done !

2023-11-25 21:28 UTC, merged