Issue #6207: Added Xpath IT regression test for StaticVariableName
checkstyle/checkstyle pull request #14079
Opened 2023-11-30 07:36 UTC by aayushRedHat

Related: https://github.com/checkstyle/checkstyle/issues/6207

2023-11-30 09:02 UTC, aayushRedHat commented
Github, generate report

2023-11-30 11:54 UTC, nrmancuso requested changes
https://github.com/checkstyle/checkstyle/pull/14074#discussion_r1410096873

2023-12-06 05:37 UTC, aayushRedHat commented
> #14074 (comment)

@nrmancuso Added test cases

2023-12-06 06:26 UTC, romani requested changes
Small improvement

2023-12-06 06:26 UTC, romani commented on src/it/resources/org/checkstyle/suppressionxpathfilter/staticvariablename/SuppressionXpathRegressionStaticVariableName2.java
> +     protected static int NUM2; // warn
It is almost same as input1, please wrap this field in inners class to show violation on field of inner class.

2023-12-06 11:46 UTC, nrmancuso commented
> > #14074 (comment)
> 
> @nrmancuso Added test cases

Not done. We only need two test inputs, one with what is is the first test, one with what I suggest above (static field in local class).

2023-12-11 02:13 UTC, romani commented
@aayushRedHat, ping

2023-12-11 10:28 UTC, aayushRedHat commented
> @aayushRedHat, ping

Done @romani Sorry for being late

2023-12-11 11:35 UTC, nrmancuso approved these changes

2023-12-11 14:33 UTC, aayushRedHat commented
> from issue:
> 
> > There should be at least 3 test methods for different structure of code.
> 
> @aayushRedHat, please add one more .

Sure @romani

2023-12-11 16:40 UTC, romani requested changes
Items

2023-12-11 16:40 UTC, romani commented on src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionStaticVariableNameTest.java
> +                        "SuppressionXpathRegressionStaticVariableName1.java"));
Use second input file

2023-12-11 16:51 UTC, aayushRedHat commented on src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionStaticVariableNameTest.java
> +                        "SuppressionXpathRegressionStaticVariableName1.java"));
Done @romani

2023-12-12 02:42 UTC, romani approved these changes
Ok to merge, thanks a lot !!

2023-12-12 02:42 UTC, merged