minor: Rename static variable in UnusedLocalVar check to make more sense
checkstyle/checkstyle pull request #14090
Opened 2023-12-02 03:30 UTC by Vyom-Yadav

> Please rename this collection to something like `CLASS_BODY_DECLARATION_TOKENS`  or even `ANONYMOUS_INNER_CLASS_SCOPES` in a separate commit first, `container` is nonsense in this context. Then update the method naming, etc. appropriately.

_Originally posted by @nrmancuso in https://github.com/checkstyle/checkstyle/pull/13543#discussion_r1289084593_

2023-12-02 03:56 UTC, romani commented
Spelling

2023-12-02 04:00 UTC, Vyom-Yadav commented
> Spelling

Done

2023-12-09 17:36 UTC, nrmancuso requested changes
Item:

2023-12-09 17:36 UTC, nrmancuso commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
> +    private static final int[] TYPEDECL_BODY_DECLARATION_TOKENS = {
```suggestion
    private static final int[] ANONYMOUS_CLASS_PARENT_TOKENS = {
```
Please do this, we can avoid extension of spelling list, and this is more obvious in the context of a check.

2024-06-28 03:59 UTC, romani commented
Moved to https://github.com/checkstyle/checkstyle/pull/15158

2024-06-28 03:59 UTC, closed without merging