Issue: #14120 Add module-info.java
checkstyle/checkstyle pull request #14139
Opened 2023-12-13 10:24 UTC by future2r

I added a `module-info.java` file to the project. This makes the resulting jar a full-featured Java module. Use this as a starting point for your project transformation.

These problems need to be addresses:

1. Currently, all packages are exported. The assumption is all packages represent public API. In the end, you should only publish those packages that are required to be accessed from the outside of the module. All other packages should not be exported and are private API. You are then free to change the content of those packages without breaking the API. For this, you may need to revise the package structure and maybe move classes to private packages.

2. This module is open by default, allowing reflective access to all packages. In the end, you should only open those packages, that are indented for reflective access. Maybe there are none...?

3. None of your third-party dependencies are modularized yet. That is why you will get a lot of warnings. It is sad in 2023, because the modules are here since Java 9. Maybe you could start updating the dependencies to modularized versions or inform the maintainers, as I did with you.

4. Im am not yet sure, why the dependencies required by your test classes need to be added to the module. I guess your project setup is not correct. But this is beyond my current scope.

Welcome in the Java 9+ World. And on my side of the table... :-)

2023-12-14 07:06 UTC, future2r commented
If this works you should remove the `Automatic-Module-Name` from your `MANIFEST.MF` if still present.

2023-12-28 00:31 UTC, romani commented
`Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\projects\checkstyle\src\main\java\module-info.java`

We need to filter it out.
Strange that https://github.com/checkstyle/checkstyle/blob/7eac9b6858fd70627746f07cd433371e8f3304d9/config/checkstyle-checks.xml#L27 does not work

2023-12-28 00:50 UTC, romani requested changes
initial:

2023-12-28 00:50 UTC, romani commented on src/main/java/module-info.java
> +    exports com.puppycrawl.tools.checkstyle.site;
we need  to hide this package, same as doxia dependencies above. should we just not mention it in this file ?

2023-12-28 00:51 UTC, romani requested changes
same as above:

2023-12-28 00:51 UTC, romani commented on src/main/java/module-info.java
> +    requires transitive plexus.utils;
we need to hide this doxia/prlexus dependecies

2023-12-28 00:55 UTC, romani commented
>Im am not yet sure, why the dependencies required by your test classes need to be added to the module. I guess your project setup is not correct. But this is beyond my current scope

this is most likely due to site package that is used in test phase of maven that generates xml files. We need to find way to hide it, if possible.

2023-12-28 00:59 UTC, romani commented
i have failure on my local:
```
[INFO] --- maven-surefire-plugin:3.2.3:test (default-test) @ checkstyle ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests

ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.3:test (default-test) on project checkstyle: 
[ERROR] 
[ERROR] Please refer to /home/rivanov/java/github/romani/checkstyle/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1240)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1089)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:905)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

```

Warnings:
```
[INFO] --- maven-compiler-plugin:3.12.1:compile (default-compile) @ checkstyle ---
[WARNING] Can't extract module name from plexus-container-default-2.1.0.jar: plexus.container.default: Invalid module name: 'default' is not a Java identifier
[WARNING] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [commons-beanutils-1.9.4.jar, commons-logging-1.2.jar, jsr305-3.0.2.jar, ant-1.10.14.jar, Saxon-HE-12.4.jar, doxia-core-1.12.0.jar, doxia-sink-api-1.12.0.jar, plexus-utils-3.3.0.jar, plexus-component-annotations-2.1.0.jar, doxia-module-xdoc-1.12.0.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 448 source files with javac [debug target 11 module-path] to target/classes
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[41,32] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[42,32] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[43,41] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[44,30] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[45,28] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[47,30] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[48,37] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[49,35] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[50,41] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[51,31] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[52,25] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[53,35] requires transitive directive for an automatic module
[WARNING] /home/rivanov/java/github/romani/checkstyle/src/main/java/module-info.java:[54,25] requires transitive directive for an automatic module

```

2024-03-18 13:33 UTC, romani commented
@sgammon, please help to continue this PR, looks like original author do not have time to continue, he did good step forward.
By crowd sourcing we can do all steps to merge it, please help. Reuse code in this PR and create new PR.

2025-02-12 03:49 UTC, romani commented
@future2r , what good or bad you know about 
https://github.com/moditect/moditect
https://github.com/vavr-io/vavr/pull/2846/files

2025-02-12 09:23 UTC, sgammon commented
@romani Sorry, I just got your comment. I'm finishing up Guava's modularity so I'm happy to take this on as well.

2025-02-12 13:09 UTC, romani commented
@sgammon ,  we appreciate your help.

2025-03-15 01:51 UTC, sgammon commented
@romani This PR can be closed, yeah, and I can still work from it before filing mine, which should be forthcoming in the next week or so.

2025-03-15 14:39 UTC, romani commented
@sgammon , thanks a lot , let keep it open until you open new PR.

2025-06-12 08:31 UTC, closed without merging

2025-06-12 12:52 UTC, romani commented
@sgammon , did you have time to create new PR ?