Issue #11584: WriteTag reports violation with confusing message when …
checkstyle/checkstyle pull request #14153
Opened 2023-12-18 15:10 UTC by aayushRedHat

Related: https://github.com/checkstyle/checkstyle/issues/11584 

Diff regression config: https://gist.githubusercontent.com/strkkk/238b6c97492ff6ffdb3be1603deca8fc/raw/5db22461435a94c56a3f420be844cd07baf497f2/config_single_2.xml

2023-12-24 19:31 UTC, romani commented
GitHub, generate website

2023-12-27 02:28 UTC, romani requested changes
Items

2023-12-27 02:28 UTC, romani commented on src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/WriteTagCheck.xml
> + No violation reported in case there is no javadoc.
Please add to examples some method without javadoc, to make it very clear that there is no validation happening.

@aayushRedHat , it looks like this update is kind of breaking changes in behavior. Do you see what Checks should be used in addition to let users get behavior how it was before?

2024-01-29 06:02 UTC, nrmancuso commented
@aayushRedHat do you plan to continue to work on this PR?

2024-11-01 21:50 UTC, romani commented
@MohanadKh03, please help us to finish this PR.
Reuse code , create new PR and I hope we can have enough energy to merge your PR.

2024-11-02 00:01 UTC, romani commented
Will be done at https://github.com/checkstyle/checkstyle/pull/15844

2024-11-02 00:01 UTC, closed without merging