Issue #13086: InnerAssignmentCheck failed for one line code in Java 1…
checkstyle/checkstyle pull request #14150
Opened 2023-12-16 07:28 UTC by aayushRedHat

Related: https://github.com/checkstyle/checkstyle/issues/13086
Diff Regression config: https://gist.githubusercontent.com/aayushRedHat/7197864ed054dca9580c0cc8c441c1fd/raw/ae6d36be203f1228e0dbb013941c8a29ce6427b6/gistfile1.txt

2023-12-16 07:28 UTC, aayushRedHat commented
Github, generate report

2023-12-20 04:27 UTC, nrmancuso commented
Let's get hanging PRs across the finish line before we begin review here: https://github.com/checkstyle/checkstyle/pulls/aayushRedhat

2023-12-23 05:10 UTC, aayushRedHat commented
> Let's get hanging PRs across the finish line before we begin review here: https://github.com/checkstyle/checkstyle/pulls/aayushRedhat

Please review @nrmancuso @romani

2023-12-24 16:55 UTC, romani approved these changes
ok to merge, report is good

2023-12-24 23:07 UTC, rnveach requested changes

2023-12-24 23:07 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
> +        {TokenTypes.EXPR, TokenTypes.SWITCH_RULE},
I don't see it being asked anywhere, but why are we damaging lambda expression by removing them from this list?

https://github.com/checkstyle/checkstyle/commit/f798a441fcd58c890ca44b0cf276bca5752b10e2
https://github.com/checkstyle/checkstyle/issues/377

2023-12-24 23:09 UTC, rnveach approved these changes
Nevermind, I thought this was a swap, but  I see it is an addition.

As a note, no test case was ever added for https://github.com/checkstyle/checkstyle/issues/377 .

2023-12-27 02:19 UTC, nrmancuso requested changes
Item:

2023-12-27 02:19 UTC, nrmancuso commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentWithEnhancedSwitch.java
> +public class InputInnerAssignmentWithEnhancedSwitch {
Please add more test cases:
```
    void m1(final String operation) {
        boolean innerFlag;
        innerFlag = switch (operation) {
            case "Y" -> flag = true; // expected violation
            case "N" -> {
                yield flag = false; // expected violation
            }
            default -> throw new UnsupportedOperationException();
        };
    }

    void m2(final String operation) {
        boolean innerFlag;
        switch (operation) {
            case "Y": flag = true; break; // should be ok
            case "N": {
                flag = false; // should be ok
                break;
            }
            default: throw new UnsupportedOperationException();
        }
    }
```

2024-01-02 04:29 UTC, nrmancuso commented
@aayushRedHat ping

2024-01-02 16:56 UTC, aayushRedHat commented
> @aayushRedHat ping

Sorry @nrmancuso @romani for the delay in my PR. I was on Holidays, will start working tomorrow.

2024-04-16 16:07 UTC, nrmancuso commented
We lost contact with PR author, anyone is welcome to pick this up and reuse the code here

2024-04-16 16:07 UTC, closed without merging