Issue #13345: Enable HideUtilityClassConstructorCheckExamplesTest
checkstyle/checkstyle pull request #14174
Opened 2023-12-22 10:02 UTC by andreiyusupau

Issue: #13345 
Enabled HideUtilityClassConstructorCheckExamplesTest.
Replaced its Example.txt with Example.java.
Added expected violations to test.

2023-12-22 17:21 UTC, romani commented
Before pushing to GitHub, please make sure `mvn verify ` on your local pass.

2023-12-23 19:54 UTC, andreiyusupau commented
@romani How such errors should be fixed? The comment of violation should match violation description, so it cannot be shortened. Moving comment to another line didn't help.
`[ERROR] [checkstyle] [ERROR] \checkstyle\src\xdocs-examples\resources\com\puppycrawl\tools\checkstyle\checks\design\hideutilityclassconstructor\Example1.java:12: Line is longer than 85 characters (found 96). [LineLength]`
The line itself:
`class Example1 { // violation, 'Utility classes should not have a public or default constructor'`

And by the way is there some kind of predefined IDE settings (Intellij IDEA) for custom codestyle used in project? Haven't find one

2023-12-24 01:31 UTC, romani commented
`class Example1 { // violation, 'should not have a public or default constructor'`

Message is regexp, so numerous ways to shorten it.

All that we have is https://checkstyle.org/beginning_development.html#Starting_Development

You can move violation line above and below. Search in project `// violation above` there are numerous examples

2024-01-29 06:01 UTC, nrmancuso requested changes
@andreiyusupau looks like we lost track of this PR, apologies. Do not be afraid to ping maintainers for review after a few days.

Why did we go from one example to four?

2024-02-01 09:01 UTC, andreiyusupau commented
> @andreiyusupau looks like we lost track of this PR, apologies. Do not be afraid to ping maintainers for review after a few days.
> 
> Why did we go from one example to four?

Short answer - because current example didn't compile. 
Long - because it is not possible to have static fields in non-public classes (and it's impossible to have multiple public classes in one file).

2024-02-02 17:04 UTC, romani commented
GitHub, generate website

2024-02-02 17:22 UTC, nrmancuso commented
> Short answer - because current example didn't compile.

Yes, this is expected in most cases.

> Long - because it is not possible to have static fields in non-public classes (and it's impossible to have multiple public classes in one file).

None of the classes in the original example were public, nor are the examples in this PR. 

We don't need multiple examples here.

2024-02-02 17:23 UTC, nrmancuso commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/Example1.java
> +  }
https://github.com/checkstyle/checkstyle/pull/14174#issuecomment-1924337405

2024-02-04 06:33 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/Example1.java
> +  }
@andreiyusupau, please share javac error that you run into

2024-06-09 17:13 UTC, romani commented
Already done in other PR https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckExamplesTest.java

2024-06-09 17:13 UTC, closed without merging