minor: remove token from ignore list that are present in google config
checkstyle/checkstyle pull request #14292
Opened 2024-01-18 13:55 UTC by romani

to be merged after https://github.com/checkstyle/checkstyle/pull/13991

2024-01-18 14:12 UTC, nrmancuso requested changes
Items:

2024-01-18 14:12 UTC, nrmancuso commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
>                  "NUM_DOUBLE", "NUM_FLOAT", "NUM_INT", "NUM_LONG", "IDENT",
```suggestion
                // numerical types should not be included
                "NUM_DOUBLE", "NUM_FLOAT", "NUM_INT", "NUM_LONG",
                // identitifiers are covered by other checks
                "IDENT",
```

2024-01-18 14:12 UTC, nrmancuso commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
> +                "TEXT_BLOCK_CONTENT")
Please wrap `)` to reduce future diff.

2024-01-31 14:29 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
> +                "TEXT_BLOCK_CONTENT")
done

2024-01-31 14:29 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
>                  "NUM_DOUBLE", "NUM_FLOAT", "NUM_INT", "NUM_LONG", "IDENT",
done

2024-01-31 14:33 UTC, nrmancuso approved these changes

2024-02-02 16:56 UTC, merged