Issue #6207: Enable XpathRegressionTest for ilegalTokenText
checkstyle/checkstyle pull request #14326
Opened 2024-01-22 00:33 UTC by Coding-Aliens

Issue #6207;
Traveling from HK to USA these days.
Three tests for the class, method and interface level

2024-01-22 20:55 UTC, romani approved these changes
Ok to merge

2024-01-22 20:56 UTC, romani requested changes
Please fix circle CI https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23080/workflows/8a67fb9d-f1a9-4daf-8028-d9663ed513a5/jobs/483359/artifacts

2024-01-23 01:26 UTC, Coding-Aliens commented
Problems fixed

2024-01-23 02:26 UTC, romani approved these changes

2024-01-23 02:27 UTC, merged