Issue #14516: Update TokenTypes.json to new AST format
checkstyle/checkstyle pull request #14564
Opened 2024-02-28 02:37 UTC by SteLeo1602

Issue: #14516 

Parameters.java used for conversion
```
public class Parameters {
    public void function(int start, int end) {

    }
}
```
Converted to AST using:
`java -jar checkstyle-10.13.0-all.jar -t Parameters.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'`

2024-02-28 03:25 UTC, romani commented
>Converted to AST using:

Please copy/share whole output of this command, to let us confirm that you have right tree

2024-02-28 07:14 UTC, romani requested changes
Items

2024-02-28 07:14 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * --PARAMETERS -&gt; PARAMETERS
Remove --

2024-03-03 19:31 UTC, SteLeo1602 commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * --PARAMETERS -&gt; PARAMETERS
Done

2024-03-03 21:24 UTC, romani approved these changes
Ok to merge

2024-03-03 21:24 UTC, merged