Issue #14436: Enforced naming convention on MagicNumberCheckTest
checkstyle/checkstyle pull request #14633
Opened 2024-03-09 10:23 UTC by Pinti0001

Issue #14436 

Enforced naming convention on MagicNumberCheckTest

2024-03-09 13:06 UTC, MANISH-K-07 reviewed
@Pinti0001 ,
Please do update all the input files and related test methods of this module.

> Each PR must contain one complete module with all existing filenames and test method names analysed and renamed.
> In update, naming should be such that, just by looking at the names, anyone can figure out what the test validates from input file without even having to open it.

You can go through the issue #14436 description again.
It is recommended to pick one module and work on it completely. This helps to avoid confusion for future contributors who happen to pick  the same module if it is merged half done.

2024-03-09 13:55 UTC, Pinti0001 commented
> @Pinti0001 , Please do update all the input files and related test methods of this module.
> 
> > Each PR must contain one complete module with all existing filenames and test method names analysed and renamed.
> > In update, naming should be such that, just by looking at the names, anyone can figure out what the test validates from input file without even having to open it.
> 
> You can go through the issue #14436 description again. It is recommended to pick one module and work on it completely. This helps to avoid confusion for future contributors who happen to pick the same module if it is merged half done.

ok @MANISH-K-07  got it I am trying to complete module

2024-03-10 18:15 UTC, Pinti0001 commented
Hey @romani  @MANISH-K-07  can you check that is name correct or not....

2024-03-11 08:47 UTC, MANISH-K-07 commented
Why haven't the Checkstyle pipelines workflow run here ? 🙄

2024-03-11 09:25 UTC, Pinti0001 commented
I was also surprised to see this,
I never saw anything like this before.

2024-03-12 13:32 UTC, romani requested changes
items:

2024-03-12 13:32 UTC, romani commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberCheckIgnoreFieldDeclarationRecords.java
> +public class InputMagicNumberCheckIgnoreFieldDeclarationRecords {
`Check` should be required, it is implied. let keep name shorted

2024-03-14 04:58 UTC, romani commented
I am really sorry, we are cancelling this issue.

2024-03-14 04:58 UTC, closed without merging