Issue #13494: Redirects checks 404 error page to index.html
checkstyle/checkstyle pull request #14667
Opened 2024-03-16 15:18 UTC by MANISH-K-07

Part of #13494 

I have added an `index.html` file that is theoretically supposed to redirect to a custom set url.
The redirecting url has been set to https://checkstyle.org/checks.html from root.

The file added is very basic boiler plate with just a title and redirection link. If this works, we can add viewport, canonical link (for SEO), and anything else if required.

2024-03-16 15:43 UTC, rnveach requested changes
> If this works

You need to test it on your local and confirm it works. We shouldn't be merging something which is untested.

2024-03-16 15:43 UTC, rnveach commented on src/xdocs/checks/index.html
> +  <meta http-equiv="refresh" content="0; URL=https://checkstyle.org/checks.html" />
=> `<meta http-equiv="refresh" content="0; URL=../checks.html" />`

This has to work from our versioned documentation.
See https://checkstyle.org/#Previous_Version_Documentation

2024-03-16 15:49 UTC, MANISH-K-07 commented
> You need to test it on your local and confirm it works.

@rnveach , thanks for the reply.
I am not entirely sure how I can generate website from local. **_Could you please point me to some source that I can refer to ?_** 
I tried our wiki pages, did I miss a page related to this ?

2024-03-16 15:52 UTC, rnveach commented
https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only

2024-03-17 02:54 UTC, romani commented
Share a video of redirection in Chrome, Firefox.

2024-03-17 02:55 UTC, romani commented
GitHub, generate website

2024-03-17 02:55 UTC, romani commented
We should have website from GitHub bot

2024-03-17 03:24 UTC, MANISH-K-07 commented
Looks like the client is parsing file content as xml instead of html. I will try to debug the http response and get back

2024-03-17 03:45 UTC, rnveach commented
From https://github.com/checkstyle/checkstyle/pull/14667#issuecomment-2002289019
> https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ded61f8_2024030159/src/xdocs/checks/index.html.html#

GitHub looks to be providing an invalid URL. `.html` is duplicated twice.

2024-03-17 03:52 UTC, MANISH-K-07 commented
GitHub, generate website

2024-03-19 03:17 UTC, MANISH-K-07 commented
@rnveach , @romani ,
The index file seems just fine and also the url has no issues. 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>K3NWAR422HTA16F0</RequestId>
<HostId>B/XnoRlbQzYpwQlLdPsnLz16XvXQFlapTAB2MQ9waa/vPstra+lSe2bionUcqX/YrE3EHZrClNk=</HostId>
</Error>
```
Could this error be from the other end and not from my side ?

2024-03-19 13:34 UTC, romani commented
generate website on local and share sources of it your github.io to let us see that index.html is generated in required path.

2024-03-19 16:18 UTC, MANISH-K-07 commented
> generate website on local and share sources of it your github.io to let us see that index.html is generated in required path.

@romani , I am relatively bit new to this part of our project. I have pushed the generated index file but all the links seem broken

https://manish-k-07.github.io/

2024-03-19 16:34 UTC, rnveach commented
> https://github.com/MANISH-K-07/MANISH-K-07.github.io

Your github.io has only 1 file in it. It needs to have all the files generated by the site command.

2024-03-19 17:45 UTC, rnveach commented
> However, https://manish-k-07.github.io/checks/ is giving 404 instead of "Access denied" like in branch 

https://github.com/MANISH-K-07/MANISH-K-07.github.io/tree/main/checks
There is no index file here.

2024-03-20 00:23 UTC, MANISH-K-07 commented
> https://github.com/MANISH-K-07/MANISH-K-07.github.io/tree/main/checks There is no index file here.

I'm not sure yet why index isn't getting generated. However, the redirection plate I added works.
For testing, I manually inserted the file in my github.io and then the page is getting redirected as expected.
Please see https://manish-k-07.github.io/checks/ redirects to https://checkstyle.org/checks

@rnveach , I will try to figure out why we are missing index while generating site. But as a completely different thought, could we simply insert this file at https://github.com/checkstyle/checkstyle.github.io/tree/master/checks or will it get overridden during every release by gh bot ?

2024-03-20 01:54 UTC, rnveach commented
My current thought right now is it is missing because it is not a doxia file. All other files are VM or XML files. I think you might need to research doxia and figure out how to play nice and integrate with.

As for manually injecting into the github.io , I believe you are correct it will go missing. I am sure we erase and copy over new files each release. All our release scripts are in GH too. I currently don't feel we should make an override for just this one purpose yet, not while doxia is not investigated.
https://github.com/checkstyle/checkstyle/blob/master/.ci/release-update-github-io.sh#L18

I am going to mark this PR until it is investigated more.

2024-03-20 02:44 UTC, MANISH-K-07 commented
@rnveach , Sure I will try to dive into doxia.
A small clarification please ,

> Which is shouldn't as my review indicated above just to be clear.

I don't understand this part. The primary goal of this issue as you have mentioned in https://github.com/checkstyle/checkstyle/issues/13494#issue-1830223378 was to redirect https://checkstyle.org/checks/ to https://checkstyle.org/checks.html. Isn't a similar thing happening with my github.io repo?

From https://github.com/checkstyle/checkstyle/pull/14667#discussion_r1527191076, for previous version docs, we are using sourceforge pages and not gh pages. So, isn't this a different issue as mentioned by @romani in https://github.com/checkstyle/checkstyle/issues/13494#issuecomment-1999633304 ?

Please correct me if I'm missing something here. I'm unable to properly understand your goal here

2024-03-20 14:59 UTC, MANISH-K-07 commented
> => `<meta http-equiv="refresh" content="0; URL=../checks.html" />`
> 
> This has to work from our versioned documentation. See https://checkstyle.org/#Previous_Version_Documentation

Got it now !!
I assumed you were asking for this same redirection to work from previous versioned docs too

> With the change I suggested, we will not be forced to an absolute URL and it will be a relative URL instead.

Yes, this I figured out :)

> However, I am fine with older versioned documentation pages not working and have this just be resolved

Doxia is new to me.. might need some time to come up with a fix. I will get back on this PR soon

2024-05-11 22:27 UTC, romani commented
GitHub, generate website

2024-05-12 04:45 UTC, romani commented
Html file is still not generating properly.

2024-11-21 13:53 UTC, romani commented
Activity is moved to https://github.com/checkstyle/checkstyle/pull/15949

2024-11-21 13:53 UTC, closed without merging