Issue #13345: Enable example tests for SingleLineJavadocCheckExamples…
checkstyle/checkstyle pull request #14871
Opened 2024-05-09 18:35 UTC by prathm3

Issue: #13345 

Enabled tests for SingleLineJavadocCheckExamplesTests.java

2024-05-09 22:19 UTC, romani commented
@prathm3, , please execute `mvn verify` on your local before pushing to PR.
If you have problems with execution of this command, please let us know, we can help.

2024-05-10 20:09 UTC, romani commented
We need this changes in commit https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=21400&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=1800

Just put in commit all that are changed on your local after mvn verify.

2024-05-11 08:02 UTC, prathm3 commented
@romani , thanks for the hint. Failed some checks with `Caused by: java.net.ConnectException: Network is unreachable (connect failed)`. I tried retriggering tests but same error is occurring. ( on local all tests are passing ). Do you think this issue is because of some changes ? ( I have seen some companies turn off some functionality ( jobs ) over weekends, is it same for check style ? )

2024-05-11 14:20 UTC, romani requested changes
items:

2024-05-11 14:20 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/singlelinejavadoc/Example1.java
> +  /** @see Math */ // violation
we have few possible messages from Check https://checkstyle.org/checks/javadoc/singlelinejavadoc.html#Violation_Messages
it is not clear which violation is here, please add message to this line `// violation 'some message'` message is regexp so you can provide only most meanigful part of original message

2024-06-15 03:32 UTC, romani commented
Moved to https://github.com/checkstyle/checkstyle/pull/14992

2024-06-15 03:32 UTC, closed without merging