Issue #13345: Enabled IllegalThrows example tests
checkstyle/checkstyle pull request #15132
Opened 2024-06-26 02:59 UTC by SteLeo1602

Issue: #13345

Enabled example tests for IllegalThrows check.

2024-06-26 03:06 UTC, SteLeo1602 commented
GitHub, generate website

2024-06-26 03:58 UTC, romani requested changes
All good, but on phone I need to scroll horizontally to see violations.
Please do me a favor:

2024-06-26 03:58 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/Example1.java
> +  public void func2() throws Exception {}
Apply to all: `void f2() throws Exception {}`
To make them horizontal short.

2024-06-27 02:04 UTC, romani commented
GitHub, generate website

2024-06-27 02:35 UTC, merged