doc: improved grammar, spelling, and punctuation
checkstyle/checkstyle pull request #15146
Opened 2024-06-27 04:10 UTC by SteLeo1602

Finished Pull Request #14730 which worked on improving grammar, spelling, and punctuation.

2024-06-27 04:13 UTC, SteLeo1602 commented
GitHub, generate website

2024-07-09 03:41 UTC, SteLeo1602 commented
@nrmancuso This is a reminder to review my changes in this pull request. It's been over a week and if I remember correctly, I should notify you after that period of time.

2024-07-11 13:45 UTC, nrmancuso commented
> @nrmancuso This is a reminder to review my changes in this pull request. It's been over a week and if I remember correctly, I should notify you after that period of time.

Sorry for the delay, and thank you for the reminder. We have been busy with GSOC, I will get to your PR in the next couple of days. I appreciate your patience, @SteLeo1602

2024-07-13 14:03 UTC, nrmancuso requested changes
First pass, thanks for removing the part about lazy maintainers:

2024-07-13 14:03 UTC, nrmancuso commented on src/xdocs/writingjavadocchecks.xml.vm
> +        to skip processing of javadocs with non-tight HTML, method
```suggestion
        to skip processing of javadocs with non-tight HTML, the <tt>acceptJavadocWithNonTightHtml</tt> method in 
```

2024-07-13 14:03 UTC, nrmancuso commented on src/xdocs/writingjavadocchecks.xml.vm
> +       Checkstyle GUI allows to show javadoc trees in java files. To run it, use
```suggestion
       The Checkstyle GUI provides us with a way to show javadoc trees in java files. To run it, use
```

2024-07-13 14:03 UTC, nrmancuso commented on src/xdocs/writingjavadocchecks.xml.vm
> +        As Java AST and Javadoc AST are not binded,
```suggestion
        As Java AST and Javadoc AST are not bound,
```

2024-07-13 14:04 UTC, nrmancuso commented
@SteLeo1602 this part of our documentation is wild, please feel free to remove unnecessary adjectives and anything that seems to wordy or not valuable.

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/beginning_development.xml
> +        Here you can find instructions on importing and debugging the project for IDEs:<br/>
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/config_system_properties.xml
> +          Imagine we want to define slightly different requirements for test sources
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/contributing.xml
> +        explanation in it. The Issue number has to be referenced in the git commit message,
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/contributing.xml
> +        We use a set of development tools that ensure that
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/contributing.xml
> +        The project is following a general maven layout and phases for its build.
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +              tag is not nested to this tag.
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +              2) Here is a correct version with open and closed HTML tags.
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        to skip processing of javadocs with non-tight HTML, method
Done

2024-07-15 04:24 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +       Checkstyle GUI allows to show javadoc trees in java files. To run it, use
Done

2024-07-15 04:25 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        As Java AST and Javadoc AST are not binded,
Done

2024-07-16 04:54 UTC, SteLeo1602 commented on src/xdocs/contributing.xml
> +        Check the results of the report in target/site/jacoco/index.html in project home folder.
Done

2024-07-16 04:54 UTC, SteLeo1602 commented on src/xdocs/index.xml.vm
>          <br/>
Done

2024-07-16 04:54 UTC, SteLeo1602 commented on src/xdocs/index.xml.vm
>          Current site contains documentation only for latest, released version.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/index.xml.vm
> +        if there are any problems with most recent JDKs.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/contributing.xml
> +        For the last step of verification, to ensure that everything works fine, please test
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +      format, therefore limitations apply.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +          to build nested ASTs that most Checks expect.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        In other words, if HTML tags are not closed Javadoc, grammar cannot determine content
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        Javadoc comment, because a ton of unclosed tags are used, etc.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        another abstract class and use another set of token types.
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
>          that start with Javadoc Identifier and parse them to Abstract Syntax Tree (AST).
Done

2024-07-16 04:55 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        newlines to the parse tree
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
>          comments, etc.
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        As you already know the Javadoc parse tree is a result of parsing the block comment.
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        You may need this block comment to check its position or something else in a java
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        definition AST you should access the java
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        HTML4 was made to just have a list of elements whose end tag is optional(omittable) and a
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
>          on updating Javadoc grammar to HTML5</a>)
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        If Checkstyle meets an unknown tag (for example HTML5 tag)
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        it doesn't fail and parses this tag as a
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        Just follow <a href="#Tight-HTML_rules">Tight-HTML rules</a> to make the
Done

2024-07-16 04:56 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        tag &lt;audio&gt;): <br/>
Done

2024-07-16 04:57 UTC, SteLeo1602 commented on src/xdocs/writingjavadocchecks.xml.vm
> +        Checkstyle to upgrade the parser.
Done

2024-07-16 13:42 UTC, nrmancuso approved these changes
Big improvement, thank you very much @SteLeo1602 !

2024-07-16 13:56 UTC, romani commented
Github, generate website

2024-07-16 13:59 UTC, romani approved these changes

2024-07-18 19:42 UTC, rnveach requested changes

2024-07-18 19:42 UTC, rnveach commented on src/xdocs/contributing.xml
> +          checkstyle-tester#checkstyle-tester">
404 error

2024-07-18 19:47 UTC, rnveach requested changes

2024-07-18 19:47 UTC, rnveach commented on src/xdocs/writingjavadocchecks.xml.vm
> +        <a href='https://github.com/checkstyle/checkstyle/issues/3332'/> for details.
1) Switch to double quotes
2) Why is this self closing? This means this link has no clickable text.

2024-07-18 20:17 UTC, merged

2024-07-18 20:17 UTC, romani commented
Oh, sorry, wrong PR....

2024-07-18 20:21 UTC, romani commented
@SteLeo1602 , please address review items in new PR.

@rnveach , please do more review on this PR , I will fix your points.
Sorry for merging, I thought I am on different PR.

2024-07-19 13:42 UTC, romani commented
@rnveach, I fixed your concerns - https://github.com/checkstyle/checkstyle/pull/15323 please review