Issue #14937: Migrated section 5.2.5 Non Constant Field Names to chapter wise testing
checkstyle/checkstyle pull request #15140
Opened 2024-06-26 16:56 UTC by Zopsss

#14937

2024-06-26 20:14 UTC, romani requested changes
Item

2024-06-26 20:14 UTC, romani commented on src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesBasic.java
> +    public int mPublic; // violation 'Member name 'mPublic' must match pattern .*.'
Remove trailing .*

2024-06-27 05:31 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesBasic.java
> +    public int mPublic; // violation 'Member name 'mPublic' must match pattern .*.'
done and conflicts resolved

2024-06-27 06:35 UTC, romani approved these changes
Ok to merge

2024-06-27 19:46 UTC, rdiachenko approved these changes
lgtm

2024-06-27 19:47 UTC, rdiachenko commented
@Zopsss please resolve conflicts

2024-06-28 12:12 UTC, romani approved these changes

2024-06-28 12:12 UTC, merged