Issue #15007: Add input file for instanceof operator in OperatorWrap
checkstyle/checkstyle pull request #15171
Opened 2024-06-29 12:18 UTC by mahfouz72

closes #15007

2024-06-29 12:19 UTC, mahfouz72 commented
github, generate site

2024-06-29 13:58 UTC, nrmancuso requested changes
Item:

2024-06-29 13:58 UTC, nrmancuso commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
Please add a variation on each method here where we correctly line wrap the `instanceof`. Example:
```
        if (o
              instanceof Integer i) {}


```

2024-06-29 14:27 UTC, mahfouz72 commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
done

2024-06-29 14:40 UTC, nrmancuso approved these changes

2024-06-30 00:31 UTC, rnveach requested changes

2024-06-30 00:31 UTC, rnveach commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
> + * <a href ="https://docs.oracle.com/javase/tutorial/java/nutsandbolts/opsummary.html">
Remove space before `=`.

2024-06-30 00:31 UTC, rnveach commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
> +option = (default)nl
Duplicate file with other option.

2024-06-30 09:46 UTC, mahfouz72 commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
> + * <a href ="https://docs.oracle.com/javase/tutorial/java/nutsandbolts/opsummary.html">
done

2024-06-30 09:47 UTC, mahfouz72 commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
> +option = (default)nl
done

2024-06-30 16:13 UTC, rnveach approved these changes

2024-06-30 16:16 UTC, merged