Issue #15214: Migrated section 3.4.2.1 Overloads: never split to whole config testing
checkstyle/checkstyle pull request #15216
Opened 2024-07-09 03:16 UTC by Zopsss

#15214

2024-07-09 04:01 UTC, romani requested changes
Apply to all

2024-07-09 04:01 UTC, romani commented on src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplitRecords.java
> +/** Testing. */
`/** Some javadoc. */`

2024-07-09 18:21 UTC, Zopsss commented on src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplitRecords.java
> +/** Testing. */
done

2024-07-09 18:45 UTC, Zopsss commented
failing CI: https://github.com/checkstyle/checkstyle/actions/runs/9862214638/job/27232334980?pr=15216

it is because the PR is referring to a closed issue, so no need to worry about it

2024-07-09 21:38 UTC, romani approved these changes
Ok to merge

2024-07-09 21:58 UTC, Zopsss commented
Strange why [Check no closed issue references / check_issues (pull_request)](https://github.com/checkstyle/checkstyle/actions/runs/9862214638/job/27239642089?pr=15216) is failing, PR is pointing to correct issue

2024-07-09 23:51 UTC, romani approved these changes
Ok to merge

2024-07-09 23:53 UTC, romani commented
Rebased by GitHub

2024-07-11 09:31 UTC, rdiachenko approved these changes
lgtm

2024-07-11 09:31 UTC, merged