Issue #15241: Reduce baseline execution time value
checkstyle/checkstyle pull request #15245
Opened 2024-07-13 02:33 UTC by mahfouz72

closes #15241 

new baseline comes from the average execution time after string template removal  https://github.com/checkstyle/checkstyle/pull/15212#issuecomment-2221074819

2024-07-13 03:02 UTC, rnveach approved these changes
If we don't want to forget to update this, we should abs the `DEVIATION_IN_SECONDS` so it can't be negative.

2024-07-13 03:36 UTC, romani approved these changes
@rnveach , gas good idea to enhance this script

2024-07-13 17:33 UTC, nrmancuso requested changes
Please do https://github.com/checkstyle/checkstyle/pull/15245#pullrequestreview-2176067278

2024-07-13 18:04 UTC, mahfouz72 commented
but we can  get negative percentage in normal circumstances it is an average time no guarantee that it will be always greater than the Baseline 

example: https://github.com/checkstyle/checkstyle/actions/runs/9910196565/job/27380011798?pr=15199

2024-07-13 19:34 UTC, rnveach commented
> we can get negative percentage in normal circumstances it is an average time so no guarantee that it will be always greater than the Baseline

Just like we can high positives in "normal" circumstances. We have no guarantees it will be within the threshold and won't randomly take longer for unexplained reasons. We could hit some PC lag for random reasons.

2024-07-13 19:36 UTC, rnveach commented
> example: https://github.com/checkstyle/checkstyle/actions/runs/9910196565/job/27380011798?pr=15199
> Difference is within the maximum allowed difference (-.8100%      <= 10%).

This actually proves we have no problems using abs normally. Even +0.81% (8/10s of a percentage) is still less than 10% and wouldn't falsely trigger.

2024-07-13 23:42 UTC, mahfouz72 commented
Make sense, I got it. After taking the abs value now it will trigger:
-  if it goes below the threshold on the negative side. An example of this would be the string template removal PR, performance improved so we go negative. (CI will be red so we need to decrease the baseline)
- if it goes above the threshold on the positive side. An example of this would be a syntax update PR that affects performance badly  (CI will be red so we need to redo PR to think about how to optimize parsing)

We will determine if it is case 1 or 2 based on the PR activity either removal or introducing syntax.

@nrmancuso @rnveach what do you feel about decreasing the threshold percentage for example from 10% to 7%

2024-07-14 00:04 UTC, rnveach commented
> what do you feel about decreasing the threshold percentage for example from 10% to 7%

I am not sure what analysis went into for creating these numbers. @nrmancuso was mostly incontrol of that.

I would like to know what the values have generally been. Like the average of the last 10-20 runs. If we can gather that from master runs (I assume this runs all the time), then we can use those as our basis. Your example showed <1%, so I wouldn't be too surpirsed if it could be low, however, we need to also take into account if we want to support local runs which could be faster and slower.

2024-07-14 00:07 UTC, mahfouz72 commented
`Failed to execute goal org.pitest:pitest-maven:1.16.1:mutationCoverage (default-cli) on project checkstyle: Execution default-cli of goal org.pitest:pitest-maven:1.16.1:mutationCoverage failed: Licence expired on 2024-06-13 and grace period ended.`

2024-07-14 00:23 UTC, romani commented
Let me contact them to renew

2024-07-14 00:33 UTC, mahfouz72 commented
Yes only pitest

2024-07-14 21:26 UTC, nrmancuso approved these changes

2024-07-14 21:27 UTC, merged