Issue #15218: formatted input file for section 4.8.5.3 methods and constructors annotations to follow google style guide rules
checkstyle/checkstyle pull request #15302
Opened 2024-07-17 18:33 UTC by Zopsss

#15218

2024-07-17 18:40 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java
> +  void test2() {}
@romani @rdiachenko

2024-07-18 14:20 UTC, romani commented on src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java
> +  void test2() {}
formatter is not opinionated, whatever it does, it does it.
if both code is valid by style guide, we should not raise violations.

as this chapter is about location of annotation, we should revert all changes about annotation location, all other formatting should stay.

2024-07-18 14:23 UTC, romani requested changes
only annoation location should be restored.
all other is good formatting - keep it.

2024-07-19 07:01 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java
> +  void test2() {}
done

2024-07-19 12:38 UTC, romani approved these changes
ok to merge

2024-07-19 18:13 UTC, rdiachenko approved these changes
lgtm

2024-07-19 18:13 UTC, merged