Issue #15214: migrated section 7.1.1 general form to whole config testing
checkstyle/checkstyle pull request #15387
Opened 2024-07-27 06:28 UTC by Zopsss

#15214

2024-07-27 15:47 UTC, romani requested changes
items

2024-07-27 17:49 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java
> +    /** warn. */
I did `valid javadoc.` and `invalid javadoc.` 

https://github.com/checkstyle/checkstyle/pull/15387#discussion_r1693978804 here you said to convert `valid.` to `valid javadoc.` so I thought for `warn` it should be `invalid javadoc.`

2024-07-27 17:50 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java
> +// violation 3 lines above 'Javadoc comment is placed in the wrong location.'
can't, it was  giving `// should be separated from above line`. Moved the violation msg to single line:

https://github.com/checkstyle/checkstyle/blob/46341423888e19e8db4dbde700251d6da13a154a/src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java#L1-L3

2024-07-27 17:51 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java
> +  /** {@inheritDoc}. */
nope, it wasn't required. removed it, my bad

2024-07-27 17:57 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java
> +/** valid. */
done

2024-07-27 18:37 UTC, romani approved these changes
Ok to merge

2024-07-28 09:54 UTC, rdiachenko approved these changes
lgtm

2024-07-28 09:54 UTC, merged