Issue #15338: updated coverage table for section 4.6.2, added blue tick for WhitespaceAround module and a message referencing to the issue
checkstyle/checkstyle pull request #15418
Opened 2024-08-01 18:08 UTC by Zopsss

#15338 

Updated coverage table for section 4.6.2 Horizontal whitespace, added blue tick for WhitespaceAround module and a message explaining the reason behind blue tick and also reference link of the issue.

2024-08-02 13:32 UTC, romani requested changes
commit should reference https://github.com/checkstyle/checkstyle/issues/15329
issue.

issue in commit prefix should mean fix for this issue.

2024-08-03 06:45 UTC, Zopsss commented
fixed @romani

2024-08-03 12:38 UTC, romani approved these changes
ok to merge

2024-08-03 19:17 UTC, rdiachenko approved these changes
lgtm

2024-08-03 19:17 UTC, rdiachenko commented
@Zopsss please fix ci

2024-08-03 20:16 UTC, merged