Issue #15449: partially excluded rule48 from google-java-format.sh
checkstyle/checkstyle pull request #15489
Opened 2024-08-12 17:13 UTC by Zopsss

#15449 

the grepped list became large in this PR. There were only few section under rule48 in which our config and formatter did not conflict. 

Most of the tests started failing after formatting the input files of them.

2024-08-12 17:15 UTC, Zopsss commented
not sure why CI is red: https://github.com/checkstyle/checkstyle/actions/runs/10356322188/job/28665930674?pr=15489

@romani

2024-08-12 19:53 UTC, romani requested changes
Please update spelling

2024-08-12 19:53 UTC, romani commented on .ci/google-java-format.sh
> +                + "InputMethodsAndConstructorsAnnotations.java" \
You missed `\` on previous line

2024-08-12 19:55 UTC, romani requested changes
Try

2024-08-12 19:55 UTC, romani commented on .ci/google-java-format.sh
> +    | grep -v "rule4861blockcommentstyle/InputCommentsIndentation*.java" \
`rule4861blockcommentstyle/InputCommentsIndentation.*.java`

2024-08-13 12:40 UTC, romani commented
I fixed shell command, line wrap will not work, we need to cut names by `.*`

2024-08-13 12:43 UTC, romani commented
to avoid problems with spelling, 
```
+++ .ci-temp/unknown.words	2024-08-13 12:40:12.893531624 +0000
@@ -810,2 +810,3 @@
 methodparampad
+methodsandconstructorsannota
 methodsandconstructorsannotations
EOF

```
we can cut by words `methodsandconstructors`

2024-08-13 12:43 UTC, romani approved these changes
ok to merge

2024-08-13 18:19 UTC, rdiachenko approved these changes
lgtm

2024-08-13 22:04 UTC, merged