Issue #15340: created InputFormatted file for section 3.3.2 No Line Wrapping
checkstyle/checkstyle pull request #15549
Opened 2024-08-23 11:31 UTC by Zopsss

#15340

2024-08-23 11:34 UTC, Zopsss reviewed
review:

2024-08-23 11:34 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapping.java
> +  PackageStatementTest packageStatementTest = new PackageStatementTest(); // ok
input had imported this class but never used it, it was imported to show that long import statements are allowed. So I just created an instance of this class for demo purpose

2024-08-23 11:34 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputFormattedNoLineWrapping.java
> +import com.google.checkstyle.test.chapter3filestructure.toolongpackagetotestcoveragegooglesjavastylerule.PackageStatementTest; // ok, long imports are allowed
If I this import statement was never used in the class then formatter would have removed it and we would miss and edge case, so I created an instance of it to test the edge case and maintain similarity between both input files

2024-08-23 12:11 UTC, Zopsss reviewed
review:

2024-08-23 12:11 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputFormattedNoLineWrapping.java
> +  PackageStatementTest packageStatementTest = new PackageStatementTest(); // ok
this class was imported to show that long imports are allowed. The import was unused and formatter would remove unused imports, so to catch this edge case I had to create and instance of this class.

2024-08-23 12:11 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapping.java
> +  PackageStatementTest packageStatementTest = new PackageStatementTest(); // ok
created instance in this file also, just to maintain similarity between both input files

2024-08-23 13:28 UTC, romani requested changes
item:

2024-08-23 15:51 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapping.java
> +  PackageStatementTest packageStatementTest = new PackageStatementTest(); // ok
done

2024-08-23 15:51 UTC, Zopsss commented on src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputFormattedNoLineWrapping.java
> +import com.google.checkstyle.test.chapter3filestructure.toolongpackagetotestcoveragegooglesjavastylerule.PackageStatementTest; // ok, long imports are allowed
done

2024-08-24 00:32 UTC, romani approved these changes
Ok to merge

2024-08-24 00:34 UTC, romani commented
CI failure can be ignored, unrelated.
We should fix it in separate PR.

2024-08-24 18:08 UTC, rdiachenko approved these changes
lgtm

2024-08-24 18:08 UTC, merged