Issue #15605: update description of TODO Check
checkstyle/checkstyle pull request #15618
Opened 2024-09-04 13:26 UTC by romani

#15605

2024-09-06 03:21 UTC, nrmancuso requested changes
Item:

2024-09-06 03:21 UTC, nrmancuso commented on src/xdocs/checks/misc/todocomment.xml
> +          case insensitive:
```suggestion
          To configure the check for comments that contain <code>TODO</code> and <code>FIXME</code>,
          case-insensitive:
```

2024-09-06 13:05 UTC, romani commented on src/xdocs/checks/misc/todocomment.xml
> +          case insensitive:
done

2024-09-06 13:05 UTC, romani commented
Github, generate website

2024-09-08 16:04 UTC, nrmancuso approved these changes

2024-09-08 16:05 UTC, merged