infra: fix regression-report.yml and add a new regression-report.sh
checkstyle/checkstyle pull request #15758
Opened 2024-10-09 11:39 UTC by relentless-pursuit

2024-10-09 11:48 UTC, relentless-pursuit commented
Tesing for the inputJavaFile: https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11254110878

2024-10-09 12:43 UTC, relentless-pursuit commented
Testing for generated configs with custom project list (e.g. RequireThis): https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11255188561

2024-10-09 13:24 UTC, romani requested changes
items:

2024-10-09 13:24 UTC, romani commented on .ci/regression-report.sh
> +#!/bin/bash
copy paste is too big.
![image](https://github.com/user-attachments/assets/30b28a51-a395-4464-a9f8-e5bbd78b69bf)

can we update diff-report.yml to expect different file name ?

2024-10-09 13:37 UTC, romani commented on .ci/regression-report.sh
> +#!/bin/bash
let copy from web file as is.

in  bash we will just get fist by extension (there supposed to be only one property file):
```
property_files=(*.properties)
PROPERTY_FILE=$({files[0]})

```

2024-10-09 13:39 UTC, romani commented on .ci/regression-report.sh
> +#!/bin/bash
please create separate PR to update old workflow, I understand that testing is complicated, I think we can merge this without pre-testing, we will test after merge.

2024-10-09 20:42 UTC, relentless-pursuit commented
As we move from `diff-report.yml` to `regression-report.yml` in an incremental manner, we saw that the entire structure of `regression-report.yml` was built with projects.properties from documentation to code. And, we have an update to use `projects.yml`. But, since checkstyle continues to use `diff-report.yml` still dependent on `project.properties`, we made changes to support both format as both the workflows use `diff-report.sh`. And, thereofre, we made a refactoring of `project.properites` to `projects.properties`. 

Merged PR: https://github.com/checkstyle/checkstyle/pull/15759
Runner: https://github.com/checkstyle/checkstyle/actions/runs/11262575457/job/31318677710

2024-10-09 20:44 UTC, romani commented
>As we move from diff-report.yml to regression-report.yml

Not yet, they will exist together for several months.
I expect no changes in readme.md

2024-10-09 21:08 UTC, romani commented on .ci/regression-report.sh
> +#!/bin/bash
Workaround at https://github.com/checkstyle/checkstyle/pull/15759

Resolved.

I will keep it "unresolved" in GitHub just to let others see reason easier

2024-10-09 22:28 UTC, relentless-pursuit commented
Testing for generated configs with default project list (e.g. AbstractClassName):https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11264005371/job/31323162613

2024-10-09 23:46 UTC, relentless-pursuit commented
@romani, testing is done.

2024-10-10 00:01 UTC, romani approved these changes
Ok to merge

2024-10-10 00:01 UTC, merged