Issue #9118: Add method parameters placement and alignment checks
checkstyle/checkstyle pull request #15773
Opened 2024-10-14 12:55 UTC by konopka

Fixes #9118

2024-10-20 19:47 UTC, romani commented
Did you consider contributing this Check to aevntu-checkstyle project?

2024-10-21 13:16 UTC, konopka commented
> Did you consider contributing this Check to aevntu-checkstyle project?

This one: https://github.com/sevntu-checkstyle/sevntu.checkstyle ? No I did not. Anyway, isn't it kind of dead with last release 2 years ago?

2024-10-21 22:13 UTC, romani commented
It is not dead.
I don't see any functional fix at https://github.com/sevntu-checkstyle/sevntu.checkstyle/commits/master/
So nothing to release for 2 years, ok :).

We keep a lot of Checks in it, to let people quickly get something to work and apply in their organization. It helps to iterate over design in few releases and not deal with breaking changes process, ... .

In main repository we are more demanding in clear design that other users should benefits also, so any hacks will not be allowed.

I will respond you on your design proposal next week.

2024-11-01 00:46 UTC, romani requested changes
Ok, let's start discussion on design.

Lets create separate issues for each Check and discuss names of check, names of parameters of checks, configs samples and behavior on exact java code.

2024-11-01 00:46 UTC, romani commented on config/checkstyle-checks.xml
> +    <module name="ParameterPlacement">
Placing two Checks in one PR will not work well.

ParameterAlignment
ParameterPlacement

Should be separated from each other and they should make sense independently.
If not planned to be independent, they should be combined.

2024-11-14 04:44 UTC, romani commented
I am closing this PR.
As we have no agreement in issue.
Even we agreed on something, each Check will be in separate PR.

2024-11-14 04:44 UTC, closed without merging