Issue #15689: Add JavadocParagraph violation message examples
checkstyle/checkstyle pull request #15826
Opened 2024-10-28 13:18 UTC by AmitKumarDeoghoria

### This PR addresses Issue #15689 

**Summary of changes:**

Added examples to illustrate each of the following violation messages such as:

> Redundant paragraph tag
> Unclosed HTML element
> Misplaced tag

2024-10-28 13:21 UTC, AmitKumarDeoghoria commented
Hey @romani added the PR. This is all I have done till now. Please have a look and let me know what more to do.

2024-10-28 15:22 UTC, romani commented
GitHub, generate website

2024-10-29 05:28 UTC, AmitKumarDeoghoria commented
Any feedback on this @romani ?

2024-10-29 12:48 UTC, romani commented
GitHub, generate website

2024-10-29 13:08 UTC, romani requested changes
this check has only 1 special property but we are going to have 8 Examples.
Is there way to cobine cases all in 1-2 examples.

Ideally we should have only two examples. default and `allowNewlineParagraph=false`

We do not have to make comments for Class only, we can put javadoc on Class properties and methods

Example on violateExecutionOnNonTightHtml we can skip, as all Javadoc checks has it.  

Lets try to show all checks violation on two Examples.

2024-10-29 13:08 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/Example5.java
> +/*xml
you added Example files but you did not add them to Test class and not to xdoc template file
https://github.com/checkstyle/checkstyle/blob/c256c10eea2e4f39c3206ab1f2a6bb31c1941f19/src/xdocs/checks/javadoc/javadocparagraph.xml.template#L53

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckExamplesTest.java

2024-10-29 15:22 UTC, romani commented
https://github.com/AmitKumarDeoghoria/AmitKumarDeoghoria-checkstyle

We have problem https://github.com/checkstyle/checkstyle/actions/runs/11574173278/job/32218712571#step:3:60

Please make fork from us as just 'checkstyle'. It will simplify collaboration to let bots to work.

2024-10-29 15:24 UTC, romani commented
I recommend to 
Black up such examples 
close this PR 
Drop fork with custom name
Make new fork, without changing name of repository 
Do PR again

2024-10-29 16:41 UTC, AmitKumarDeoghoria commented
ok doing it.

2024-10-29 16:41 UTC, closed without merging