Issue #13345: Enable examples tests for IllegalInstantiationCheck
checkstyle/checkstyle pull request #15887
Opened 2024-11-06 21:43 UTC by AmitKumarDeoghoria

### Title: Enable examples tests for  IllegalInstantiationCheck

**Related Issue: #13345** 

**Summary**
This pull request aims to enable example tests for the ** IllegalInstantiationCheck** in the project. The implementation focuses on ensuring that the  IllegalInstantiation checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

**Key Changes Made**

- Conversion of txt file to Java File
- Enable the test cases by adding expected violations in the expected array for all example tests
- Made corresponding changes in the xml and xml.template file

2024-11-06 21:45 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-06 22:31 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-06 23:11 UTC, romani commented
Can we copy code of Example3 to Example1 and Example2 to let the be the same by java code ?

2024-11-06 23:53 UTC, AmitKumarDeoghoria commented
I was thinking of doing the same. Done.

2024-11-06 23:53 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-07 00:58 UTC, romani requested changes
Items

2024-11-07 00:58 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/Example1.java
> +      <property name="classes"
Example1 must be default config.
All other configs are showing change in behavior after customization by properties

2024-11-07 00:59 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/Example1.java
> +      <property name="classes"
In my previous point I meant to copy example3 Java statements only.

2024-11-07 08:40 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-07 13:45 UTC, romani approved these changes
thanks a lot.

limitation of array is pretty weird, but lets not dig on this now.

2024-11-07 13:46 UTC, merged