Issue #13345: Enabled example tests for IllegalType
checkstyle/checkstyle pull request #15902
Opened 2024-11-09 19:21 UTC by akankshat05

For #13345

2024-11-09 19:47 UTC, romani commented
GitHub, generate website

2024-11-09 20:13 UTC, romani commented
please apply this patch https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=24539&view=logs&j=6a833393-c551-5000-0916-5000fd3b86e7&t=bdbbd129-77f0-5d73-ce7d-db58d34c8358&l=45
to let CI be green.

2024-11-09 21:01 UTC, romani requested changes
I confirm that examples are very big and complicated and I do not see easy way to make them simple.

the only items to improve:

2024-11-10 07:02 UTC, akankshat05 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example1.java
> +  }
Okay, I will make the change

2024-11-10 10:05 UTC, akankshat05 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example1.java
> +  }
Done

2024-11-10 10:05 UTC, akankshat05 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example5.java
> +        LITERAL_PROTECTED, LITERAL_STATIC"/>
Done

2024-11-10 14:16 UTC, romani approved these changes
thanks a lot .

ok to merge.

2024-11-10 14:16 UTC, merged