Issue #13345: Enable examples tests for NestedIfDepthCheck
checkstyle/checkstyle pull request #15910
Opened 2024-11-12 19:40 UTC by AmitKumarDeoghoria

### Title: Enable examples tests for NestedIfDepthCheck

**Related Issue: #13345** 

**Summary**
This pull request aims to enable example tests for the **NestedIfDepthCheck** in the project. The implementation focuses on ensuring that NestedIfDepth checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

**Key Changes Made**

- Conversion of txt file to Java File
- Enable the test cases by adding expected violations in the expected array for all example tests
- Made corresponding changes in the xml and xml.template file

2024-11-12 19:41 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-12 21:31 UTC, romani requested changes
Items

2024-11-13 04:12 UTC, AmitKumarDeoghoria commented
GitHub, generate website

2024-11-13 04:55 UTC, AmitKumarDeoghoria commented on src/xdocs/checks/coding/nestedifdepth.xml
> -          To configure the check to allow nesting depth 3:
Done

2024-11-13 05:08 UTC, romani approved these changes
Ok to merge.

Thanks a lot

2024-11-13 05:08 UTC, merged