Issue #15456: Specify violation messages for SealedShouldHavePermitsListCheck
checkstyle/checkstyle pull request #15919
Opened 2024-11-14 09:16 UTC by Mostafahassen1

Issue #15456: Specify violation messages for SealedShouldHavePermitsListCheck

2024-11-14 12:18 UTC, romani requested changes
Item to improve:

2024-11-14 12:18 UTC, romani commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListInnerClass.java
> +    sealed class A {} // violation 'Sealed classes or interfaces should explicitly declare'
Please use last part of message to keep it more clear`'should explicitly declare permitted subclasses'`

2024-11-15 15:47 UTC, Mostafahassen1 reviewed
I finished from update

2024-11-15 16:52 UTC, romani approved these changes
Thanks a lot, please do more contributions

2024-11-15 16:52 UTC, merged