Issue #14019: Kill mutation in SuppressWithNearbyTextFilter
checkstyle/checkstyle pull request #15941
Opened 2024-11-18 17:58 UTC by akankshat05

For #14019 
Removed suppressions:
```
  <mutation unstable="false">
    <sourceFile>SuppressWithNearbyTextFilter.java</sourceFile>
    <mutatedClass>com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter</mutatedClass>
    <mutatedMethod>accept</mutatedMethod>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
    <description>removed call to java/lang/String::equals</description>
    <lineContent>if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {</lineContent>
  </mutation>

  <mutation unstable="false">
    <sourceFile>SuppressWithNearbyTextFilter.java</sourceFile>
    <mutatedClass>com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter</mutatedClass>
    <mutatedMethod>accept</mutatedMethod>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF</mutator>
    <description>removed conditional - replaced equality check with true</description>
    <lineContent>if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {</lineContent>
  </mutation>
```
**Steps followed to kill mutation**

-  Removed suppression from `pitest-filters-suppressions.xml`
- Listed pitest profiles with `groovy .ci/pitest-survival-check-xml.groovy --list` using java 11 and groovy 2.4.5
- Picked up `pitest-filters` as active profile
- Generated report locally using `mvn -e --no-transfer-progress -P"$PITEST_PROFILE" clean test-compile org.pitest:pitest-maven:mutationCoverage`
- Screenshots:
![before-result1](https://github.com/user-attachments/assets/a48f6ec8-7c00-4f1b-a1d1-f07d4cd153bb)

![before-result2](https://github.com/user-attachments/assets/33e8fc65-6a5f-42d7-b5dd-09a112113143)

- Analyzed report locally with `groovy .ci/pitest-survival-check-xml.groovy "$PITEST_PROFILE"`. 
Response:
```
New surviving mutation(s) found:

Source File: "SuppressWithNearbyTextFilter.java"
Class: "com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter"
Method: "accept"
Line Contents: "if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {"
Mutator: "org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator"
Description: "removed call to java/lang/String::equals"
Line Number: 198

Source File: "SuppressWithNearbyTextFilter.java"
Class: "com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyTextFilter"
Method: "accept"
Line Contents: "if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath)) {"
Mutator: "org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_IF"
Description: "removed conditional - replaced equality check with true"
Line Number: 198
```
- Added new test case
- Generated report again
- Screenshots:

![after-result1](https://github.com/user-attachments/assets/f73d3fbf-5a8b-4173-9678-d73f5c388070)

![after-result2](https://github.com/user-attachments/assets/16f5f5ae-dde8-4c04-a8b3-1f3a874708cc)

- Report analysis `No new surviving mutation(s) found.`

2024-11-19 17:15 UTC, akankshat05 commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
> +     * unchanged and validates a single call to retrieve file text.
Okay, I will update the test.

2024-11-20 01:58 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
> +     * unchanged and validates a single call to retrieve file text.
Look at examples of internal testing modules https://github.com/checkstyle/checkstyle/tree/master/src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules

2024-11-21 01:45 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
> +     * unchanged and validates a single call to retrieve file text.
Just FYI, is case you think we are crazy to not use mocks https://testing.googleblog.com/2024/02/increase-test-fidelity-by-avoiding-mocks.html

2024-11-26 19:56 UTC, romani requested changes
Items

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
> +                        && !path.contains(File.separatorChar + "filters" + File.separatorChar)) {
Please revert this.
We can put internal test input to existing folder "internal".

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/utils/FileRemovalFilter.java
> +
Please put it under "internal"

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/utils/FileRemovalFilter.java
> +public final class FileRemovalFilter implements Filter {
FileRemovalAfterFirstUsageFilter

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/utils/FileRemovalFilter.java
> +    private final AtomicInteger violationCount = new AtomicInteger(0);
`boolean isUsed`

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/utils/FileRemovalFilter.java
> +        if (currentCount == 2) {
If not used them delete.

2024-11-26 19:56 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
> +        final AuditEvent dummyEvent2 = buildDummyAuditEvent(tempInputFile.getPath());
Nothing dummy.

Please use Input file.

2024-11-29 14:51 UTC, romani requested changes
please always reply to each review item as "done" or any disagreement or comments.
it help a lot.

2024-11-29 14:51 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
> +        targetFilter.accept(auditEvent1);
one more time: test method should use Input files with config inside of it.
https://github.com/checkstyle/checkstyle/commit/2d5bfc110a7b81e76e5821b9e899e65a71b24a86#diff-0aa5d4351017b80ba94f82da4e00e2396e2db8a811918444878635c740400263R1401

test should use `verifyWithInlineConfigParser` method only.

location to register test module - https://github.com/checkstyle/checkstyle/commit/2d5bfc110a7b81e76e5821b9e899e65a71b24a86#diff-e7b107f6c9570fd3f500483f55b8bfb863cae9c96384f286d9a50be3ed4b725fR61

example of Input file https://github.com/checkstyle/checkstyle/commit/2d5bfc110a7b81e76e5821b9e899e65a71b24a86#diff-fa96fe0c65d2dd977a14acfbd8d38cebb470c9b1fff52d19e22801b2d833120dR4

2024-12-16 16:27 UTC, romani commented
@akankshat05, ping.

2025-01-03 20:25 UTC, romani commented
we lost connection to contributor

2025-01-03 20:25 UTC, closed without merging

2025-02-20 18:17 UTC, zyadahmed commented
@romani   i have question about your statment  

> Filters executed in order of declaration, 

is that actually true in `FilterSet.java` because the storage of filters in    ` private final Set<Filter> filters = new HashSet<>();`
 and  HashSet does not guarantee order, so wouldn’t we need a List to ensure the execution order you mentioned? Is my understanding correct, or am I missing something?

2025-02-20 21:46 UTC, romani commented
Looks like not:), thanks for pointing on this.

2025-02-20 22:11 UTC, zyadahmed commented
> Looks like not:), thanks for pointing on this. Let's keep Set to avoid easy relying on order.

 with set that solution will not work  what about using LinkedHashSet it will not change alot but we can ensure the order

2025-02-20 22:19 UTC, romani commented
Please create new PR, let's discuss it from scratch

2025-02-20 22:24 UTC, zyadahmed commented
> Please create new PR, let's discuss it from scratch

i am trying to solve problem with LinkedhashSet  and verifyWithInlineXmlConfig  to make working pr to discuss the issue  but i have several problem

2025-02-20 22:29 UTC, romani commented
Please create PR with what you have, and we will discuss and more clearly understand problems