Issue #15456: define violation message for UpperEll check
checkstyle/checkstyle pull request #15999
Opened 2024-12-04 16:37 UTC by mernaahmed2020

2024-12-05 13:07 UTC, mahfouz72 requested changes
The violation messages can be found [here](https://github.com/checkstyle/checkstyle/blob/b93ff886acf780c80e0f15630b69fd33db9af979/src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages.properties#L21C10-L21C36)

2024-12-05 13:07 UTC, mahfouz72 commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/upperell/InputUpperEllSemantic.java
> +    private static final long IGNORE = 666l + 666L; // violation: Using lowercase 'l' as a suffix for long literals can lead to confusion with the digit '1'. Use 'L' instead.
```suggestion
    private static final long IGNORE = 666l + 666L; // violation, Should use uppercase ''L''
```
  and you should do the same in the docs [Example](https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/upperell/Example1.java) file also files of UpperEl

2024-12-07 10:48 UTC, mahfouz72 commented
@mernaahmed2020 Single commit please and the commit message should reference the issue number (Same as you did in PR title)

2025-01-03 20:21 UTC, romani commented
we lost connection to contributor

2025-01-03 20:21 UTC, closed without merging