Issue #15939: false-positive for text-block-literal at indentation fix
checkstyle/checkstyle pull request #16058
Opened 2024-12-26 03:08 UTC by mohitsatr

resolves #15939 

WIP: to ask for directions

```xml
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">

    <property name="charset" value="UTF-8"/>

    <property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="SuppressWarningsFilter"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>

        <module name="Indentation">
            <property name="lineWrappingIndentation" value="4"/>
            <property name="forceStrictCondition" value="true"/>
        </module>
    </module>
</module>
```

```java
public class Test {
    private static final String EXAMPLE = """
                Example string
        EXample2
            example3
""";    
} 
```
```
java -jar checkstyle-10.21.1-SNAPSHOT-all.jar -c testconfig.xml Test.java
Starting audit...
Audit done.
```
this implementation completely ignores `TEXT_BLOCK_LITERAL_BEGIN/END/CONTENT`

2024-12-27 23:53 UTC, romani commented
@mohitsatr , please proceed with finishing this PR.
Direction is good, If you need some answer to your concerns please state them again, I can not spot them.

Just make CI pass, run regression diff report.

2024-12-28 02:41 UTC, mohitsatr commented
Github, generate report

2024-12-28 03:05 UTC, mohitsatr commented
Github, generate report for Indentation/all-examples-in-one

2024-12-28 04:08 UTC, romani commented
@mohitsatr , we expect only removal of violations, please investigate why they changed.

2024-12-28 04:49 UTC, mohitsatr commented
Github, generate report for Indentation/Example1

2024-12-28 06:02 UTC, romani commented
This is suspicious https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/f406eea9d33fe73dda1621f577f6d1af1fc90823_2024053241/reports/diff/checkstyle/index.html#A7 message changed.

Please add it to inputs

2024-12-30 04:45 UTC, mohitsatr commented
Github, generate report for Indentation/all-examples-in-one

2024-12-30 07:36 UTC, mohitsatr commented
save yourself from scrolling 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/openjdk21/index.html#A13191

2024-12-30 18:03 UTC, rnveach requested changes
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/apache-struts/index.html#A1
This is a false negative. Whitespaces on the end line of the text block are not part of the string and there is nothing visible before the end of the text block. It should be indented by this check because it is code and it starts the line.

https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5c0ac47fb19e4230fbb93ede0bc8fcd7ee8b33dd_2024061859/reports/diff/camunda/index.html#A3
Similar to this, but this is the start of the text block.

2024-12-30 18:59 UTC, romani commented
@mohitsatr , 

>This is a false negative

Please create new issue for this, it will be separate update. We need to remove false positives sooner.

2024-12-30 19:02 UTC, rnveach commented
There is no issue until this PR is merged. Better to fix it now then have this go out as a bad fix.

2024-12-30 22:08 UTC, romani commented
There is an issue https://github.com/checkstyle/checkstyle/issues/15939

So we do step back in support of it to ignore it completely, to avoid annoying users, next step will be to fix new issue with all details on how it should work, I think there will be discussion.

After this issue, users should rely on manual indentation for text blocks, or use formatter of their preferences.
As CS be ready to validate proper indentation, it will start to placing violation back such code. But a way more will be known on how it should be.

2024-12-31 00:55 UTC, rnveach commented
And there is a problem https://github.com/checkstyle/checkstyle/pull/16058#pullrequestreview-2525855058 .

Your replacing one issue for another and your "discussion" on this is creating a problem on something that doesn't exist. Nothing has been said this problem can't be fixed now or admins can't assist. It is better to provide a proper fix than a broken one.

2025-01-02 03:53 UTC, mohitsatr commented
Github, generate report for Indentation/all-examples-in-one

2025-01-02 03:56 UTC, rnveach commented
@mohitsatr Basically you should be verifying the text block starts the line to process it. If something is before the node, then we know it doesn't start the line.

You may want to look at https://github.com/checkstyle/checkstyle/blob/befb825a3127883f8c4bb8e3d4291259727a7ab4/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L177-L179 .

2025-01-03 01:56 UTC, mohitsatr commented
Github, generate report for Indentation/all-examples-in-one

2025-01-03 19:34 UTC, romani commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
> +                """); //indent:16 exp:12 warn
please out above or below "functionally same" code with correct indentation, to let clearly state what is expected form of indentation.

2025-01-04 02:58 UTC, mohitsatr commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
> +                """); //indent:16 exp:12 warn
done

2025-01-04 02:58 UTC, mohitsatr commented on src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
> +""";//indent:0 exp:8 warn
done

2025-01-04 03:29 UTC, mohitsatr commented
> Should we add this to xdoc examples? as handling of `"""` is very nuanced

I didn't understand this. are you asking whether we should mention how we are handling the logic for """(ending).

2025-01-04 03:29 UTC, mohitsatr commented
If the `TEXT-BLOCK-BEGIN` is in the `firstNodeOnLine` map, we can be certain it is the first node on the line. However, if the `TEXT-BLOCK-END` appears in the `firstNodeOnLine`, we cannot be sure that it is the first node on the line.

The `firstNodeOnLine` hashmap is specifically designed to store AST nodes that start a line. Ideally, the `TEXT-BLOCK-END` should be present in the `firstNodeOnLine` only if it starts the line. However, since text-blocks-literals can span multiple lines, the `TEXT-BLOCK-END` can bypass our current logic and end up in the `firstNodeOnLine`  without being verified as the first node on the line.

`shouldProcessTextBlockLiteral` method is responsible for checking whether `TEXT-BLOCK-END`  starts a line or not.

2025-01-04 03:51 UTC, romani commented
@mohitsatr , please fix CI failure

2025-01-04 03:57 UTC, mohitsatr commented
it is expecting some line terminator  :
```
error: illegal text block open delimiter sequence, missing line terminator
    private static final String EXAMPLE = """                 //indent:4 exp:4
```
?

2025-01-04 04:09 UTC, romani commented
Try to compile by jdk21

2025-01-04 04:14 UTC, romani commented
https://stackoverflow.com/a/57853218/1015848

2025-01-06 02:10 UTC, mohitsatr commented
> so some input files should be exceptional

how ? using suppression ?

2025-01-07 06:31 UTC, romani commented
No. Instead of `verifyWarns(` use regular `verify` method.

2025-01-14 06:18 UTC, mohitsatr commented
Github, generate report for Indentation/all-examples-in-one

2025-01-18 20:08 UTC, romani approved these changes
thanks a lot.

it is hard to review  all diff, but i  did spot checking for about 30 violations, no problems is found.

it is good step forward.

2025-01-19 08:30 UTC, nrmancuso commented
Let’s allow @rnveach to finish review since he left items above

2025-01-19 16:10 UTC, rnveach approved these changes

2025-01-25 12:59 UTC, nrmancuso approved these changes

2025-01-25 12:59 UTC, merged