Issue #14631: Updated code_literal in JavadocTokenTypes.java to new AST format
checkstyle/checkstyle pull request #16062
Opened 2024-12-27 08:55 UTC by ironfist-15

Issue :#14631

**Command Used:**
java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"

**Test.java**
```
/**
 *  Comparable&lt;E&gt;
 */
public class Test {
}

```

```
COMPILATION_UNIT -> COMPILATION_UNIT
`--CLASS_DEF -> CLASS_DEF
    |--MODIFIERS -> MODIFIERS
    |   |--BLOCK_COMMENT_BEGIN -> /*
    |   |   |--COMMENT_CONTENT -> *\r\n *  Comparable&lt;E&gt;\r\n
    |   |   |   `--JAVADOC -> JAVADOC
    |   |   |       |--NEWLINE -> \r\n
    |   |   |       |--LEADING_ASTERISK ->  *
    |   |   |       |--TEXT ->   Comparable&lt;E&gt;
    |   |   |       |--NEWLINE -> \r\n
    |   |   |       |--TEXT ->
    |   |   |       `--EOF -> <EOF>
    |   |   `--BLOCK_COMMENT_END -> */
    |   `--LITERAL_PUBLIC -> public
    |--LITERAL_CLASS -> class
    |--IDENT -> Test
    `--OBJBLOCK -> OBJBLOCK
        |--LCURLY -> {
        `--RCURLY -> }

```

2024-12-27 15:24 UTC, romani requested changes
items:

2024-12-27 15:24 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
> +     *         `--TEXT -&gt;
use lower case for tags "Code" --> "code".

tree should be like this.
```
    |   |   |       |--JAVADOC_TAG -> JAVADOC_TAG
    |   |   |       |   |--CUSTOM_NAME -> @Code
    |   |   |       |   |--WS ->
    |   |   |       |   `--DESCRIPTION -> DESCRIPTION
    |   |   |       |       |--TEXT -> Comparable&lt;E&gt;
```

2024-12-27 15:42 UTC, romani approved these changes
thanks a lot

2024-12-27 15:48 UTC, merged

2024-12-27 15:49 UTC, romani commented
@ironfist-15 , please be welcome with more contributions

2024-12-27 15:51 UTC, ironfist-15 commented
Sure . It was my first  open source contribution . I had a lot of fun :)

2024-12-28 14:25 UTC, Akshat-Dimri commented
@ironfist-15 can you guide me in this issue, i am a bit confused which command to use and how to implement this, i have cloned the repository successfully, how to proceed from there, just the basics ...

2024-12-28 14:54 UTC, ironfist-15 commented
@Akshat-Dimri  Sure. Watch these videos. It will help you 

https://youtube.com/playlist?list=PLHM9s_lN4X0hzOQ0sUmGdroxW0HfREAqj&si=ZA9CwqE1J5BO610q