Issue #16013: test to ensure alphabetical order at summary pages
checkstyle/checkstyle pull request #16096
Opened 2024-12-31 05:11 UTC by mohitsatr

resolves #16013

2024-12-31 05:13 UTC, mohitsatr commented
checks at https://checkstyle.org/checks.html are not in alphabetical order 
filter names at https://checkstyle.org/filters/index.html are not in alphabetical order 
Hence the failure.

2024-12-31 05:44 UTC, romani commented
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=25169&view=logs&jobId=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111

```
ERROR]   XdocsPagesTest.testAlphabetOrderAtIndexPages:428->validateOrder:459 Check Names must be in alphabetical order.
contents match, but order was wrong
expected: [AbbreviationAsWordInName, AbstractClassName, AnnotationLocation, AnnotationOnSameLine, AnnotationUseStyle, AnonInnerLength, ArrayTrailingComma, ArrayTypeStyle, AtclauseOrder, AvoidDoubleBraceInitialization, AvoidEscapedUnicodeCharacters, AvoidInlineConditionals, AvoidNestedBlocks, AvoidNoArgumentSuperConstructorCall, AvoidStarImport, AvoidStaticImport, BooleanExpressionComplexity, CatchParameterName, ClassDataAbstractionCoupling, ClassFanOutComplexity, ClassMemberImpliedModifier, ClassTypeParameterName, CommentsIndentation, ConstantName, ConstructorsDeclarationGrouping, CovariantEquals, CustomImportOrder, CyclomaticComplexity, DeclarationOrder, DefaultComesLast, DescendantToken, DesignForExtension, EmptyBlock, EmptyCatchBlock, EmptyForInitializerPad, EmptyForIteratorPad, EmptyLineSeparator, EmptyStatement, EqualsAvoidNull, EqualsHashCode, ExecutableStatementCount, ExplicitInitialization, FallThrough, FileLength, FileTabCharacter, FinalClass, FinalLocalVariable, FinalParameters, GenericWhitespace, Header, HiddenField, HideUtilityClassConstructor, IllegalCatch, IllegalIdentifierName, IllegalImport, IllegalInstantiation, IllegalThrows, IllegalToken, IllegalTokenText, IllegalType, ImportControl, ImportOrder, Indentation, InnerAssignment, InnerTypeLast, InterfaceIsType, InterfaceMemberImpliedModifier, InterfaceTypeParameterName, InvalidJavadocPosition, JavaNCSS, JavadocBlockTagLocation, JavadocContentLocation, JavadocLeadingAsteriskAlign, JavadocMethod, JavadocMissingLeadingAsterisk, JavadocMissingWhitespaceAfterAsterisk, JavadocPackage, JavadocParagraph, JavadocStyle, JavadocTagContinuationIndentation, JavadocType, JavadocVariable, LambdaBodyLength, LambdaParameterName, LeftCurly, LineLength, LocalFinalVariableName, LocalVariableName, MagicNumber, MatchXpath, MemberName, MethodCount, MethodLength, MethodName, MethodParamPad, MethodTypeParameterName, MissingCtor, MissingDeprecated, MissingJavadocMethod, MissingJavadocPackage, MissingJavadocType, MissingNullCaseInSwitch, MissingOverride, MissingSwitchDefault, ModifiedControlVariable, ModifierOrder, MultipleStringLiterals, MultipleVariableDeclarations, MutableException, NPathComplexity, NeedBraces, NestedForDepth, NestedIfDepth, NestedTryDepth, NewlineAtEndOfFile, NoArrayTrailingComma, NoClone, NoCodeInFile, NoEnumTrailingComma, NoFinalizer, NoLineWrap, NoWhitespaceAfter, NoWhitespaceBefore, NoWhitespaceBeforeCaseDefaultColon, NonEmptyAtclauseDescription, OneStatementPerLine, OneTopLevelClass, OperatorWrap, OrderedProperties, OuterTypeFilename, OuterTypeNumber, OverloadMethodsDeclarationOrder, PackageAnnotation, PackageDeclaration, PackageName, ParameterAssignment, ParameterName, ParameterNumber, ParenPad, PatternVariableName, RecordComponentName, RecordComponentNumber, RecordTypeParameterName, RedundantImport, RedundantModifier, Regexp, RegexpHeader, RegexpMultiline, RegexpOnFilename, RegexpSingleline, RegexpSinglelineJava, RequireEmptyLineBeforeBlockTagGroup, RequireThis, ReturnCount, RightCurly, SealedShouldHavePermitsList, SeparatorWrap, SimplifyBooleanExpression, SimplifyBooleanReturn, SingleLineJavadoc, SingleSpaceSeparator, StaticVariableName, StringLiteralEquality, SummaryJavadoc, SuperClone, SuperFinalize, SuppressWarnings, ThrowsCount, TodoComment, TrailingComment, Translation, TypeName, TypecastParenPad, UncommentedMain, UniqueProperties, UnnecessaryParentheses, UnnecessarySemicolonAfterOuterTypeDeclaration, UnnecessarySemicolonAfterTypeMemberDeclaration, UnnecessarySemicolonInEnumeration, UnnecessarySemicolonInTryWithResources, UnusedCatchParameterShouldBeUnnamed, UnusedImports, UnusedLambdaParameterShouldBeUnnamed, UnusedLocalVariable, UpperEll, VariableDeclarationUsageDistance, VisibilityModifier, WhenShouldBeUsed, WhitespaceAfter, WhitespaceAround, WriteTag]
but was : [AbbreviationAsWordInName, AbstractClassName, AnnotationLocation, AnnotationOnSameLine, AnnotationUseStyle, AnonInnerLength, ArrayTrailingComma, ArrayTypeStyle, AtclauseOrder, AvoidDoubleBraceInitialization, AvoidEscapedUnicodeCharacters, AvoidInlineConditionals, AvoidNestedBlocks, AvoidNoArgumentSuperConstructorCall, AvoidStarImport, AvoidStaticImport, BooleanExpressionComplexity, CatchParameterName, ClassDataAbstractionCoupling, ClassFanOutComplexity, ClassMemberImpliedModifier, ClassTypeParameterName, CommentsIndentation, ConstantName, ConstructorsDeclarationGrouping, CovariantEquals, CustomImportOrder, CyclomaticComplexity, DeclarationOrder, DefaultComesLast, DescendantToken, DesignForExtension, EmptyBlock, EmptyCatchBlock, EmptyForInitializerPad, EmptyForIteratorPad, EmptyLineSeparator, EmptyStatement, EqualsAvoidNull, EqualsHashCode, ExecutableStatementCount, ExplicitInitialization, FallThrough, FileLength, FileTabCharacter, FinalClass, FinalLocalVariable, FinalParameters, GenericWhitespace, Header, HiddenField, HideUtilityClassConstructor, IllegalCatch, IllegalIdentifierName, IllegalImport, IllegalInstantiation, IllegalThrows, IllegalToken, IllegalTokenText, IllegalType, ImportControl, ImportOrder, Indentation, InnerAssignment, InnerTypeLast, InterfaceIsType, InterfaceMemberImpliedModifier, InterfaceTypeParameterName, InvalidJavadocPosition, JavadocBlockTagLocation, JavadocContentLocation, JavadocLeadingAsteriskAlign, JavadocMethod, JavadocMissingLeadingAsterisk, JavadocMissingWhitespaceAfterAsterisk, JavadocPackage, JavadocParagraph, JavadocStyle, JavadocTagContinuationIndentation, JavadocType, JavadocVariable, JavaNCSS, LambdaBodyLength, LambdaParameterName, LeftCurly, LineLength, LocalFinalVariableName, LocalVariableName, MagicNumber, MatchXpath, MemberName, MethodCount, MethodLength, MethodName, MethodParamPad, MethodTypeParameterName, MissingCtor, MissingDeprecated, MissingJavadocMethod, MissingJavadocPackage, MissingJavadocType, MissingOverride, MissingNullCaseInSwitch, MissingSwitchDefault, ModifiedControlVariable, ModifierOrder, MultipleStringLiterals, MultipleVariableDeclarations, MutableException, NeedBraces, NestedForDepth, NestedIfDepth, NestedTryDepth, NewlineAtEndOfFile, NoArrayTrailingComma, NoClone, NoCodeInFile, NoFinalizer, NoLineWrap, NonEmptyAtclauseDescription, NoEnumTrailingComma, NoWhitespaceAfter, NoWhitespaceBefore, NoWhitespaceBeforeCaseDefaultColon, NPathComplexity, OneStatementPerLine, OneTopLevelClass, OperatorWrap, OrderedProperties, OuterTypeFilename, OuterTypeNumber, OverloadMethodsDeclarationOrder, PackageAnnotation, PackageDeclaration, PackageName, ParameterAssignment, ParameterName, ParameterNumber, ParenPad, PatternVariableName, RecordComponentNumber, RecordComponentName, RecordTypeParameterName, RedundantImport, RedundantModifier, Regexp, RegexpHeader, RegexpMultiline, RegexpOnFilename, RegexpSingleline, RegexpSinglelineJava, RequireThis, ReturnCount, RightCurly, SeparatorWrap, SimplifyBooleanExpression, SimplifyBooleanReturn, SingleLineJavadoc, RequireEmptyLineBeforeBlockTagGroup, SingleSpaceSeparator, StaticVariableName, StringLiteralEquality, SummaryJavadoc, SuperClone, SuperFinalize, SuppressWarnings, SealedShouldHavePermitsList, ThrowsCount, TodoComment, TrailingComment, Translation, TypecastParenPad, TypeName, UncommentedMain, UniqueProperties, UnnecessaryParentheses, UnnecessarySemicolonInEnumeration, UnnecessarySemicolonInTryWithResources, UnnecessarySemicolonAfterOuterTypeDeclaration, UnnecessarySemicolonAfterTypeMemberDeclaration, UnusedImports, UpperEll, UnusedCatchParameterShouldBeUnnamed, UnusedLambdaParameterShouldBeUnnamed, UnusedLocalVariable, VariableDeclarationUsageDistance, WhenShouldBeUsed, VisibilityModifier, WhitespaceAfter, WhitespaceAround, WriteTag]

```

2024-12-31 05:45 UTC, romani commented
Please fix order in same commit.

2025-01-02 19:34 UTC, romani commented
ci failure: `ERROR] [checkstyle] [ERROR] C:\projects\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\internal\XdocsPagesTest.java:472:40: Condition with && at line 472 position 39 need optimization. All method calls are advised to move to end of logic expression. [LogicConditionNeedOptimization]`

2025-01-02 23:17 UTC, rnveach commented
@mohitsatr Your PR is now conflicted from @romani 's. You will need to rebase and move the files.

2025-01-03 02:03 UTC, mohitsatr commented
rebased & fixed CI

2025-01-03 04:26 UTC, romani commented
GitHub, generate website

2025-01-03 17:18 UTC, romani commented
awesome - https://www.diffchecker.com/bBUjFxHW/

2025-01-03 17:32 UTC, romani requested changes
it looks suspicious on why we have loop of validations, but it iok, as in "Checks" we have separate group for Holding module, so we so validate sorting in that single item group also, it is ok.
 
item to fix:

2025-01-03 17:32 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
> +            result = getNamesFromIndexPage(current);
not clear why `result` is out of loop, please combine declaration and first definition.
and name should be `names`

2025-01-04 02:16 UTC, mohitsatr commented on src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
> +            result = getNamesFromIndexPage(current);
done

2025-01-04 03:37 UTC, romani approved these changes
Thanks a lot!!

2025-01-04 03:37 UTC, merged