Issue #13345: Enable Example Test for ImportOrder Check
checkstyle/checkstyle pull request #16103
Opened 2024-12-31 20:43 UTC by shaikhu

Title: Enable examples tests for ImportOrderCheck

Related Issue: https://github.com/checkstyle/checkstyle/issues/13345

Summary
This pull request aims to enable example tests for the importOrderCheck in the project. The implementation focuses on ensuring that importOrderCheck are correctly validated through comprehensive test cases, improving overall code reliability and quality.

Key Changes Made

    Conversion of txt file to Java File
    Enable the test cases by adding expected violations in the expected array for all example tests
    Made corresponding changes in the xml and xml.template file

2024-12-31 21:13 UTC, romani commented
GitHub, generate website

2024-12-31 21:23 UTC, romani requested changes
Items:

2024-12-31 21:23 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
> +// extra separation before import and wrong order, comes before 'java.net.URL'.
Please use ` 2 violations above:` comment, see examples in our project

2024-12-31 21:23 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example10.java
> +//non-compiled with javac: Compilable with Java7
Should it be java7 or java11 ? Better to use jdk11

2024-12-31 21:23 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example9.java
> +import static io.netty.handler.codec.http.HttpHeaders.Names.DATE; // violation, wrong order, should sort alphabetically
Please use `violation above '.. message part...'`

2024-12-31 21:23 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example5.java
>  import javax.swing.JComponent; // violation, extra separation in import group
Please use form `violation '...some part of message...'`

2025-01-01 14:22 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example9.java
> +import static io.netty.handler.codec.http.HttpHeaders.Names.DATE; // violation, wrong order, should sort alphabetically
> Please use `violation above '.. message part...'`

Done with slight modification. I had to use `violation above 'start of message...` to void checkstyle failures (exceed line length)

2025-01-01 14:23 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example10.java
> +//non-compiled with javac: Compilable with Java7
> Should it be java7 or java11 ? Better to use jdk11

Done

2025-01-01 14:23 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
> +// extra separation before import and wrong order, comes before 'java.net.URL'.
> Please use ` 2 violations above:` comment, see examples in our project

Done

2025-01-01 21:59 UTC, romani commented
GitHub, generate website

2025-01-02 05:04 UTC, romani commented
GitHub, generate website

2025-01-02 05:10 UTC, romani requested changes
Items

2025-01-02 05:10 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  // xdoc section -- end
Please put `// xdoc section -- end` above class.
Users don't need class definition.

2025-01-02 05:10 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  // xdoc section -- end
Apply to all examples

2025-01-02 06:45 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  // xdoc section -- end
> Apply to all examples

Done

2025-01-02 20:02 UTC, romani commented
GitHub, generate website

2025-01-02 20:17 UTC, romani requested changes
items:

2025-01-02 20:17 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  import org.apache.http.conn.ClientConnectionManager; // OK
please remove "// OK" from all files that you changing.

2025-01-02 20:17 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  import org.apache.http.conn.ClientConnectionManager; // OK
there should be NO comments like "// OK".

the only allowed OK comments are like `// OK, alphabetical case-sensitive ASCII order, 'P' < 'a'` that have extra wording to explain why it is ok. So such comments with details are ok to stay.

2025-01-02 20:21 UTC, romani requested changes
items:

2025-01-02 20:21 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example4.java
> +// all static imports comes at bottom
restore indentation, as it is linewrap from previous line.
or do  change comment to start from line start ` // violation above,`

2025-01-02 20:21 UTC, romani commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example5.java
> +import javax.swing.JComponent; // violation '...separation in import group...'
// violation, 'Extra separation in import group'

2025-01-02 23:34 UTC, romani commented
, please rebase to latest master, I just merged big update for xdoc, and location of it is changed.

2025-01-03 13:02 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
>  import org.apache.http.conn.ClientConnectionManager; // OK
> please remove "// OK" from all files that you changing.

Done

2025-01-03 13:03 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example4.java
> +// all static imports comes at bottom
> restore indentation, as it is linewrap from previous line. or do change comment to start from line start ` // violation above,`

Done. I used `// violation above` as restoring the indentation was causing a checkstyle failure.

2025-01-03 13:03 UTC, shaikhu commented on src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example5.java
> +import javax.swing.JComponent; // violation '...separation in import group...'
> // violation, 'Extra separation in import group'

Done.

2025-01-03 13:04 UTC, shaikhu commented
> , please rebase to latest master, I just merged big update for xdoc, and location of it is changed.

Done.

2025-01-03 15:52 UTC, romani commented
GitHub, generate website

2025-01-03 16:42 UTC, romani approved these changes
I am merging this pleasure.

It is huge leap forward for this Check.
Thanks a lot for hard work

2025-01-03 16:42 UTC, merged