Issue #13345: Enable Test Example for CustomImport
checkstyle/checkstyle pull request #16102
Opened 2024-12-31 19:57 UTC by Anmol202005

Title: Enable examples tests for CustomImportCheck
Related Issue: #13345

Summary
This pull request aims to enable example tests for the ** CustomImportCheck ** in the project. The implementation focuses on ensuring that Indentation Checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

Key Changes Made

Conversion of txt file to Java File
Enable the test cases by adding expected violations in the expected array for all example tests
Made corresponding changes in xml.template file

2024-12-31 20:00 UTC, Anmol202005 commented
![image](https://github.com/user-attachments/assets/b13134c9-9c4a-4abf-9814-596b476f0b9a)
I am getting this error for linelength violation is there any way to suppress this .
Since the lines can not be further reduced .
![image](https://github.com/user-attachments/assets/95b63e70-6c22-4e98-a03b-51d926ea2042)

2024-12-31 20:19 UTC, romani commented
Can we do line wrapping for imports?
I think so, please try.

2025-01-01 06:46 UTC, Anmol202005 commented
Thanks Roman, that worked

2025-01-01 06:52 UTC, Anmol202005 commented
GitHub, generate website

2025-01-01 09:06 UTC, romani requested changes
Items

2025-01-01 09:06 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example6.java
> +import static java.io.File.separator; // OK
Please remove ok comments.

No comment , means ok

2025-01-01 09:29 UTC, romani requested changes
Items

2025-01-01 09:29 UTC, romani commented on config/checkstyle-non-main-files-suppressions.xml
> +
Please remove extra changes

2025-01-01 09:29 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
Please remove all ok comments

2025-01-01 11:45 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
done

2025-01-01 11:45 UTC, Anmol202005 commented on config/checkstyle-non-main-files-suppressions.xml
> +
done

2025-01-01 11:45 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example6.java
> +import static java.io.File.separator; // OK
done

2025-01-01 11:47 UTC, Anmol202005 commented
GitHub, generate website

2025-01-01 17:06 UTC, romani requested changes
Items

2025-01-01 17:06 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example12.java
>  // xdoc section -- end
Please search all `// OK` in your files and remove them

2025-01-01 17:24 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example12.java
>  // xdoc section -- end
Done.

2025-01-01 18:18 UTC, romani commented
GitHub, generate website

2025-01-02 20:31 UTC, romani requested changes
this Check is very special and message does not easily show what is problem and what is expected and why.

so this Check is exceptional and I suggesting to not use messages for complicated case and use free text reasons:

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import java.time.*; // violation, "wrong order"
`// violation, should be in standard package group`

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import javax.net.*; // violation, "wrong order"
`// violation, should be in special import group`

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import org.apache.commons.io.FileUtils; // violation, "wrong order"
`// violation, should be in THIRD PARTY PACKAGE GROUP`

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck; // violation, "wrong order"
please change all `"` to `'`, in all files of your PR.

`// violation, 'wrong order'`

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example11.java
> +import org.apache.commons.io.FileUtils; // violation, "Extra separation"
`// violation, 'Extra separation'`

2025-01-02 20:31 UTC, romani commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example14.java
> +import java.awt.Frame; // violation, "Wrong lexicographical"
`// violation, in ASCII order all uppercase comes before lowercase letters`

2025-01-02 23:35 UTC, romani commented
please rebase to latest master, I just merged big update for xdoc, and location of it is changed.

2025-01-03 01:00 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import java.time.*; // violation, "wrong order"
done

2025-01-03 01:00 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import javax.net.*; // violation, "wrong order"
done

2025-01-03 01:00 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import org.apache.commons.io.FileUtils; // violation, "wrong order"
done

2025-01-03 01:00 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.java
> +import com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck; // violation, "wrong order"
done

2025-01-03 01:00 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example11.java
> +import org.apache.commons.io.FileUtils; // violation, "Extra separation"
done

2025-01-03 01:01 UTC, Anmol202005 commented on src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example14.java
> +import java.awt.Frame; // violation, "Wrong lexicographical"
done

2025-01-03 01:02 UTC, Anmol202005 commented
Done, I have rebased to latest master

2025-01-03 01:37 UTC, romani commented
Please address red CI

2025-01-03 04:10 UTC, romani commented
GitHub, generate website

2025-01-03 04:22 UTC, romani approved these changes
Ok to merge.


Thanks a lot.
It is very complicated Check, at least we made it actual and a bit better.

2025-01-03 04:22 UTC, merged