chore: add compilerArg `-Xpkginfo:always` for useIncrementalCompilation which make build fast
checkstyle/checkstyle pull request #8787
Opened 2020-09-05 03:27 UTC by qxo

useIncrementalCompilation will not work for some java not compiled (package-info.java).
try `mvn package -X ` will find thest files by key word "recompiling the module!"

maven will not compile package-info.java without any annotation with Retention=RUNTIME

ref:
https://stackoverflow.com/questions/6770455/maven-compiling-package-info-java-to-package-info-class
https://github.com/jenkinsci/jenkins/pull/4759

PLEASE READ before removing!!

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
   Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
   a) MUST match one of the following patterns:
      ^Issue #\\d+: .*$
      ^Pull #\\d+: .*$
      ^(minor|config|infra|doc|spelling|dependency): .*$
   b) MUST contain only one line of text
   c) MUST NOT end with a period, space, or tab
   d) MUST be less than or equal to 200 characters

To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html

ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.

Thanks for reading, remove whole this message and type what you need.

2020-09-11 14:22 UTC, romani commented
please provide CLI prove that compilation time is reduced, share statistic in PR description.

2020-09-11 15:19 UTC, strkkk commented
As for me, it looks like almost always build is run by `mvn clean package` or `mvn clean verify`, so clean will remove all previously compiled classes anyway. 
So it looks like it is not that useful.

2020-09-12 03:09 UTC, romani commented
CI will not benefit from this.
And we have sources generation phase that generate parser, so some compiler is not avoidable

2020-09-12 14:10 UTC, romani requested changes
It works good for main sources compilation BUT it does not work for `mvn verify` that we use all the time.
See details below:
```
✔ ~/java/github/romani/checkstyle [master|✔] 

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ checkstyle ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 406 source files to /home/rivanov/java/github/romani/checkstyle/target/classes
[INFO] /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java: /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java uses or overrides a deprecated API.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.786 s


✔ ~/java/github/romani/checkstyle [qxo/forceCompile4pkginfo L|✔] 


[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ checkstyle ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.075 s



========================

✔ ~/java/github/romani/checkstyle [master|✔] 
$ mvn test-compile

[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ checkstyle ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1999 source files to /home/rivanov/java/github/romani/checkstyle/target/test-classes
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Some input files use or override a deprecated API.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Some input files use unchecked or unsafe operations.
[INFO] /home/rivanov/java/github/romani/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:instrument (default-instrument) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.823 s


✘-1 ~/java/github/romani/checkstyle [qxo/forceCompile4pkginfo L|✔] 
$ mvn test-compile
....

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ checkstyle ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default) @ checkstyle ---
[WARNING] 
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_43f5073/Offline
    at com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator.$jacocoInit (JavadocPropertiesGenerator.java)
    at com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator.<clinit> (JavadocPropertiesGenerator.java)
    at sun.misc.Unsafe.ensureClassInitialized (Native Method)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:330)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:327)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:227)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:209)
    at java.lang.ClassValue.get (ClassValue.java:115)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:351)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:341)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:291)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_43f5073.Offline
    at java.net.URLClassLoader.findClass (URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator.$jacocoInit (JavadocPropertiesGenerator.java)
    at com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator.<clinit> (JavadocPropertiesGenerator.java)
    at sun.misc.Unsafe.ensureClassInitialized (Native Method)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:330)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:327)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:227)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:209)
    at java.lang.ClassValue.get (ClassValue.java:115)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:351)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:341)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:291)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.975 s
[INFO] Finished at: 2020-09-12T07:07:02-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default) on project checkstyle: An exception occured while executing the Java class. org/jacoco/agent/rt/internal_43f5073/Offline: org.jacoco.agent.rt.internal_43f5073.Offline -> [Help 1]
[ERROR] 


✘-1 ~/java/github/romani/checkstyle [qxo/forceCompile4pkginfo L|✔] 
$ mvn verify
...
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default) on project checkstyle: An exception occured while executing the Java class. org/jacoco/agent/rt/internal_43f5073/Offline: org.jacoco.agent.rt.internal_43f5073.Offline -> [Help 1]
```

2020-09-19 14:48 UTC, romani commented
@qxo , please reply,
if no good reply, please close PR.
If no reply till end of September, I will close this PR.

2020-10-04 13:53 UTC, closed without merging