PropertiesExpander init support property resolver
checkstyle/checkstyle pull request #8794
Opened 2020-09-06 08:39 UTC by qxo

so we an using expression (ie:${basedir}) in checkstyle.properties

2020-09-20 14:31 UTC, romani requested changes
please create issue on this and explain what is problem now and what is suggested behavior.
Issue will be used in release notes to route users to read more.
Issue number should be used in commit message.

We also need to update documentation files in xdoc folder, 

items:

2020-09-20 14:31 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/PropertiesExpander.java
> +            String val = properties.getProperty(name);
`val` -> `value`

2020-09-20 14:31 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/PropertiesExpander.java
> +            final String val, final Set<String> resolveKeys) {
remove "final" from all arguments.

2020-09-20 14:31 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/PropertiesExpander.java
> +        String ret = val;
please use full names for both variables.

2020-10-05 02:29 UTC, romani commented
@qxo , please reply

2020-10-05 02:48 UTC, qxo commented
> @qxo , please reply

I just saw it.
ok, I'll check the review.

2021-01-11 17:18 UTC, nmancus1 commented
@qxo please share any thoughts at https://github.com/checkstyle/checkstyle/issues/9173

2021-01-18 00:56 UTC, romani commented
this PR is abandoned ,
@nmancus1 , please open new PR with update of code for issue that you are created.
please do not forget about documentation update on this feature.

2021-01-18 00:56 UTC, closed without merging