Issue #7669: Updated docs for MultipleVaribleDeclaration
checkstyle/checkstyle pull request #8988
Opened 2020-11-14 13:00 UTC by AkMo3

Fixes #7669

![Checkstyle](https://user-images.githubusercontent.com/69365878/99147483-4ab98c00-26a7-11eb-93cb-76267182dc91.jpg)

```
PS H:\CheckstyleCheck> cat .\config.xml
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="MultipleVariableDeclarations">
    </module>
  </module>
</module>
PS H:\CheckstyleCheck> cat .\Test.java
public class Test {
  public void myTest() {
    int mid;
    int high;
    // ...

    int lower, higher; // violation
    // ...

    int value,
        index;  //Violation
    // ...

    int place = mid, number = high; // violation, each to be declared at a new line
}
}
PS H:\CheckstyleCheck> java -jar H:\GitHub\checkstyle\target\checkstyle-8.38-SNAPSHOT-all.jar -c .\config.xml .\Test.java
Starting audit...
[ERROR] H:\CheckstyleCheck\.\Test.java:7:5: Each variable declaration must be in its own statement. [MultipleVariableDeclarations]
[ERROR] H:\CheckstyleCheck\.\Test.java:10:5: Each variable declaration must be in its own statement. [MultipleVariableDeclarations]
[ERROR] H:\CheckstyleCheck\.\Test.java:14:5: Each variable declaration must be in its own statement. [MultipleVariableDeclarations]
Audit done.
Checkstyle ends with 3 errors.
```

2020-11-14 13:01 UTC, AkMo3 commented
I am really sorry that I have to create a new PR, but my branch had totally conflicted, and it was no longer mergable so, had to create a new PR.

2020-11-14 13:25 UTC, AkMo3 commented
Github, generate web site

2020-11-14 15:11 UTC, AkMo3 commented
@romani  Please have a look at PR.

2020-11-14 16:33 UTC, romani requested changes
items:

2020-11-14 16:33 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
> + *       index;  //Violation
`// violation`

2020-11-14 16:33 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
> + *   int place = mid, number = high; // violation, each to be declared at a new line
`// violation`

2020-11-14 17:42 UTC, romani approved these changes

2020-11-15 07:27 UTC, strkkk requested changes

2020-11-15 07:27 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
> + * public void myTest() {
This will not compile, please change method to class

2020-11-15 08:12 UTC, strkkk approved these changes

2020-11-15 14:37 UTC, romani approved these changes
Ok to merge if CI green

2020-11-16 11:18 UTC, merged