minor : Updated SuperFinalize doc
checkstyle/checkstyle pull request #8993
Opened 2020-11-17 15:39 UTC by harshitmalik03

Issue : #7662 
minor : Updated SuperFinalize doc

2020-11-17 16:41 UTC, romani commented
There should be update in xdoc file and javadoc of Check class.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheck.java

2020-11-22 14:59 UTC, romani commented
@harshitmalik03 , do you have problems to finish this PR ?

2020-11-22 15:03 UTC, romani requested changes
https://checkstyle.org/config_coding.html#SuperFinalize

2020-11-22 15:03 UTC, romani commented on src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/SuperFinalizeCheck.xml
> +                      name="format"
I am not sure how you get all that properties, This Check has no properties at all.

2020-11-22 15:48 UTC, harshitmalik03 commented
> @harshitmalik03 , do you have problems to finish this PR ?

Actually I do have a problem .... I did change the xdoc file but that too by just looking at the example you gave and i don't know if that's how its done .... I still need someone to tell me more about how exactly do i do this.

2020-11-22 16:00 UTC, romani commented
please review commits from https://github.com/checkstyle/checkstyle/issues?q=is%3Aissue+label%3A%22gsoc+first+issue%22+is%3Aclosed
it will give you idea what and how to change a code.

2020-11-22 22:27 UTC, harshitmalik03 commented
Hey,
I checked that out..... Im not getting those "List&lt;Integer&gt". I dont know what these are and what are these for?

2020-11-24 15:40 UTC, romani commented
@harshitmalik03 , please create PR when you pass `mvn verify` on local and you will see your examples in website.
Here is how to generate website on local - https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-website-only

2020-11-24 15:40 UTC, closed without merging