Issue #8971: ExecutableStatementCount should allow LAMBDA token
checkstyle/checkstyle pull request #9067
Opened 2020-11-30 11:09 UTC by shashwatj07

Resolves #8971

2020-12-07 09:42 UTC, strkkk requested changes
Please also fix CI

2020-12-07 09:42 UTC, strkkk commented on src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
> +            "90:29: " + getCheckMessage(MSG_KEY, 1, 0),
it is not that easy.
Please add more test cases with lambdas like `a -> a.trim()` where executable statement count should be 1.

2021-02-07 22:28 UTC, romani commented
@shashwatj07 , please finish PR.

2021-03-06 23:40 UTC, romani commented
@shashwatj07 , ping

2021-03-15 02:01 UTC, closed without merging