Issue #7583: Added example for default config of if else tokens
checkstyle/checkstyle pull request #9095
Opened 2020-12-10 10:11 UTC by Vyom-Yadav

Issue #7583: Added example for default config of if else tokens

2020-12-10 10:13 UTC, Vyom-Yadav commented
@Abhishek-kumar09 Sorry for closing the other PR as I set up a new upstream for my branch and in earlier PR couldn't set up due to an error. Please review this addition if it's fine then I will add it for all tokens.

2020-12-10 10:21 UTC, Vyom-Yadav commented
Github, rebase

2020-12-10 10:23 UTC, Vyom-Yadav commented
Github, generate web site

2020-12-11 15:41 UTC, Vyom-Yadav commented
@Abhishek-kumar09 ping

2020-12-11 16:58 UTC, Abhishek-kumar09 requested changes

2020-12-11 16:58 UTC, Abhishek-kumar09 commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
> + *   &lt;property name=&quot;allowSingleLineStatement&quot; value=&quot;false&quot;/&gt;
This is not the default property.
Default config is one without any property being explicitly set.
This is the default config: 
```xml
<module name="NeedBraces"/>
```
You have to look at the table and generate the exmples foro the same.

2020-12-12 09:34 UTC, Vyom-Yadav commented
@Abhishek-kumar09 I am really sorry but I have to close this one also as my branches are conflicting. Currently, in my repo, there are two branches by the same name IDK how, I will have to delete these branches and create a new branch and a new PR, sorry for the inconvenience.

2020-12-12 09:34 UTC, closed without merging

2020-12-12 13:24 UTC, Abhishek-kumar09 commented
@Vyom-Yadav  Don't do github rebase on website only, You have to rebase things on your local setup also. It may be the reason behind conflicts.

2020-12-12 16:20 UTC, Vyom-Yadav commented
> @Vyom-Yadav Don't do github rebase on website only, You have to rebase things on your local setup also. It may be the reason behind conflicts.

Ok will do it from now