Fix enum checks
checkstyle/checkstyle pull request #9230
Opened 2021-02-02 08:36 UTC by strkkk

Fixes for #8653

After https://github.com/checkstyle/checkstyle/pull/9229 is merged, enum related checks are extended with empty enum body with comma inputs + NoEnumTrailingCheck rewritten to handle such cases

2021-02-02 08:38 UTC, strkkk commented
Regression for NoEnumTrailingCommaCheck: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8653_fix_failure_on_empty_enum_2021131932/reports/diff/index.html

No diff

2021-02-13 15:33 UTC, romani commented
@strkkk , please rebase and update PR title and description to define target of fix

2021-02-13 16:19 UTC, strkkk commented
@romani done

2021-02-13 23:31 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheck.java
> +        return new int[] {TokenTypes.ENUM_DEF};
it is not breaking compatibility, such token is not adjustable by user so users are not affected

2021-02-13 23:32 UTC, romani requested changes
items:

2021-02-13 23:32 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingComma.java
> +        ,;
trailing comments please.

2021-02-14 07:55 UTC, strkkk commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingComma.java
> +        ,;
done

2021-02-14 08:10 UTC, pbludov approved these changes

2021-02-14 19:02 UTC, romani approved these changes
Ok to merge

2021-02-14 19:02 UTC, merged