Issue #7581: Add default config and code examples for EmptyCatchBlock
checkstyle/checkstyle pull request #9319
Opened 2021-02-23 12:48 UTC by SGanguly1999

Closes: #7581

![image](https://user-images.githubusercontent.com/42171790/108845221-256fde80-7603-11eb-9d4b-26311dbccde4.png)

`$ cat Hello.java`

```
class Hello {
  public static void main(String args[]) {
    try {

    }
    catch(Exception e) { // violation since catch block is empty

    }
  }
}
```

`$ cat config.xml`

```
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="EmptyCatchBlock"/>
  </module>
</module>
```

Output:

```
$ java -jar checkstyle-8.39-all.jar -c config.xml Hello.java
Starting audit...
[ERROR] E:\New folder\Java Dev\src\com\company\Hello.java:10:9: Empty catch block. [EmptyCatchBlock]
Audit done.
Checkstyle ends with 1 errors.

```

2021-02-24 10:20 UTC, strkkk requested changes

2021-02-24 10:20 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
> + *   Example:
should be no indentation here

2021-02-24 10:20 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
> + *   To configure the check:
same here

2021-02-24 10:20 UTC, strkkk commented on src/xdocs/config_blocks.xml
> +        Example:
indentation +2

2021-02-24 10:20 UTC, strkkk commented on src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
> + * class Hello {
please make examples same as ones below to show difference between configs

Also, description says that `By default check allows empty catch block with any comment inside.` please show this

2021-02-24 19:02 UTC, SGanguly1999 commented
@strkkk....I will surely make the changes as soon as possible

2021-03-10 13:13 UTC, SGanguly1999 commented
@strkkk  there is some mistake in this branch  i am creating a PR attaching this issue on it.

2021-03-10 13:13 UTC, closed without merging