Temp
checkstyle/checkstyle pull request #9384
Opened 2021-03-12 14:02 UTC by gurleennsidhuu

Issue: #7688 
Adds examples to the doc "config_imports" for redundant import.

2021-03-12 14:28 UTC, AkMo3 commented
@gurleennsidhuu Please squash commits into one and run `mvn clean verify` and see it passes successfully.

2021-03-12 21:13 UTC, AkMo3 requested changes
Item:

2021-03-12 21:13 UTC, AkMo3 commented on src/xdocs/config_imports.xml
> +       </source>
Wrong indention at line 2328 is failing tests. Make indention 8 (add another space in front of it.)

2021-03-13 04:43 UTC, Vyom-Yadav commented on src/xdocs/config_imports.xml
> +       </source>
Also while updating examples you have to modify 2 files, the XML file and the Javadoc of the check you are updating. In your case, it is `RedundantImportCheck`

2021-03-14 11:42 UTC, closed without merging