Issue #9406: update example of AST for TokenTypes.CASE_GROUP
checkstyle/checkstyle pull request #9602
Opened 2021-03-16 06:18 UTC by vivek286

Closes #9406 

![WhatsApp Image 2021-03-16 at 11 45 26 AM](https://user-images.githubusercontent.com/68116663/111264335-8c6e2b00-85e4-11eb-9872-244203c3aac6.jpeg)

Expected changes for update example of AST for TokenTypes.CASE_GROUP
![WhatsApp Image 2021-03-16 at 11 46 09 AM](https://user-images.githubusercontent.com/68116663/111264395-a9a2f980-85e4-11eb-8219-2a91ba848dc6.jpeg)

2021-03-16 08:37 UTC, anshuman10398 commented
github, generate website

2021-03-16 08:39 UTC, anshuman10398 commented
Github, generate web site

2021-03-16 17:06 UTC, vivek286 commented
@rdiachenko  please review if you have time

2021-03-16 18:42 UTC, vivek286 commented
@rdiachenko please review if you have time

2021-03-16 20:53 UTC, rdiachenko commented
@vivek286 please update description according to https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes (check PR example mentioned)

2021-03-19 13:57 UTC, romani requested changes
please keep in PR description image of javadoc after code update

2021-03-19 13:57 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |--CASE_GROUP -&gt; CASE_GROUP
remove first `|` in all lines, it is not required

2021-03-27 13:55 UTC, romani commented
if there will be no reply in a week, this PR be closed.

2021-04-03 14:37 UTC, closed without merging