Issue #9400: update example of AST for TokenTypes.BLOCK_COMMENT_END
checkstyle/checkstyle pull request #9610
Opened 2021-03-16 14:12 UTC by vivek286

Closes #9400 

![WhatsApp Image 2021-03-16 at 7 39 51 PM](https://user-images.githubusercontent.com/68116663/111323068-c7914e00-8626-11eb-9053-cacab50b206c.jpeg)

Expected update example of AST for TokenTypes.BLOCK_COMMENT_END

![WhatsApp Image 2021-03-16 at 7 40 25 PM](https://user-images.githubusercontent.com/68116663/111323213-e394ef80-8626-11eb-98d6-84006fc0c80b.jpeg)

2021-03-16 18:42 UTC, vivek286 commented
@romani please review if you have time

2021-03-16 19:33 UTC, Abhishek-kumar09 commented
java Test.java
```java
class A {
  // hi
}
```
$ java -jar checkstyle-8.41-all.jar -t Test.java 
```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> A [1:6]
`--OBJBLOCK -> OBJBLOCK [1:8]
    |--LCURLY -> { [1:8]
    `--RCURLY -> } [3:0]
```
Comments are not getting any AST print, is it normal?

2021-03-16 19:47 UTC, vivek286 commented
Please guide me through the development IDE setup, the process given in documentation is a bit confusing.

2021-03-19 14:04 UTC, romani commented
@Abhishek-kumar09 

> Comments are not getting any AST print, is it normal?

use `-T` CLI argument to print comment.

2021-03-19 14:07 UTC, romani requested changes
item

2021-03-19 14:07 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *      |--BLOCK_COMMENT_END -&gt; BLOCK_COMMENT_END
please make java code examples to make it visual for user like `// comment` and `/* comment */`

2021-03-27 14:38 UTC, romani commented
@vivek286 , please reply in next 7 days, if no reply, I will close PR

2021-04-03 14:38 UTC, closed without merging