Issue #9549 : updated example of AST for TokenTypes.PACKAGE_DEF
checkstyle/checkstyle pull request #9612
Opened 2021-03-16 15:44 UTC by theanmolsharma

## Issue #9549 : updated example of AST for TokenTypes.PACKAGE_DEF

closes #9549 
<img width="482" alt="Screenshot 2021-03-16 at 9 02 09 PM" src="https://user-images.githubusercontent.com/65589791/111337146-d9610880-869b-11eb-8b70-556fecb418e4.png">

```
% java -jar checkstyle-8.41-all.jar -t MyClass.java | grep "1:"
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:39]
|--DOT -> . [1:39]
|   |--DOT -> . [1:28]
|   |   |--DOT -> . [1:22]
|   |   |   |--DOT -> . [1:11]
|   |   |   |   |--IDENT -> com [1:8]
|   |   |   |   `--IDENT -> puppycrawl [1:12]
|   |   |   `--IDENT -> tools [1:23]
|   |   `--IDENT -> checkstyle [1:29]
|   `--IDENT -> api [1:40]
`--SEMI -> ; [1:43]
```

expected update for javodoc is:

```
PACKAGE_DEF -> package
|--ANNOTATIONS -> ANNOTATIONS
|--DOT -> .
|   |--DOT -> .
|   |   |--DOT -> .
|   |   |   |--DOT -> .
|   |   |   |   |--IDENT -> com
|   |   |   |   `--IDENT -> puppycrawl
|   |   |   `--IDENT -> tools
|   |   `--IDENT -> checkstyle
|   `--IDENT -> api
`--SEMI -> ;
```

2021-03-16 19:18 UTC, pbludov approved these changes
I'm ok to merge if you make the CI pass.
The commit message should be fixed.

2021-03-17 03:56 UTC, theanmolsharma commented
> I'm ok to merge if you make the CI pass.
> The commit message should be fixed.

I am unable to figure out what changes to make and why CI is failing.
Please help.

2021-03-17 04:05 UTC, Vyom-Yadav commented
`Issue #9549 : updated example of AST for TokenTypes.PACKAGE_DEF` -> `Issue #9549: updated example of AST for TokenTypes.PACKAGE_DEF
`

2021-03-17 04:32 UTC, shashwatj07 commented
Replying to https://github.com/checkstyle/checkstyle/pull/9600#issuecomment-800778916

Please fix your commit message and force push.

2021-03-17 04:37 UTC, theanmolsharma commented
> Replying to [#9600 (comment)](https://github.com/checkstyle/checkstyle/pull/9600#issuecomment-800778916)
> 
> Please fix your commit message and force push.

What should I change? Please help. I am unable to understand.

2021-03-17 06:50 UTC, Vyom-Yadav commented
Please drop the dependency bump commit.

2021-03-17 07:59 UTC, Vyom-Yadav commented
@theanmolsharma Few points-

- Keep the number of commits one.
- Don't address two issues in a PR.
- If you want to learn how to rebase, you can read [this](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec), its pretty user friendly.

2021-03-17 08:05 UTC, theanmolsharma commented
> @theanmolsharma Few points-
> 
> * Keep the number of commits one.
> * Don't address two issues in a PR.
> * If you want to learn how to rebase, you can read [this](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec), its pretty user friendly.

Okay I will squash the latest commit. Will that be okay?

2021-03-17 09:02 UTC, Vyom-Yadav commented
> @Vyom-Yadav
> 
> Okay I will squash the latest commit. Will that be okay?
> Also please guide me as I am new. How to address 2 different issues? By creating a separate branch?

1. Never commit to the master branch directly.
2. Always create a separate branch for an issue.
3. Keep the number of commits by squashing them into one (Can be done by the tutorial link I provided above or any of your choice).

2021-03-18 17:07 UTC, pbludov commented
@theanmolsharma your PR should contain only one commit. Use `git rebase --interactive HEAD~4` to drop all axtra commits. Then rebase to the latest master.

2021-03-18 17:27 UTC, pbludov commented
The commit message says that this is example for `TokenTypes.PACKAGE_DEF`, but it is not.

2021-03-18 17:28 UTC, pbludov commented
Please fix the PR description too.

2021-03-18 17:50 UTC, theanmolsharma commented
@pbludov I am so sorry for creating a mess here. My sincerest apologies. I am new to open source and therefore I didn't know how to contribute. Thank you for your patience. I have fixed everything. Now my PR has only 1 commit which is to fix issue #9549

2021-03-19 06:28 UTC, Vyom-Yadav commented
Github, rebase

2021-03-19 21:46 UTC, pbludov commented
`The PR is based on a master that is 21 commit(s) old.
The max allowed is 10.
This PR is too old and should be rebased on origin/master.
`
@theanmolsharma please rebase:
```bash
git pull --rebase upstream master
```
Where `upstream` should be https://github.com/checkstyle/checkstyle as described [here](https://checkstyle.org/beginning_development.html)

2021-03-20 23:17 UTC, romani requested changes
please properly rebase all your changes over our latest master
here are details - https://checkstyle.org/beginning_development.html#Starting_Development

2021-03-21 15:15 UTC, romani approved these changes

2021-03-21 15:15 UTC, merged