Issue #9485: add example of AST for TokenType.LITERAL_NATIVE
checkstyle/checkstyle pull request #9616
Opened 2021-03-16 17:34 UTC by vivek286

Closes #9485 

![WhatsApp Image 2021-03-16 at 11 03 06 PM](https://user-images.githubusercontent.com/68116663/111353958-0df4a600-8643-11eb-86b0-31b47dedf8cd.jpeg)

Expected change in code
![WhatsApp Image 2021-03-16 at 11 02 27 PM](https://user-images.githubusercontent.com/68116663/111354063-2664c080-8643-11eb-9410-8a162f1e3ddb.jpeg)

2021-03-17 23:22 UTC, rdiachenko commented
@vivek286 please update description according to https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes (check PR example mentioned)

2021-03-20 22:43 UTC, romani requested changes
item:

2021-03-20 22:43 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |--LITERAL_SYNCHRONIZED -&gt; synchronized
I do not see "native" usage this example

2021-03-27 13:55 UTC, romani commented
if there will be no reply in a week, this PR be closed.

2021-04-03 14:39 UTC, closed without merging