Issue #9556: Added example of AST for TokenTypes.POST_INC
checkstyle/checkstyle pull request #9633
Opened 2021-03-17 16:05 UTC by shashwatj07

Resolves #9556 

![image](https://user-images.githubusercontent.com/52609734/111499126-a173c700-8768-11eb-8ae1-cfd53a13f3b8.png)

```

C:\Users\Shashwat>cat Test.java
public class Test {
    void foo(long a) {
      a++;
    }
}

C:\Users\Shashwat>java -jar checkstyle-8.41-all.jar -t Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:18]
    |--LCURLY -> { [1:18]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |--TYPE -> TYPE [2:4]
    |   |   `--LITERAL_VOID -> void [2:4]
    |   |--IDENT -> foo [2:9]
    |   |--LPAREN -> ( [2:12]
    |   |--PARAMETERS -> PARAMETERS [2:13]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:13]
    |   |       |--MODIFIERS -> MODIFIERS [2:13]
    |   |       |--TYPE -> TYPE [2:13]
    |   |       |   `--LITERAL_LONG -> long [2:13]
    |   |       `--IDENT -> a [2:18]
    |   |--RPAREN -> ) [2:19]
    |   `--SLIST -> { [2:21]
    |       |--EXPR -> EXPR [3:7]
    |       |   `--POST_INC -> ++ [3:7]
    |       |       `--IDENT -> a [3:6]
    |       |--SEMI -> ; [3:9]
    |       `--RCURLY -> } [4:4]
    `--RCURLY -> } [5:0]
```

2021-03-18 14:05 UTC, shashwatj07 commented
@strkkk please restart semaphore CI

2021-03-18 17:18 UTC, pbludov requested changes

2021-03-18 17:18 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |       |--IDENT -&gt; a
|--IDENT -> `--IDENT

2021-03-18 17:31 UTC, shashwatj07 commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |       |--IDENT -&gt; a
Oh, sorry. My bad!

2021-03-18 17:33 UTC, shashwatj07 commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |       |--IDENT -&gt; a
Done. I'll be more careful next time.

2021-03-19 17:47 UTC, pbludov approved these changes

2021-03-20 07:21 UTC, merged