Issue #9593: update example of AST for TokenTypes.UNARY_MINUS
checkstyle/checkstyle pull request #9635
Opened 2021-03-17 16:39 UTC by gurleennsidhuu

Issue #9593: update example of AST for TokenTypes.UNARY_MINUS
BEFORE:
![be](https://user-images.githubusercontent.com/64313783/111504197-6de76b80-876d-11eb-84eb-618149d56690.jpg)

AFTER:
![af](https://user-images.githubusercontent.com/64313783/111504094-56a87e00-876d-11eb-94f7-90ad1933e1c4.jpg)

2021-03-18 15:41 UTC, AkMo3 requested changes
Point:

2021-03-18 15:42 UTC, AkMo3 requested changes
Point:

2021-03-18 15:42 UTC, AkMo3 commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *                  +--IDENT (b)
@gurleennsidhuu Please share CLI output, and site output. Also, please match CLI output with your changes. These changes doesn't seem correct to me.

2021-03-20 22:48 UTC, romani requested changes
javadoc should use CLI output with minor corrections as defined in issue.
Please take a look in example PR.

2021-03-27 23:57 UTC, romani commented
If no response in 5 days, I will close PR

2021-04-03 14:42 UTC, closed without merging