Issue #9548: add code example of AST for TokenTypes.OBJBLOCK
checkstyle/checkstyle pull request #9721
Opened 2021-03-25 14:38 UTC by CryptoSingh1337

Closes: #9548 
![image](https://user-images.githubusercontent.com/56120837/112490527-72cba100-8da5-11eb-8808-e3059005c17b.png)

**Successfully compiled**
![image](https://user-images.githubusercontent.com/56120837/112490608-87a83480-8da5-11eb-8067-a1b72ad0eeca.png)

**Test.java**
`λ cat Test.java`
```
class Test {}
```
**AST**
`λ java -jar checkstyle-8.41-all.jar -t Test.java`
```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> Test [1:6]
`--OBJBLOCK -> OBJBLOCK [1:11]
    |--LCURLY -> { [1:11]
    `--RCURLY -> } [1:12]
```
### Expected update for javadoc
```
CLASS_DEF -> CLASS_DEF
|--MODIFIERS -> MODIFIERS
|--LITERAL_CLASS -> class
|--IDENT -> Test
`--OBJBLOCK -> OBJBLOCK
    |--LCURLY -> {
    `--RCURLY -> }
```

2021-03-25 16:35 UTC, timurt requested changes

2021-03-25 16:35 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * <pre>class Test {}</pre>
please, put tags and content on separate lines

2021-03-26 18:46 UTC, timurt requested changes

2021-03-26 18:46 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *     For example:
this one can be written in one line, I meant `<pre>` tag

2021-03-26 18:46 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *     class Test {}
please delete preceding spaces

2021-03-26 18:46 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *     parses as:
same as for `For example:` section, should be on the same line

you can use https://github.com/checkstyle/checkstyle/pull/9378/files as an example

2021-03-28 01:34 UTC, romani approved these changes

2021-03-28 01:34 UTC, merged