Refactored test with multiple assertions into a parameterized one
checkstyle/checkstyle pull request #9769
Opened 2021-03-30 19:06 UTC by eas5

Problem:
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution. In the refactored methods, the difference between the assertions lies in different arguments only.

Solution:
Parameterized tests make it possible to run a test multiple times, with different arguments, as individual and independent tests. This way, we were able to make 1 original test become 6 independent ones. In this refactoring, no original assertion parameter was changed.

2021-03-31 07:05 UTC, strkkk commented
@eas5 Thanks for your contribution. Please fix code to pass CI

2021-04-17 23:53 UTC, romani requested changes
items:

2021-04-17 23:53 UTC, romani commented on src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java
> +    @MethodSource("testGetShortDescriptionProvider")
it is not good approach.
it is very compact and very technological but VERY complicated and cryptic.
We need easy to read tests and make them as much as possible to be focused on human ability to read them easily - https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2021-Project-Ideas#project-name-adaptation-of-behavior-driven-development-ideas-for-testing-of-source-code-validation-algorithms

---
 

I do not understand why we need so much instances for `getShortDescription`, better approach is simply remove all except for one.

2021-05-16 22:08 UTC, romani commented
we lost connection to author , PR is closed.

2021-05-16 22:08 UTC, closed without merging