Issue #9773: update DeclarationOrderCheckTest.java to use unique Inpu…
checkstyle/checkstyle pull request #9812
Opened 2021-04-04 04:33 UTC by MahmoudAbdelazim

Closes #9773

2021-04-04 04:36 UTC, MahmoudAbdelazim commented
@romani @timurt please review the changes.

2021-04-05 15:00 UTC, timurt requested changes

2021-04-05 17:41 UTC, MahmoudAbdelazim commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderVariableAccess.java
>      public static final InputDeclarationOrderVariableAccess.Stream STREAM =
Yes, should I add the comment behind it instead of above it? It's just that the statement takes two lines that's why I thought this was better.

2021-04-05 17:42 UTC, MahmoudAbdelazim commented on src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
> +            "64:5: " + getCheckMessage(MSG_ACCESS),
Done

2021-04-05 18:17 UTC, MahmoudAbdelazim commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderVariableAccess.java
>      public static final InputDeclarationOrderVariableAccess.Stream STREAM =
The line then will be too long the checkstyle will produce an error for that.

2021-04-06 14:50 UTC, romani commented on src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderVariableAccess.java
>      public static final InputDeclarationOrderVariableAccess.Stream STREAM =
we will fix during automation of this verification

2021-04-06 14:50 UTC, romani approved these changes

2021-04-06 14:52 UTC, merged