Issue #9481: updated example of AST for TokenTypes.LITERAL_INSTANCEOF
checkstyle/checkstyle pull request #9862
Opened 2021-04-12 13:56 UTC by AmrBumadian

Updated the TokenTypes.java file according to Issue #9481

![Capture](https://user-images.githubusercontent.com/35141856/114406056-8483b580-9ba7-11eb-97d7-f3042a910ee5.PNG)

added example:
<pre>
<code>
StringBuilder text = new StringBuilder();
boolean isBuilder = text instanceof StringBuilder;
</code>
</pre>

<pre>
D:\Work\GSOC>java -jar checkstyle-8.41.1-all.jar -t Test.java
CLASS_DEF -> CLASS_DEF
|--MODIFIERS -> MODIFIERS
|--LITERAL_CLASS -> class
|--IDENT -> Test
`--OBJBLOCK -> OBJBLOCK 
    |--LCURLY -> {
    |--METHOD_DEF -> METHOD_DEF 
    |   |--MODIFIERS -> MODIFIERS 
    |   |   |--LITERAL_PUBLIC -> public 
    |   |   `--LITERAL_STATIC -> static 
    |   |--TYPE -> TYPE 
    |   |   `--LITERAL_VOID -> void 
    |   |--IDENT -> main 
    |   |--LPAREN -> ( 
    |   |--PARAMETERS -> PARAMETERS
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF 
    |   |       |--MODIFIERS -> MODIFIERS 
    |   |       |--TYPE -> TYPE 
    |   |       |   `--ARRAY_DECLARATOR -> [ 
    |   |       |       |--IDENT -> String 
    |   |       |       `--RBRACK -> ] 
    |   |       `--IDENT -> args 
    |   |--RPAREN -> ) 
    |   `--SLIST -> { 
    |       |--VARIABLE_DEF -> VARIABLE_DEF 
    |       |   |--MODIFIERS -> MODIFIERS 
    |       |   |--TYPE -> TYPE 
    |       |   |   `--IDENT -> StringBuilder 
    |       |   |--IDENT -> text 
    |       |   `--ASSIGN -> = 
    |       |       `--EXPR -> EXPR 
    |       |           `--LITERAL_NEW -> new 
    |       |               |--IDENT -> StringBuilder 
    |       |               |--LPAREN -> ( 
    |       |               |--ELIST -> ELIST 
    |       |               `--RPAREN -> ) 
    |       |--SEMI -> ; 
    |       |--VARIABLE_DEF -> VARIABLE_DEF 
    |       |   |--MODIFIERS -> MODIFIERS 
    |       |   |--TYPE -> TYPE 
    |       |   |   `--LITERAL_BOOLEAN -> boolean 
    |       |   |--IDENT -> isBuilder 
    |       |   `--ASSIGN -> = 
    |       |       `--EXPR -> EXPR 
    |       |           `--LITERAL_INSTANCEOF -> instanceof 
    |       |               |--IDENT -> text 
    |       |               `--TYPE -> TYPE
    |       |                   `--IDENT -> StringBuilder 
    |       |--SEMI -> ;
    |       `--RCURLY -> }
    `--RCURLY -> }
</pre>

expected update for java doc:

<pre>
    |--VARIABLE_DEF -> VARIABLE_DEF
    |   |--MODIFIERS -> MODIFIERS
    |   |--TYPE -> TYPE
    |   |   `--LITERAL_BOOLEAN -> boolean
    |   |--IDENT -> isBuilder
    |   `--ASSIGN -> = 
    |       `--EXPR -> EXPR
    |           `--LITERAL_INSTANCEOF -> instanceof
    |               |--IDENT -> text
    |               `--TYPE -> TYPE
    |                   `--IDENT -> StringBuilder
    |--SEMI -> ;
</pre>

<code> mvn clean verify </code>

![Capture2](https://user-images.githubusercontent.com/35141856/114406026-7df53e00-9ba7-11eb-84c3-7dde14701fb0.PNG)

2021-04-12 18:52 UTC, timurt requested changes
@AmrBumadian thank you for you contribution, I have only minor requests, 
please fix them and I will merge PR

2021-04-12 18:52 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * <p> For example: </p>
minor: can you please trim spaces, like `* <p>For example:</p>`

2021-04-12 18:52 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *
minor: remove empty line

2021-04-12 18:52 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *
minor: remove empty line

2021-04-12 19:19 UTC, AmrBumadian commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     *
Done, Thank you for the reviews.

2021-04-13 19:00 UTC, timurt approved these changes

2021-04-13 19:00 UTC, merged