Issue #9499: update example of AST for TokenTypes.LITERAL_THROW
checkstyle/checkstyle pull request #9865
Opened 2021-04-13 03:28 UTC by Soist

![image](https://user-images.githubusercontent.com/46078550/114491638-81410600-9c49-11eb-94ff-048424c8a1ee.png)

```
% javac Test.java

% cat Test.java
public class Test {
	void sub() {
		new throw ArithmeticException();
	}
}

% java -jar checkstyle-8.42-SNAPSHOT-all.jar -t Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> Test [1:6]
`--OBJBLOCK -> OBJBLOCK [1:11]
    |--LCURLY -> { [1:11]
    |--METHOD_DEF -> METHOD_DEF [2:1]
    |   |--MODIFIERS -> MODIFIERS [2:1]
    |   |--TYPE -> TYPE [2:1]
    |   |   `--LITERAL_VOID -> void [2:1]
    |   |--IDENT -> sub [2:6]
    |   |--LPAREN -> ( [2:9]
    |   |--PARAMETERS -> PARAMETERS [2:10]
    |   |--RPAREN -> ) [2:10]
    |   `--SLIST -> { [2:12]
    |       |--LITERAL_THROW -> throw [3:2]
    |       |   |--EXPR -> EXPR [3:8]
    |       |   |   `--LITERAL_NEW -> new [3:8]
    |       |   |       |--IDENT -> ArithmeticException [3:12]
    |       |   |       |--LPAREN -> ( [3:31]
    |       |   |       |--ELIST -> ELIST [3:32]
    |       |   |       `--RPAREN -> ) [3:32]
    |       |   `--SEMI -> ; [3:33]
    |       `--RCURLY -> } [4:1]
    `--RCURLY -> } [5:0]

# printing a line only for code that we care
% java -jar checkstyle-8.42-SNAPSHOT-all.jar -t Test.java | grep "3:"
|--LITERAL_THROW -> throw [3:2]
|    |--EXPR -> EXPR [3:8]
|    |    `--LITERAL_NEW -> new [3:8]
|    |       |--IDENT -> ArithmeticException [3:12]
|    |       |--LPAREN -> ( [3:31]
|    |       |--ELIST -> ELIST [3:32]
|    |      `--RPAREN -> ) [3:32]
|   `--SEMI -> ; [3:33]
```
expected update for javodoc is:
```
 |--LITERAL_THROW -> throw
 |   |--EXPR -> EXPR
 |   |   `--LITERAL_NEW -> new
 |   |       |--IDENT -> ArithmeticException
 |   |       |--LPAREN -> (
 |   |       |--ELIST -> ELIST
 |   |       `--RPAREN -> )
 |   `--SEMI -> ;
```

2021-04-13 06:29 UTC, Soist commented
Respected mentors,
Does it matter if the CI build failed? Could you please help me with that if it does? I have attached the error message below. Thank you for your time!

![Screen Shot 2021-04-13 at 11 36 34 AM](https://user-images.githubusercontent.com/46078550/114506586-98d9b800-9c64-11eb-9cb6-84723581c6a1.png)

2021-04-14 17:59 UTC, CryptoSingh1337 commented
@Soist please compile your code example.

2021-04-17 23:29 UTC, romani requested changes
item:

2021-04-17 23:29 UTC, romani commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * new throw ArithmeticException();
`throw new ArithmeticException();`

2021-04-19 14:01 UTC, pbludov requested changes

2021-04-19 14:01 UTC, pbludov commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * |--LITERAL_THROW -&gt; throw
Please remove the leftmost `|` as it leads to nowhere.

2021-05-02 01:10 UTC, closed without merging

2021-05-02 01:10 UTC, romani commented
we lost connection to contributor