Issue #9492: updated example of AST for TokenTypes.LITERAL_RETURN
checkstyle/checkstyle pull request #9885
Opened 2021-04-17 07:10 UTC by Devansu-Yadav

Closes #9492 
![CheckStyle_return_PR_photo](https://user-images.githubusercontent.com/62554685/115104942-fce0d280-9f29-11eb-938b-75eac6609b2b.png)

```
$ cat Test.java

public class Test{
    public void foo(){
        return;
    }
}
```
AST in CLI for the above Java file:-
```
$ java -jar checkstyle-8.41-all.jar -T Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:17]
    |--LCURLY -> { [1:17]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |   `--LITERAL_PUBLIC -> public [2:4]
    |   |--TYPE -> TYPE [2:11]
    |   |   `--LITERAL_VOID -> void [2:11]
    |   |--IDENT -> foo [2:16]
    |   |--LPAREN -> ( [2:19]
    |   |--PARAMETERS -> PARAMETERS [2:20]
    |   |--RPAREN -> ) [2:20]
    |   `--SLIST -> { [2:21]
    |       |--LITERAL_RETURN -> return [3:8]
    |       |   `--SEMI -> ; [3:14]
    |       `--RCURLY -> } [4:4]
    `--RCURLY -> } [5:0]
```
```
# printing lines we are concerned with:-
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "2:\|3:\|4:"

|--METHOD_DEF -> METHOD_DEF [2:4]
|   |--MODIFIERS -> MODIFIERS [2:4]
|   |   `--LITERAL_PUBLIC -> public [2:4]
|   |--TYPE -> TYPE [2:11]
|   |   `--LITERAL_VOID -> void [2:11]
|   |--IDENT -> foo [2:16]
|   |--LPAREN -> ( [2:19]
|   |--PARAMETERS -> PARAMETERS [2:20]
|   |--RPAREN -> ) [2:20]
|   `--SLIST -> { [2:21]
|       |--LITERAL_RETURN -> return [3:8]
|       |   `--SEMI -> ; [3:14]
|       `--RCURLY -> } [4:4]
```
Expected update for JavaDoc:-
```
METHOD_DEF -> METHOD_DEF 
 |--MODIFIERS -> MODIFIERS 
 |   `--LITERAL_PUBLIC -> public 
 |--TYPE -> TYPE 
 |   `--LITERAL_VOID -> void 
 |--IDENT -> foo 
 |--LPAREN -> ( 
 |--PARAMETERS -> PARAMETERS 
 |--RPAREN -> ) 
 `--SLIST -> { 
     |--LITERAL_RETURN -> return 
     |   `--SEMI -> ; 
     `--RCURLY -> } 
```

2021-04-17 07:10 UTC, Devansu-Yadav commented
@timurt @romani Can u pls review this PR?

2021-04-17 13:40 UTC, timurt requested changes

2021-04-17 13:40 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * {@code
you do not need to use `{@code }`

2021-04-17 13:40 UTC, timurt commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * public void foo(){
missing whitespace before curly braces

2021-04-17 14:14 UTC, Devansu-Yadav commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * {@code
Done!

2021-04-17 14:14 UTC, Devansu-Yadav commented on src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> +     * public void foo(){
Done!

2021-04-17 17:29 UTC, romani commented
Please make example as:
```
public int foo(int i) {
        return i + 1;
    }
```

2021-04-18 08:05 UTC, Devansu-Yadav commented
@romani Done! Updated PR description as well.

2021-04-18 14:27 UTC, romani approved these changes

2021-04-18 14:27 UTC, merged