Issue #3082: new filter: SuppressByMessageFilter
checkstyle/checkstyle pull request #9960
Opened 2021-04-30 11:07 UTC by bossever

Closes #3082

2021-04-30 11:12 UTC, bossever commented
GitHub, generate website

2021-04-30 13:00 UTC, bossever commented
GitHub, generate website

2021-05-15 15:28 UTC, bossever commented
@romani @rnveach Please review when you get a chance.

2021-08-25 02:45 UTC, rnveach commented
GitHub, rebase

2021-09-29 01:04 UTC, rnveach commented
@bossever Are you still working on this?

2021-09-29 04:27 UTC, bossever commented
@rnveach 
The development of this filter is complete.

2021-09-29 12:32 UTC, rnveach commented
Then please rebase on the latest master, ensure CI still passes, and I will start looking it over.

2021-09-29 12:36 UTC, rnveach requested changes
Quick look over.

2021-09-29 12:36 UTC, rnveach commented on src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressByMessageFilterTest.java
> +        verifySuppressed(config, getPath("InputSuppressByMessageFilter.java"),
You'll probably be requested to convert this to our BDD testing. I would look over an existing filter on what it will ask for.

2021-09-29 12:36 UTC, rnveach commented on src/xdocs/config_filters.xml
> +              <td>8.43</td>
Version numbers will need to be updated.

2021-10-15 00:27 UTC, rnveach commented
Yes, it looks like you will have to update `XmlMetaReaderTest` as part of this since you are adding a new module.

2021-11-29 00:51 UTC, rnveach commented
@bossever ping

2021-12-01 09:03 UTC, romani commented
PR will be closed at the end of December 2021 if no activity happen.

2022-02-19 13:37 UTC, nmancus1 commented
We lost contact with author, anyone is welcome to reuse code from this PR to solve issue.

2022-02-19 13:37 UTC, closed without merging